### ISSUE TITLE
Toggle-Shortcuts

### ISSUE THREAD

**Issue by Waboodoo** [Waboodoo/HTTP-Shortcuts#10]
Add special shortcuts that toggle between two different requests.

**Comment by baquilla** [comment]
Maybe it's interesting that the icon also changes according to the request to be executed, so one can know what's going on. The icon could be chosen or simple turn grey or change background.

**Comment by Waboodoo** [comment]
I think changing the icon of a shortcut on the home screen is not possible on Android. If anything the icon could only be changed for the shortcut in the list within the app, but not outside.

**Comment by baquilla** [comment]
Ops! It's a pity. I think it also depends on the launcher the user has. 
It could be done with widgets, but it's not the matter of this issue. If a widget is used, then some feedback could be shown depending on response. It's an idea.
Great app, great work. Thanks!

**Comment by Waboodoo** [comment]
Yes, with a widget there would be much more flexibility. However, at this point, there are no plans to extend the app with a widget.
