### ISSUE TITLE
Feature Request : Triggered via broadcast / Intent

### ISSUE THREAD

**Issue by jemmail** [Waboodoo/HTTP-Shortcuts#100]
The idea is to trigger a shortcut once an "event" is raised.
Maybe possible via a listener on a broadcast / Intent.

**Scenario : call a Shortcut (to a Philips HUE for example) which wake up Lights when the alarm I've set on my phone rings.**

list of alarm by brand
[https://stackoverflow.com/questions/4115649/listing-of-manufacturers-clock-alarm-package-and-class-name-please-add/15876187](url)

Once again.. many thanks for your superb app !
Phil

**Comment by Waboodoo** [comment]
This is something that can already be achieved by combining the app with a 3rd party automation app such as [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en) or [E-Robot](https://play.google.com/store/apps/details?id=com.bartat.android.robot). Both of these apps allow you to build such workflows and trigger the execution of a shortcut. I recommend you have a look at those.

**Comment by Waboodoo** [comment]
For more information on how to trigger a shortcut from an external app see https://http-shortcuts.rmy.ch/faq#trigger-from-other-app
