### ISSUE TITLE
shortcuts on home screen

### ISSUE THREAD

**Issue by Adam-GitHubq** [Waboodoo/HTTP-Shortcuts#101]
After update (1.21?) shortcut from home screen stopped working, just request to the outside net.
It's working on app, but when I use option 'Place on home screen' & use it from home screen it doesn't work correctly Failed to connect to ....

**Comment by Waboodoo** [comment]
Android restricts how apps can use network capabilities when not in the foreground. This may be what's causing your problem. You either need to allow this explicitly for the app by changing the Android settings, or alternatively you can change how the shortcut's response is handled. If you set it to "Show as Dialog" or "Show as Window" the problem you're seeing should no longer occur.
