### ISSUE TITLE
Toggle variables not being requested

### ISSUE THREAD

**Issue by bisho** [Waboodoo/HTTP-Shortcuts#103]
If I add a toggle variable and a shortcut uses it, it does not show any dialog to change to toggle.

**Comment by Waboodoo** [comment]
That is intended behavior. The "toggle" type simply switches from one value to the next every time it is used. What you're looking for is the "select" type, which displays a dialog where you can select a value.

**Comment by bisho** [comment]
Ouch, sorry, my bad.

Might be cool to offer alternate iconds for each of the options, so it is easy to know the state. It will become more usefull.

**Comment by Waboodoo** [comment]
I have plans to add a feature to change the shortcut icon dynamically. This would allow what you are suggesting. Currently, however, there is no timeline for this.
