### ISSUE TITLE
Feature Request: allow curl --data-binary equivalent + File chooser

### ISSUE THREAD

**Issue by aslmx** [Waboodoo/HTTP-Shortcuts#104]
Hey there,

first of all: thanks for this nice App! I use it to send HTTP requests to my jabber server that result in XMPP messages being triggered. Very helpful!

I now discovered filebin (https://github.com/espebra/filebin/) which has a nice Web Service API that allows to upload files via curl --binary-data. 

Works like a charm!

I now just need a decent tool, that allows me to Post a photo or any other binary and i think HTTP-Shortcuts would be a decent fit. 

I imagine that there would be a file-variable which can either be fixed or set to choose from the regular file chooser. 
Then you just need to take a photo, launch the HTTP-Shortcut and you could post it into a nice filebin to share it... 
We could even combine it with https://github.com/Waboodoo/HTTP-Shortcuts/issues/42 so we can share pictures from other Applications or from the camera directly. 

The ice-topping would be that i can click on a HTTP Shortcut and it launches the camera... (could be covered by variable to be {{camera}} or something. 

I know i'm dreaming ;-) 
But maybe someone else finds this to be useful also...

Thanks for considering!

**Comment by Waboodoo** [comment]
Thanks for the suggestion. This is also on my personal wishlist, but so far I didn't have the time to implement it. Something like this is in my backlog, and I hope I'll eventually get to it. 👍🏻

**Comment by Waboodoo** [comment]
Part of this is now possible with version 1.29.0, which allows you to send files as form parameters. The files can either be picked with a file picker, or shared into the app. It is not yet possible to send a file as the full request body, that's something I want to look into in a future release. There I also want to explore the idea of directly opening the camera app instead of just a file picker.

**Comment by Waboodoo** [comment]
Closing this now because as of version 1.32.0 it is possible to pick a file to be used as the request body.
