### ISSUE TITLE
Fix support for KLWP

### ISSUE THREAD

**Issue by jghaanstra** [Waboodoo/HTTP-Shortcuts#105]
[KLWP](https://play.google.com/store/apps/details?id=org.kustom.wallpaper) is a live wallpaper app allowing you to fully customize your Android wallpaper. It has the ability to add elements and assign click actions including launching shortcuts.

When selecting to launch a shortcut from HTTP Requests app you enter the HTTP requests app for selecting a shortcut (same as in Tasker) but when selecting a shortcut  the phone freezes with a black screen. Not sure if this is an issue with HTTP Requests app or with KLWP though.

**Comment by Waboodoo** [comment]
I'm not familiar with KLWP, but most likely this is the same issue that exists with other apps that allow to pick shortcuts. I have included a workaround to address this in version 1.22. When selecting a shortcut to be used in another app you are now prompted to select a method, either "Default" or "Legacy". Try selecting "Legacy". If this does not fix the issue please let me know.

**Comment by jghaanstra** [comment]
Awesome, just updated and tested it and it works fine in legacy mode. Huge thanx!
