### ISSUE TITLE
multipart/form-data: incorrect boundary delimiter

### ISSUE THREAD

**Issue by micha5104** [Waboodoo/HTTP-Shortcuts#106]
According to RFC 7578 section 4.1. the boundary delimiter is 

> constructed using CRLF, "--", and the value of the "boundary" parameter

 (https://tools.ietf.org/html/rfc7578#section-4.1)

The app only writes a LF ('\n') before the "--".
See ShortcutRequest.kt lines 56ff.

I suppose all the other line breaks in a multipart/form-data should also be a CRLF ("\r\n") instead of just LF ("\n").

**Comment by Waboodoo** [comment]
Thanks for reporting. This is now fixed in version 1.22.
