### ISSUE TITLE
Feature Request: Extract from xml body

### ISSUE THREAD

**Issue by kalemontes** [Waboodoo/HTTP-Shortcuts#107]
Hi, am using HTTP-Shortcuts and so far i found it great!

Am making requests to a webserver and extrating some data from a html/xml response using the "substring extraction type" to check if a service is up. It does the job but in some cases it's not ideal because the page changes and i have to re-calculate de start and end indexes.

I was wondering if it's possible to add an [xpath ](https://developer.android.com/reference/javax/xml/xpath/XPath)extration type.

Thanks

**Comment by RighteousPotato** [comment]
Would love to see this added too

**Comment by Waboodoo** [comment]
I'm still trying to work out what would be the best way to support this. I'm wondering if it would suffice to just provide a simple function that takes an XML string and an xpath expression as arguments. I'm open to suggestions.

**Comment by Waboodoo** [comment]
There will be a `parseXML(xml)` function added in version 2.16.0, which can parse an XML string and return an object representation of it. Documentation will follow once that version gets released.

**Comment by Waboodoo** [comment]
Version 2.16.0 is now released, which has support for the `parseXML` function. It allows to parse XML into a JS object representation which makes it possible to extract values and attributes from it.
The documentation can be found here: https://http-shortcuts.rmy.ch/scripting#parse-xml

As always, if you find any issues or you find that this new function is not sufficient for your usecase, don't hesitate to reach out.
