### ISSUE TITLE
enhancement request: confirmation

### ISSUE THREAD

**Issue by clach04** [Waboodoo/HTTP-Shortcuts#112]
The current confirmation support (cancel/ok) works well. It would be nice if additional confirmation types could be added:

  * PIN (require a simple PIN, it would not be super secure but would require deliberate intent to execute the commend)
  * slider - a slider would be faster in many cases

**Comment by Waboodoo** [comment]
This sounds like a good idea. I've added it to my backlog.
Can you explain that "slider" part a bit more? I'm not sure I understand what you mean by that.

**Comment by clach04** [comment]
After rereading i see that's unclear! Slide to unlock.

Something like https://github.com/cortinico/slidetoact/blob/master/README.md

**Comment by Waboodoo** [comment]
I have decided that I would like to keep the confirmation feature as simple as it is now and not add more complexity. If you do with to have a more advanced or customized confirmation step, you can achieve this by adding a piece of JavaScript code to the shortcut's Scripting section, which will run before the execution of the shortcut. For example, the following code snippet would prompt the user to enter a PIN and only continue if the correct PIN (1234) is entered:

```js
if (prompt('Please enter your PIN to continue') != '1234') {
    abort();
}
```

For more information about Scripting see https://http-shortcuts.rmy.ch/scripting
