### ISSUE TITLE
HTTP 301 redirects are not properly processed

### ISSUE THREAD

**Issue by pawalther** [Waboodoo/HTTP-Shortcuts#114]
If an API endpoint answers with an HTTP 301 redirect, the app neither handles the redirect nor treats this as an result.

Scenario:
The POST request to a endpoint generates a HTTP 301 redirect, which just changes the scheme from http to https. The app does not treat the redirect as results, but tries to follow the redirection.
But new request got reset (http method is GET, no basic auth credentials, no request body).

**Comment by Waboodoo** [comment]
I'm a bit late here with a response, but this issue should now be fixed. You have the option for each shortcut to select whether or not the app should follow HTTP redirects or not.

Closing this now, please re-open if there is still an issue.
