### ISSUE TITLE
Multiple delayed requests not send

### ISSUE THREAD

**Issue by pawalther** [Waboodoo/HTTP-Shortcuts#115]
Delaying multiple request for the same shortcut does not work properly.

Scenario:
Without internet connection several request for one shortcut were issued (with different values for a single variable). Upon connection to the internet only the first request was sent to the API endpoint. All other requests did not reach the endpoint.

**Comment by Waboodoo** [comment]
As of now, this is intended behavior. A shortcut can only be queued for delayed execution once at a time.
I can see however that this is a limitation, and I'll look into changing this so that multiple executions can be queued.

**Comment by Waboodoo** [comment]
This will be fixed in the upcoming version 1.32.0.

**Comment by Waboodoo** [comment]
Closing this now as 1.32.0 was release and this issue should be fixed. Please let me know if you still encounter problem.
