### ISSUE TITLE
Suggestion: catch ANR / Crash when slider is misconfigured step width 0

### ISSUE THREAD

**Issue by aslmx** [Waboodoo/HTTP-Shortcuts#118]
Hey,

just added a rather complex call with a couple of parameters. HTTP-Shortcuts would always crash with ANR (version 1.22) and simply close (version 1.23).

When using log cat i found out that there is a divide by zero. 

Checking all my variables again, i realized i had accidentially set the step-width (not sure what the english name for this field is) to 0 [when i wanted to configure it to be 0.1 - which is not possible...]

This is the Stack

01-28 18:31:53.033  4339  7104 I ActivityManager: START u0 {act=ch.rmy.android.http_shortcuts.resolveVariablesAndExecute dat=content:/6 flg=0x10010000 cmp=ch.rmy.android.http_shortcuts/.activities.ExecuteActivity (has extras)} from uid 10146
01-28 18:31:53.121 25730 25730 D AndroidRuntime: Shutting down VM
01-28 18:31:53.125 25730 25730 E AndroidRuntime: FATAL EXCEPTION: main
01-28 18:31:53.125 25730 25730 E AndroidRuntime: Process: ch.rmy.android.http_shortcuts, PID: 25730
01-28 18:31:53.125 25730 25730 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.rmy.android.http_shortcuts/ch.rmy.android.http_shortcuts.activities.ExecuteActivity}: java.lang.ArithmeticException: divide by zero
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: Caused by: java.lang.ArithmeticException: divide by zero
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at ch.rmy.android.http_shortcuts.variables.types.SliderType.findSliderMax(SliderType.kt:62)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at ch.rmy.android.http_shortcuts.variables.types.SliderType.createDialog(SliderType.kt:25)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at ch.rmy.android.http_shortcuts.variables.VariableResolver.resolveVariables(VariableResolver.kt:93)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at ch.rmy.android.http_shortcuts.variables.VariableResolver.resolve(VariableResolver.kt:28)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at ch.rmy.android.http_shortcuts.activities.ExecuteActivity.resolveVariablesAndExecute(ExecuteActivity.kt:155)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at ch.rmy.android.http_shortcuts.activities.ExecuteActivity.onCreate(ExecuteActivity.kt:104)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
01-28 18:31:53.125 25730 25730 E AndroidRuntime: 	... 9 more
01-28 18:31:53.136 25730 25730 I zygote64: Deoptimizing void com.bugsnag.android.Breadcrumb.toStream(com.bugsnag.android.JsonStream) due to JIT inline cache
01-28 18:31:53.147  4339  7104 W ActivityManager:   Force finishing activity ch.rmy.android.http_shortcuts/.activities.ExecuteActivity
01-28 18:31:53.152  4339  7104 W ActivityManager:   Force finishing activity ch.rmy.android.http_shortcuts/.activities.MainActivity
01-28 18:31:53.178 25730 25730 I Process : Sending signal. PID: 25730 SIG: 9
01-28 18:31:53.362  4339  4493 W InputDispatcher: channel '9cd0ee9 ch.rmy.android.http_shortcuts/ch.rmy.android.http_shortcuts.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-28 18:31:53.363  4339  4493 E InputDispatcher: channel '9cd0ee9 ch.rmy.android.http_shortcuts/ch.rmy.android.http_shortcuts.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-28 18:31:53.364  4080  4080 I Sensors : batch - accelerometer_sensor try to batching with 66667000
01-28 18:31:53.365  4339  7104 I ActivityManager: Process ch.rmy.android.http_shortcuts (pid 25730) has died: fore TOP 

I'm raising a seperate issue to suggest fractional values for step width ;)

**Comment by Waboodoo** [comment]
Thanks for the report, good catch. I'll fix this for the next release. Step size 0 should not be allowed.

**Comment by Waboodoo** [comment]
This is fixed in version 1.24
