### ISSUE TITLE
Feature Request: fractional values for Slider step-width

### ISSUE THREAD

**Issue by aslmx** [Waboodoo/HTTP-Shortcuts#119]
For the slider we can define Min and Max value as well as the increment / step width.

I have a use case where i'd need a step width of 0.1.

It is not possible to set 0,1 or 0.1. 

I guess it is meant to be an integer. But i need a float  ;-)

Thanks for considering!

**Comment by Waboodoo** [comment]
This sounds useful, and easy to implement. I'll add it to the todo list for next release.

**Comment by aslmx** [comment]
> Turns out my previous message was a bit too optimistic, but better late than never: I have implemented this now and will include it in the next release.

Thanks!

Apparently I have totally forgotten about the use case in the meanwhile :|

**Comment by Waboodoo** [comment]
Understandable, it's been a while after all... In case you remember though, the feature is now available in the newly released version 2.17.0.
