### ISSUE TITLE
Shortcuts with parameters

### ISSUE THREAD

**Issue by Waboodoo** [Waboodoo/HTTP-Shortcuts#12]
Create shortcuts where upon invoking them the user is prompted with a previously user-defined list of options so choose from. The selected option is then inserted into the request, either as part of the URL or part of a request parameter.

Example:
Click thermostat shortcut -> select "20°C" -> URL "http://my-thermostat?temperature=20" is requested

**Comment by mwcz** [comment]
This would be awesome!  I just set up a REST API to control the color of my monitor backlight and discovered HTTP-Shortcuts.  Exactly what I was looking for, and it would be even cooler if there were parameter prompts like this.
