### ISSUE TITLE
Add clipboard contents as available variable

### ISSUE THREAD

**Issue by pataquets** [Waboodoo/HTTP-Shortcuts#121]
Thanks for this nifty and great tool!
Also adding the option to show clipboard contents as default value for string variables input values would be helpful.

**Comment by Waboodoo** [comment]
In version 2.20.0 I'm adding the `getClipboardContent()` variable, which will allow to handle this usecase, with a bit of Scripting. 

One could then basically create a static variable `my_variable` and populate its value via the following script when executing a shortcut:

```js
const clipboardValue = getClipboardContent();
const myValue = prompt("Please enter a value:", clipboardValue);
setValue("my_variable", myValue);
```

**Comment by Waboodoo** [comment]
@pataquets Currently no. You could however simulate this behavior, by replacing your Text Input variable with a Static Variable and then using the following piece of code JS at the beginning of your shortcut:

```js
// Let's assume your variable is named "my_variable"

const value = prompt("Please enter a value:", getClipboardContent());
if (value == null) {
    abort();
}
setVariable("my_variable", value);
```

That will open a text input dialog with the prompt "Please enter a value" and prefill it with whatever is currently in the clipboard. It then saves whatever the user entered as the value of the "my_variable" variable, which can then be used normally as part of the HTTP request.

**Comment by pataquets** [comment]
@Waboodoo Thanks!
