### ISSUE TITLE
HTML Web View for Response Type

### ISSUE THREAD

**Issue by thejeshgn** [Waboodoo/HTTP-Shortcuts#122]
As of now the Response Type can be Toast, Dialog or Window. But none of them can actually display rendered HTML.

Can we have the ability for Dialog or Window to display rendered html? It will be great to get formatted information. It can be a webview.

Interesting uses will be
- Does something and returns a SVG image
- Does something and return an HTML table

**Comment by Waboodoo** [comment]
This is now (partially) possible:

- "Dialog" and "Window" response type have basic support for HTML formatting (bold, italics, font color, ...)
- the "Window" response type will display the response in a webview if the response's content type is "text/html".
