### ISSUE TITLE
SSL client auth with Android key chain

### ISSUE THREAD

**Issue by spali** [Waboodoo/HTTP-Shortcuts#123]
Would love to see support for requests with client auth cert support.
I use a client cert imported in android for authentification. This is nearly transparent independent if I connect local without the need of a client cert and remote where i get asked for the cert by i.e. chrome.
Thats my only missing feature in this great app.

**Comment by Tytouc** [comment]
I agree: Client Auth with SSL is a must to secure access to a server. I vote for this feature

**Comment by Waboodoo** [comment]
I will include support for client cert authentication as part of the upcoming 2.3.0 release.

**Comment by Tytouc** [comment]
This would be perfect, thanks. Any idea of release date of this version?

**Comment by Waboodoo** [comment]
Version 2.3.0 is now released. It might take a few hours for it to become available on the Play Store and a few days to reach F-Droid.
