### ISSUE TITLE
Please help to display rendered HTML.

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#124]
Please, Can we have the ability for Dialog or Window to display rendered html? It will be great to get formatted information. It can be a webview.
Interesting uses will be
Does something and returns a SVG image
Does something and return an HTML table

**Comment by Waboodoo** [comment]
Thanks for the suggestion. I'll try to get this in once I find the time to do so.

**Comment by Waboodoo** [comment]
With the 1.24 release, it is now possible to display the response in a webview. For this to work the response type "Window" has to be selected, and the "Content-Type" header of the HTTP response has to indicate that it is type "text/html".
