### ISSUE TITLE
Is it possible to save the response (at least the body) in file?

### ISSUE THREAD

**Issue by Mid-Bar** [Waboodoo/HTTP-Shortcuts#125]

**Comment by Waboodoo** [comment]
Not yet, at least not automatically. You can use the "Share" button in the window that displays the response to export it to another app that could save it to a file.

I'll add this to my backlog. It seems like a good addition, and it has been requested before.

**Comment by Waboodoo** [comment]
As of version 2.0.0, there is the option to save the response into a file. You'll have to use the "Fullscreen Window" display type for your shortcut. In the fullscreen window's menu bar you'll find a button to save the response, next to the option to share it.
