### ISSUE TITLE
Feature request: custom proxy

### ISSUE THREAD

**Issue by internety** [Waboodoo/HTTP-Shortcuts#126]
I am heavily using WSGI apps running within mitmproxy instance, bound to nonexistent domains to avoid name collisions possibility. That would be great to have an option to define custom proxy, preferably on per shortcut basis. It would make my life much easier ;)

**Comment by Waboodoo** [comment]
Thanks for the input. I've added it to the backlog. It sounds like a good addition.

**Comment by Waboodoo** [comment]
Proxy support will be available in version 1.29.0, which I'm planning on releasing in the next few days
