### ISSUE TITLE
New Variables/improvements

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#127]
Kindly can you add image post variable? I want to upload image to my server using this app

**Comment by Waboodoo** [comment]
Uploading images (or files in general) can be achieved by changing the Request Body type to "File (Picker)", which will allow you to pick a file when the shortcut is executed and the file's content is used as the request body. Alternatively you can use the Request Body type "Parameters (form-data)" which also allows providing files as form parameters. There is no need to use variables for either of these usecases.
