### ISSUE TITLE
Javascript on response success

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#132]
I am trying to pass javascript on success(POST-REQUEST ACTIONS).
HERE MY CODE
<html>
<head>
<script type="text/javascript">
function disp_prompt()
{
var name=prompt("Please enter your name","")
var Age=prompt("Please enter your Age,your name is" + name + "","")
var Email=prompt("Please enter your Email","")
if (name!=null && name!="")
{
if (Age != null && Age != "")
{
document.write("Hello " + name + "! Your age is "+ Age);
}

}
}
</script>
</head>
<body>
<form>
<input type="button" onclick="disp_prompt()" value="Display a prompt box">
</form>
</body>
HOW CAN I PASS THIS PEACE OF CODE ?

**Comment by Waboodoo** [comment]
I'm unsure of what you are trying to achieve. The app does not support running JavaScript at the moment.

**Comment by stevenjohnk** [comment]
Thanks you for response, I am referring here as attached, give me a sample working script to start with, I am running developer version.
Thanks
![Screen Shot 2019-06-12 at 12 46 07](https://user-images.githubusercontent.com/3540813/59341405-739a5c80-8d10-11e9-8dd3-2f9fd18ea55f.png)

**Comment by Waboodoo** [comment]
This feature is still under development and not yet stable. You can run arbitrary JS with it but there is currently no way to export data in any way. You can try one of the following, but it is likely to stop working eventually:

```js
_runAction("show_dialog", {"text": "Hello world!"});
```

```js
_runAction("show_toast", {"text": "Hello world!"});
```

**Comment by stevenjohnk** [comment]
Thank you for your response, I tried and worked(no crash), I have an Idea which may be useful, while under developing allow this features follows:
1. instead of dialog, toast add also prompt, on success user can enter and POST additional data to server
2. Allow php code so that user can do some calculations
3. Allow to parse results from request or Constant variable
Thanks bro, good work

**Comment by Waboodoo** [comment]
For now, I'd like to keep the response handling as clean as possible and not add more complex user interaction to it. If you need to post additional data, that would be another request, so you could just trigger another shortcut that sends this request.

I will not add PHP support, as that adds immense complexity and may not even be possible. You can already do calculation using JavaScript. What PHP feature would you need that is not covered by JS?

Parsing the response is also already possible with JavaScript. E.g. to parse JSON you can use `JSON.parse()`
