### ISSUE TITLE
Confirmation popup

### ISSUE THREAD

**Issue by fmarzocca** [Waboodoo/HTTP-Shortcuts#133]
Is there a way to add a confirmation popup (i.e. Are You Sure) before launching the request? This is useful to avoid unexpected execution.

**Comment by stevenjohnk** [comment]
This is implemented ready, confirmation!

**Comment by fmarzocca** [comment]
I found it! Thanks.


- Sent from my mobile phone. Sorry for typos -

Il dom 23 giu 2019, 18:46 stevenjohnk <notifications@github.com> ha scritto:

**Comment by scasic** [comment]
Can I specify my own confirmation text?

**Comment by Waboodoo** [comment]
Currently there is no way to specify a custom confirmation message.
