### ISSUE TITLE
Can't use variables.

### ISSUE THREAD

**Issue by cstumph** [Waboodoo/HTTP-Shortcuts#134]
Unsure if I am doing something wrong here. 5 mins into using the app I'm unable to set up my first request intending to extract a cookie value.
No matter what I do it tells me I have no configured variables. When I click create it takes me to a screen showing me the variable I created.

User error?

![Screenshot_20190728-121159](https://user-images.githubusercontent.com/341658/62011793-f137f180-b131-11e9-8ef1-5f9bdf1dc6b2.png)
![Screenshot_20190728-121228](https://user-images.githubusercontent.com/341658/62011796-f5640f00-b131-11e9-85c1-056cc1150fce.png)
![Screenshot_20190728-121243](https://user-images.githubusercontent.com/341658/62011797-f8f79600-b131-11e9-943b-ce6ad9d6e726.png)

**Comment by Waboodoo** [comment]
The "Extract from Cookie" action, as well as all the other actions that extract data from the response can only store that data into variables of type "Constant". Your variable is of type "Text Input".

**Comment by cstumph** [comment]
Ah I see. Maybe I'm misinterpeting text input as "string" value. I would have (and did) assume a constant was for a static value that I'd want to manually set beforehand.
