### ISSUE TITLE
Markup diplayed in response

### ISSUE THREAD

**Issue by fmarzocca** [Waboodoo/HTTP-Shortcuts#135]
I am using HTTP Shortcuts v.1.23.0.
Some of my responses are containing HTML code (i.e.: <br> for newline) and the tags get printed in the response dialog. This is quite annoying. I have replaced the <br> with \n and included the response in `<pre>` tags, but also the `<pre> `tags are printed.

How can I do to have a clean response?

**Comment by Waboodoo** [comment]
The "dialog" response type can only display plain text. It does not support HTML markup, or any markup for that matter. In the upcoming release of 1.24 I'm adding support for HTML responses, but only in the "Window" response type. Maybe that will help.

**Comment by fmarzocca** [comment]
Ok, thanks anyway. Maybe you could rip-off markup from the plain text dialog?

**Comment by Waboodoo** [comment]
This is now (partially at least) supported with the 1.24 release. Certain HTML formatting tags can be used in dialogs and the "Window" response type.
