### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by fmarzocca** [Waboodoo/HTTP-Shortcuts#136]
I am in the need to launch multiple simoultaneous commands (i.e. to close all the shutters of the house). Is there any way to achieve this target?

**Comment by Waboodoo** [comment]
This is only somewhat possible. You could add an action ("Success Action" to be more precise) to one shortcut that triggers another one. When the first one is triggered and succeeds, it would then trigger the other one. You could create a dummy shortcut (i.e., one that points to something trivial) and have it trigger all the other shortcuts.

**Comment by fmarzocca** [comment]
Great! Not simoultaneous, but good anyway.
Thanks.
