### ISSUE TITLE
Hidden Shortcut

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#137]
Kindly while under development can you add option to hide shortcut? example I want to trigger a shortcut on success but I do not want this shortcut to be shown to user.
But still can be executed

**Comment by Waboodoo** [comment]
If the shortcut is hidden, how would you edit it?
Would a hidden category also work for your usecase?

**Comment by stevenjohnk** [comment]
Thanks for reply, yes a hidden category can work, good think beyond.

**Comment by fmarzocca** [comment]
BTW, what is an hidden category? Or, how can you hide a category?

**Comment by stevenjohnk** [comment]
This is how I think
![swbd](https://user-images.githubusercontent.com/3540813/63642422-5a763a80-c6c7-11e9-918c-ba57f375547c.png)

**Comment by Waboodoo** [comment]
A feature to hide a category will be available with the next version (1.27.0).
