### ISSUE TITLE
Recurrent or scheduled task

### ISSUE THREAD

**Issue by DocPepperFR** [Waboodoo/HTTP-Shortcuts#139]
Something that could be nice is to be able to schedule the execution of a task at a fixed time, or according to a timer, like a crontab, without an app like tasker, directly in the app.

**Comment by Waboodoo** [comment]
Functionality like this would go too far into the direction of building a fully fletched automation app, like Tasker. As such apps already exist and can integrate with this app, I see no need to replicate that functionality.
