### ISSUE TITLE
More variable options

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#140]
Please do not be tired of my suggestions; I would advice to think about more options and type of variables, example image variable which can post image, from camera or from gallery, another example is scanner variable which can scan and read a barcode, in some variables ,you added Title as optional, also add Body as optional so that user can add some instructions and can be useful if can be a parse of body response or any text.

**Comment by Waboodoo** [comment]
This issue covers various topics, most of which have been addressed in the mean time, at least partially:
- You can configure a shortcut to take a file or image (from the file system or camera) as its request body or as a form parameter. You'll find these options when creating/editing a shortcut and opening the "Request Body" screen from there.
- You can invoke use the `scanBarcode()` function to open a barcode scanner app (see https://http-shortcuts.rmy.ch/scripting#scan-barcode)
- I will consider the idea for adding a dialog message body, as it sounds generally useful and easy to implement

In the interest of cleaning up a little, I'm closing this issue now.
