### ISSUE TITLE
Editing on computer

### ISSUE THREAD

**Issue by fmarzocca** [Waboodoo/HTTP-Shortcuts#141]
Is there any way to edit the javascript code from a standard PC keyboard and then upload it to the application? Typing a long javascript code on the phone is driving me mad!
:-)

**Comment by exw777** [comment]
You can upload code files to cloud, open in html viewer on mobile and copy to app!

**Comment by fmarzocca** [comment]
Yes, a little bit tricky but it could work. Thanks.


- Sent from my mobile phone. Sorry for typos -

Il sab 24 ago 2019, 18:57 exw777 <notifications@github.com> ha scritto:

**Comment by stevenjohnk** [comment]
My recommendation is to add import from url(online) where you will host json file, which can be edited anytime and in realtime

**Comment by Waboodoo** [comment]
An option to import shortcuts from a URL will be available in the next release (1.27.0)

**Comment by Waboodoo** [comment]
Editing shortcuts remotely on a computer is now possible as of the 1.39.0 release. You'll find further instructions on the app's settings screen.
