### ISSUE TITLE
Feat Request: more coding freedom

### ISSUE THREAD

**Issue by fmarzocca** [Waboodoo/HTTP-Shortcuts#142]
This is one of my needs: 
- execute a shortcut
- evaluate its response (if string contains...)
- after evaluation, show a confirmation box (do you want to proceed)
- trigger another shorcut on user’s answer.

I am currently doing this with the help of my REST server, but I think it could be done in HTTP Shortcuts

**Comment by stevenjohnk** [comment]
Sure this is very useful!

**Comment by Waboodoo** [comment]
This is already kinda possible, albeit cumbersome to set up. With a combination of the "triggerShortcut" action and the "Require confirmation before execution" feature, you could have a setup like this.

I'll see if there's anything I can do to facilitate this in the future.

**Comment by Waboodoo** [comment]
Closing this now, as with version 1.29.0, all of the above mentioned steps can be implemented using the scripting feature in the app.
