### ISSUE TITLE
Variables in the "Request Body / Parameters" section do not work

### ISSUE THREAD

**Issue by exw777** [Waboodoo/HTTP-Shortcuts#143]
Variables in the "Request Body / Parameters" section do not work if "Request Body Type" is "custom text".
After closing this window, and when re-opening, the variable becomes plain text
<img width="374" alt="2019-08-23_192812" src="https://user-images.githubusercontent.com/46466764/63640641-4b818f00-c6ab-11e9-874a-bbcbd12f3aac.png">
<img width="406" alt="2019-08-23_192832" src="https://user-images.githubusercontent.com/46466764/63640644-4de3e900-c6ab-11e9-8471-9dd6f34dd6a4.png">

**Comment by thejeshgn** [comment]
And it doesn't prompt.

**Comment by Waboodoo** [comment]
Thanks for reporting this. I have identified the source of the bug and will fix it for the upcoming 1.24.1 release.

**Comment by thejeshgn** [comment]
Ref #144 - same
