### ISSUE TITLE
basic auth not working

### ISSUE THREAD

**Issue by thejeshgn** [Waboodoo/HTTP-Shortcuts#144]
Says no authentication.

It used to work in the previous version.

**Comment by Waboodoo** [comment]
Can you provide some more information about the issue you're seeing? I cannot reproduce any problem with the basic auth feature.

**Comment by thejeshgn** [comment]
I figure. I had used variables (constant) for username and password. They don't work in the latest updates.

I need to put the username and passwords directly.

**Comment by thejeshgn** [comment]
Duplicate and hence closing
