### ISSUE TITLE
Android libraries access from pre/post-request actions

### ISSUE THREAD

**Issue by 14geronimo** [Waboodoo/HTTP-Shortcuts#148]
Thank you for this absolutely brilliant app, extremely well thought-through functionally.

I wanted to pass a unique device ID on my requests, and, to save having to configure a constant manually, I thought about using the Android ID in a pre-request script. However, none of the objects I've found referenced out there (android.os.Build.SERIAL, Secure, Android) to get to this ID are unknown to the pre-request context.

Is there a way to achieve this from pre-request scripts please?

**Comment by Waboodoo** [comment]
Currently, there's no way to get such a device identifier in the Javascript context.
I'll see if I can add something like this for the next version.

**Comment by 14geronimo** [comment]
Thanks for responding, very much appreciated. I think it would indeed be a useful feature for registering devices to an online service, that kind of thing.

I was looking for a 'Buy me a beer' button on your website, but that's another question ;)
