### ISSUE TITLE
3× APK size increase from v1.22.0 → v1.24.2⁈

### ISSUE THREAD

**Issue by TPS** [Waboodoo/HTTP-Shortcuts#150]
@Waboodoo How/why did https://github.com/Waboodoo/HTTP-Shortcuts/commit/5d71e8ac1ae6d159c9f45b55e80c9176487ecc8f ("ReadMe")  & https://github.com/Waboodoo/HTTP-Shortcuts/commit/6307d471bb795ff284377c0f34d090491537bcab ("Various Fixes") lead to a 3× size increase from v1.22.0 (13.8 MB) → v1.24.2 (43.4 MB)⁈  It seems mighty weird, given the app's purpose & those mundane commit titles.…

**Comment by Waboodoo** [comment]
There are way more commits in between 1.22.0 and 1.24.2 than those 2. I haven't looked into this yet, but I suspect the reason why the APK size increased that much is the LiquidCore dependency that I added to allow the execution of JavaScript code in the app (https://github.com/Waboodoo/HTTP-Shortcuts/blob/develop/HTTPShortcuts/app/build.gradle#L113)

I'll see if I can reduce the size somehow, but I can't make any promises. You will get a significantly smaller APK if you install the app via the Play Store, due to Android App Bundles, so I expect this to have little impact on most users.

**Comment by TPS** [comment]
Per https://github.com/Waboodoo/HTTP-Shortcuts/commits/develop, those are 2 are the only commits logged since 9/9/19, when v1.22.0 was released.  Anything else isn't apparent.  Why is JS needed?

**Comment by Waboodoo** [comment]
v1.22.0 was released on September 9th _2018_, not _2019_. I also forgot to publish the APK for v1.23.0 in between (I don't have an automated process for this yet). There are definitely lots and lots of commits between 1.22.0 and 1.24.2.

JavaScript is needed to give the user much more power and flexibility in how the HTTP response can be processed, and how data can be prepared for a request. You can find more about that here: http://waboodoo.ch/http-shortcuts/scripting.

Given that this is an intended change, and that I unfortunately don't see an easy way to reduce the APK size here, I'm closing this issue.

**Comment by TPS** [comment]
@IzzySoft I don't know if you noticed that this latest release _probably_ exceeds your repo's limits, though somehow it ended up in there.

**Comment by IzzySoft** [comment]
Oh my, yes indeed – more than double the original size limit, and still 1/3 above the current one. @Waboodoo what needs 40M+ to create shortcuts? A 20M `libnode.so` for multiple platforms, ouch (that library wasn't present in v1.22.0, neither was `libliquidcore.so`). If that library is really worth tripling the APK size, maybe you could split off a smaller "ARM-only" APK? That's the most frequent use case, and would end up around 20..25M. Mips is quite rare, and x86 devices are few…

**Comment by Waboodoo** [comment]
This is an open-source project, so feel free to build such an APK. I currently don't have the capacity to focus on this. The increase in APK size is unfortunate, but I expect most users of this app would get it via the Play Store, where they can benefit from app bundles and get a much smaller binary size, so personally I don't see this is a big priority.

**Comment by IzzySoft** [comment]
Not being a dev myself (and lacking the environment), I unfortunately can't …

**Comment by IzzySoft** [comment]
@Waboodoo I just checked again. Reason are most likely the "native libs" for multiple architectures. If you could offer an (additional) APK just including armeabi+x64 (i.e. no mips, no x86_64, no armv7/armv8), resulting size would be down from the current 46M to ~18M – while that APK would still cover most devices (MIPS Android devices are rather rare, and x86_64 can run x86, same with the ARMs).

Could you do that? As pointed out, most of us "simple users" can't. Thanks in advance!

**Comment by Waboodoo** [comment]
Yes, a large part of the app's size comes from the bundled binaries, mainly for Realm and Liquibase.
I will publish a "simplified" APK next time I create a release, but I can't guarantee to do that for every release, as I have not set up any automation for this yet and have to do it manually.

**Comment by IzzySoft** [comment]
Thanks, that would help! As I'd have to tell my updater which APK to pick: if the "simplified" is missing from a release, that version will be missing from my repo. Should be fine if it happens in one out of 10 cases (or like that – i.e. not the other way around :wink:) – maybe one day you can automate that as well.

Could you please mention here when the first release with such a simplified APK is available, so I correct the config here?

**Comment by Waboodoo** [comment]
Yes, I will mention it here. I currently don't want to create a release for 1.27.2, because I am still investigating 2 bugs that I would like to have fixed.

**Comment by Waboodoo** [comment]
I created a new release for version 1.28.0 and uploaded APKs for different architectures
https://github.com/Waboodoo/HTTP-Shortcuts/releases/tag/v1.28.0

**Comment by IzzySoft** [comment]
Thanks a lot, @Waboodoo! I modified the metadata in my repo to match `/armeabi/i` on the file name, and the updater picked the correct file. So now it's well within the limits again which @TPS mentioned, great! Please keep the file naming pattern (or drop me a note if you need to change that).
