### ISSUE TITLE
Input Type QR Code

### ISSUE THREAD

**Issue by thejeshgn** [Waboodoo/HTTP-Shortcuts#151]
An input or variable type QR code will be very useful. When the app encounters the variable it can open the camera to scan the qr code, once the scan is complete the value of the scan be assigned to the variable, which can be used in a request.

**Comment by sebastiannielsen** [comment]
I think the best way to handle this is to have a QR or scanner app that has a built-in share feature, and use that to send the request. Some share dialogs allows you to "remember" the selection of where to share, and then its to send the request just by pushing a button.

**Comment by Waboodoo** [comment]
While I see the potential usecases for such a variable type, I'm a bit reluctant to add it as it would mean that the app needs to hold the CAMERA permission, which I'd rather avoid as it can be a privacy concern to some users. It might be possible to invoke a 3rd party QR scanner app here to get around that issue, but I have not investigated that yet.

An alternative to this would be to generate QR code which, when scanned, can trigger a specific shortcut, potentially with specific values assigned to its variables. For example, if you have a shortcut with ID *2dddb06f-9b46-49fd-8378-ab1a5ac195cf*, which uses the variable *my_var*, then you could create a QR code which points to that shortcut and triggers it, with *my_var* initialized to 42, by using this URL: *http-shortcuts://deep-link/2dddb06f-9b46-49fd-8378-ab1a5ac195cf?my_var=42*

**Comment by Waboodoo** [comment]
In version 2.18.0 there will be a way to integrate with the QR Droid app, allowing to scan barcodes and using their contents in Scripting (from where it can be stored into variables and used in HTTP requests). I will post a link to the documentation here once it is released.

**Comment by thejeshgn** [comment]
Binary Eye would be a great qr code app to integrate. Its FOSS as well.

**Comment by Waboodoo** [comment]
@thejeshgn Cool, I didn't know about this app. I added support for it as well now.

**Comment by sebastiannielsen** [comment]
You could also integrate the default zxing app:_

https://play.google.com/store/apps/details?id=com.google.zxing.client.android

**Comment by Waboodoo** [comment]
@sebastiannielsen I tried that at first but it didn't work so well, but I gave it another try now and apart from the warning that this app is outdated it works 👍🏻

**Comment by Waboodoo** [comment]
Closing this issue as there is now support in version 2.18.0, which is being released now.
Documentation can be found here: https://http-shortcuts.rmy.ch/scripting#scan-barcode
