### ISSUE TITLE
shortcuts from homescreen doesn't work anymore

### ISSUE THREAD

**Issue by DuschdrBabbe** [Waboodoo/HTTP-Shortcuts#155]
Hello,
i am using shortcuts for a wile now, everything has worked fine... but since a wile the shortcuts on my homescreen or novalauncher sidebar didnt work anymore. from the app himself the shortcuts works fine. i have read in the faq that is a problem from battery saving or datasaving, i have exclude shortcuts from powersaving but this setting is not working...

has somebody also this problems??

greetings...

**Comment by Waboodoo** [comment]
Can you explain in more detail what exactly doesn't work? When you click them on your home screen, does anything happen at all?

What "Response Type" did you set for the shortcuts? As a workaround, it might help to change the response type to "Response in Dialog" or "Response in Window", or alternatively, setting a "Run on Success" script in the Post-Request Actions screen, e.g. just put a single semicolon ";" there.
