### ISSUE TITLE
Custom Responses

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#156]
Kindly help, I have two keyword in my response (plain text)
one start with word START and another with END, I want to display my response in dialog if it start with START and display it with Response in Toast if it start with END
Regards

**Comment by Waboodoo** [comment]
What have you tried so far? This should be easily possible using the `showToast` and `showDialog` action when used as a post-action. Have a look here for instructions on how to use these actions: http://waboodoo.ch/http-shortcuts/scripting

The rest is simple Javascript string processing, which you can learn more about on the internet, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by stevenjohnk** [comment]
Thank you for your help, I checked , now I am asking how I can use javascript to open a Text input variable after clicking OK on dialog response (not using using trigger another shortcut).
Thanks in advance

**Comment by Waboodoo** [comment]
The JavaScript execution can currently only be used to compute values and to invoke the built-in actions (e.g. show toast, vibrate, trigger another shortcut). There is currently no way for the JS execution to do other UI interaction, such as opening a text input prompt. I'll be looking into making this possible eventually, but currently it's not supported.

**Comment by stevenjohnk** [comment]
Thanks and God bless u for this, regards
