### ISSUE TITLE
update request-body after pre-request-action

### ISSUE THREAD

**Issue by wumboka** [Waboodoo/HTTP-Shortcuts#158]
Hi!

I have a problem with variables.
The idea is to set the value of a variable from a "select" list (pre-request action) and that value will be sent in the "request body".

I created variables:
"devices"
type: list
item1: name: dev1, value: 5
item2: name: dev2, value: 6

"selected_id"
type: constant
value: 0

I made a shortcut, its parameters:
Name: ON
Request body: custom text - text/plain
Textarea value: {"id": "{selected_id}"}
Pre-request actions:
setVariable ("selected_id", getVariable ("devices"));

When I run, the list comes up (pre-request action), I select the device, but at run the "selected_id" value does not change in the sent data, because the "request body" value is already set and no longer exists updated.

note: I tried this form, but the same result:
var d = getVariable ("devices");
setVariable ("selected_id", d);
var test = getVariable ("devices");
showToast (body);

The popup shows the correct value, but the "request body" value is not updated.

I don't know if this is definitely a bug, but is there a way to update "request body" AFTER "pre request action"? Because a value in "pre-request-action" may change.
If you want, I'll share the .json file if it can help.

**Comment by Waboodoo** [comment]
There is a bug in version 1.24.0 which causes variable changes made in the "Pre-Request" block to not be reflected in the current execution. This is most likely what's causing the problem you're describing. This bug should be fixed in 1.25.0, which will be released soon. Once it's available please update and let me know if you still encounter this problem. Thank you.

**Comment by wumboka** [comment]
Yes, I think that's the bug :)
Thank you very much for your quick and informal response!

**Comment by wumboka** [comment]
Wow! That was a very fast update!
My problem is gone. The response-body is updated after the pre-request-action event.
Thank you!
