### ISSUE TITLE
Question: Returncode an Actions

### ISSUE THREAD

**Issue by lblabr** [Waboodoo/HTTP-Shortcuts#160]
Hi i'm very new to HTTP-Shortcuts and in like it very much. My requests to an RESTAPI return some values:

1) i would like to see the return values (like Temperature in the shortcut-list 
2) could color change according return value (like button etc...)

is that possible, might that be possible ?

Thanks in advance

Lars

**Comment by lblabr** [comment]
solved to 80%, found javascript methods to change the shortcut.name. Do you think, its possible to change color and symbol by javascript ?

thanks in advance Lars

**Comment by Waboodoo** [comment]
Currently there is no way to programmatically change the shortcut's icon. I'm planning to eventually add a way to do this, but I can't make any promises.
