### ISSUE TITLE
URL validation does not check variables

### ISSUE THREAD

**Issue by sebastianha** [Waboodoo/HTTP-Shortcuts#161]
I tried to set my base URL (something like "http://server.com/") as a variable but when using this variable in a shortcut I cannot save it because the URL validation fails. I have to begin the URL with "http://{shortcut}", that works.

I am using version 1.25.0 and also added a comment to https://github.com/Waboodoo/HTTP-Shortcuts/issues/70 but as this is already closed I opened this ticket here.

Would be nice if you could solve this problem. Thank you very much for this great App!

**Comment by tobyink** [comment]
I've got a constant called "LAPTOP" set to "192.168.0.11" then a shortcut set to:

```
POST http://{LAPTOP}/api/sound/mute
```

And it works nicely. From your description of what you're doing, you seem to have the "http://" in both the variable and the URL.

**Comment by sebastianha** [comment]
This is not what I tried.
I want a variable "http://192.168.0.11" and set the URL to "{VARIABLE}/api/sound/mute". This does not work, at least for me.

**Comment by Waboodoo** [comment]
Thanks for reporting this, I can confirm this is a bug, I can reproduce it. I will fix it for the next version.

**Comment by Waboodoo** [comment]
This is fixed in version 1.27.0, which I'm planning to release in the coming days.
