### ISSUE TITLE
feat. req. : widgets without labels

### ISSUE THREAD

**Issue by lapsus63** [Waboodoo/HTTP-Shortcuts#163]
I use your app for kodi shortcuts. Custom icons are very relevant and widgets don't need to show label under them. Ex: I'd like to have a play/pause button without the text play pause under it.
Very nice app, congratulations !

**Comment by Waboodoo** [comment]
The app currently doesn't provide a widget, it only provides shortcuts (which are basically a special type of widgets on Android). With shortcuts, there's only very limited control over what they can do. They're basically just an icon and a label. As such, I can't remove the label. I currently have no plans of adding widget support.

For your use case, I recommend to install [Elixir Widgets](https://play.google.com/store/apps/details?id=com.bartat.android.elixir.widget&hl=en) (or a similar app) and combine it with HTTP Shortcuts. This way you can create custom widgets that can trigger other apps, e.g. to trigger a shortcut.

Hope this helps.
