### ISSUE TITLE
feature request: add security logon to execution of a shortcut

### ISSUE THREAD

**Issue by Nijn02** [Waboodoo/HTTP-Shortcuts#164]
Enable security (like Android’s Biometric API) on execution of a shortcut. 
Function to be set on shortcut level so it can be activated per shortcut. 
If not possible per shortcut, make it general on executionof the tool. 

Some examples of implementation:
https://www.androidauthority.com/add-fingerprint-authentication-app-biometricprompt-943784/
https://www.androidauthority.com/how-to-add-fingerprint-authentication-to-your-android-app-747304/

**Comment by latdev** [comment]
I  think it's possible to do using  scripting + Intent, just check this.

https://stackoverflow.com/questions/39526631/intent-to-launch-fingerprint-enrollment-screen

**Comment by Waboodoo** [comment]
As of version 3.2.0, a shortcut can be configured to require biometric authentication before running. The option can be found in the "Trigger & Execution Settings" section of the shortcut editor.
