### ISSUE TITLE
Support for bearer token authentication?

### ISSUE THREAD

**Issue by ebaschiera** [Waboodoo/HTTP-Shortcuts#168]
Hi,
I took a look, but could find a way to use bearer token authentication...
Should this issue be a feature request? :)

Thanks!

**Comment by EugenGez** [comment]
Hi

do you already have the token? Why not to use it as a variable in request headers?

BR

**Comment by Waboodoo** [comment]
If you already have the token then you can simply add a custom 'Authorization' header with it.

**Comment by ebaschiera** [comment]
Thanks, I didn't realize that was so simple. I just added an 'Authorization' header with value 

`Bearer xxxxxxx`

and it worked. Thanks!
