### ISSUE TITLE
Request content body parameters not working

### ISSUE THREAD

**Issue by danimaciasperea** [Waboodoo/HTTP-Shortcuts#169]
Since last release (1.27.0) the parameters in request body are not being correctly sent (request content type x-www-form-urlencoded). Previous version works successfully. The function Export cURL also shows parameter encoding (even when no encoding option is selected).

The same shortcut tested with previous release (1.26.1) works perfectly fine.

**Comment by Waboodoo** [comment]
Thanks for reporting. I will look into it tonight or tomorrow.

**Comment by Waboodoo** [comment]
> Since last release (1.27.0) the parameters in request body are not being correctly sent (request content type x-www-form-urlencoded).

This is now fixed in 1.27.1, which I will release to the Play Store tomorrow after some more testing.

> The function Export cURL also shows parameter encoding (even when no encoding option is selected).

This I don't quite understand what you mean. Can you elaborate?
