### ISSUE TITLE
Can`t install update on android tv

### ISSUE THREAD

**Issue by ycodryn** [Waboodoo/HTTP-Shortcuts#171]
I`m trying to update v1.26.1 to v1.27.2 on my sony tv but is failing. Support for armeabi-v7a is ended?

**Comment by ThinkTwiceCodeOnce-prog** [comment]
@ycodryn Do you have a solution?
I am facing the same issue, when updating on my Samsung Galaxy S5. I also assume it is a something hardware related problem.

**Comment by Waboodoo** [comment]
Support for armeabi-v7a should still be there, I made no changes on that front.

**Comment by ThinkTwiceCodeOnce-prog** [comment]
Finally, with your new v1.28.0 installation (with armeabi-v7a apk) works fine again.
Thank you for your help.

**Comment by Waboodoo** [comment]
Glad to hear :+1:

**Comment by ycodryn** [comment]
> @ycodryn Do you have a solution?
> I am facing the same issue, when updating on my Samsung Galaxy S5. I also assume it is a hardware related problem.

I used sai but with latest version v7a as you saw is available separately. Thanks.
