### ISSUE TITLE
Update to 1.27.2 broke something to shortcuts

### ISSUE THREAD

**Issue by ycodryn** [Waboodoo/HTTP-Shortcuts#172]
Updating v1.26.1 to v1.27.2 on my sony tv (android 7.0, armv7-a) broke shortcuts. Launching them nothing happens. Here is an example of a shortcut:

        {
          "acceptAllCertificates": false,
          "authentication": "none",
          "bodyContent": "\u003c?xml version\u003d\"1.0\"?\u003e\u003cs:Envelope xmlns:s\u003d\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle\u003d\"http://schemas.xmlsoap.org/soap/encoding/\"\u003e\u003cs:Body\u003e\u003cu:X_SendIRCC xmlns:u\u003d\"urn:schemas-sony-com:service:IRCC:1\"\u003e\u003cIRCCCode\u003e AAAAAQAAAAEAAAA+Aw\u003d\u003d\u003c/IRCCCode\u003e\u003c/u:X_SendIRCC\u003e\u003c/s:Body\u003e\u003c/s:Envelope\u003e",
          "codeOnFailure": "",
          "codeOnPrepare": "",
          "codeOnSuccess": "",
          "contentType": "text/plain",
          "delay": 0,
          "description": "",
          "executionType": "app",
          "feedback": "none",
          "followRedirects": true,
          "headers": [
            {
              "id": "07e2d4fb-776e-4428-bc44-66fa78f67db9",
              "key": "Content-Type",
              "value": "text/xml: charset\u003dUTF-8"
            },
            {
              "id": "72ea4610-25a6-4720-8dd7-093632a5d660",
              "key": "SOAPACTION",
              "value": "\"urn:schemas-sony-com:service:IRCC:1#X_SendIRCC\""
            },
            {
              "id": "7fa9886a-ddb3-475b-a986-0e2f2fa983e2",
              "key": "X-Auth-PSK",
              "value": "0000"
            }
          ],
          "iconName": "flat_color_lightbulb",
          "id": "74d184a3-f87d-4b06-9c6d-5dcbeb6d55b0",
          "launcherShortcut": false,
          "method": "POST",
          "name": "Screen off",
          "parameters": [],
          "password": "",
          "requestBodyType": "custom_text",
          "requireConfirmation": false,
          "retryPolicy": "none",
          "timeout": 10000,
          "url": "http://192.168.2.6/sony/IRCC",
          "username": ""
        },

**Comment by Waboodoo** [comment]
Does this also happen when you trigger the shortcuts from within the app? Or is it only from the home screen?

**Comment by ycodryn** [comment]
Even inside app when clicking on shortcut (with setting to execute shortcut on click)

**Comment by Waboodoo** [comment]
I see you have this shortcut set up to run silently ("feedback": "none"). This would mean that also errors are ignored and not shown. Can you try changing the shortcut's Response Type to "Response in Window" and see if it gives you any meaningful error back from the server?

**Comment by ycodryn** [comment]
Sure, i will reinstall tonight and check.

**Comment by Waboodoo** [comment]
You can also enroll in the beta tester program on the Play Store and install version 1.28.0, which might fix your issue.

**Comment by ycodryn** [comment]
Sorry for the delay but for last days me, my wife and my kid had some health issues and with this virus we were a little worried.  Here is the log: Screen off failed: Parameter is not formatted correctly: ":charset=UTF-8" for: "text/xml: charset=UTF-8"

**Comment by Waboodoo** [comment]
This bug might be fixed now with version 1.28.0
You can download the APK here: https://github.com/Waboodoo/HTTP-Shortcuts/releases/tag/v1.28.0

**Comment by Waboodoo** [comment]
Also, try changing that colon into a semi-colon, i.e. "text/xml; charset=UTF-8"

**Comment by ycodryn** [comment]
By default, v1.28.0 did not resolve the issue but changing ":" to ";" did the trick. Thank you.
