### ISSUE TITLE
Adding new shortcut won't add launcher shortcut menu

### ISSUE THREAD

**Issue by auspic7** [Waboodoo/HTTP-Shortcuts#173]
Android 10, Galaxy S10 5G.

launcher shortcut menu(the menu which appears when you longpress the app icon) will be updated only when I completely restart the app. It would be better if it is updated immediately when you add a new shortcut.

**Comment by Waboodoo** [comment]
Thanks for the bug report. I will improve this for the next version of the app (1.28.0), so that the launcher shortcuts are also updated whenever a shortcut is created or edited.

**Comment by auspic7** [comment]
Thank you for your fast feedback.

**Comment by Waboodoo** [comment]
This should now be fixed in version 1.28.0.
