### ISSUE TITLE
Enhanced Import/Export Functionality

### ISSUE THREAD

**Issue by jmccrohan** [Waboodoo/HTTP-Shortcuts#177]
Hi,

Thanks for developing HTTP-Shortcuts, it is a really useful app.

Have you considered enhancing the current Import/Export functionality to allow users to select which Shortcuts to export?

I find myself having to share Shortcuts that I have created with others.

I order to do this, I need to either:

-  send on details for them to create it themselves manually
     -  only an option for trivial Shortcuts
     - not a viable option if the Shortcut uses using response scripting
- else export my full settings to JSON, manually trim the other entries from the JSON, and share the settings file with them

It would be fantastic if I could create a _package_ of Shortcuts to share with others. Bonus marks if you could create an Android Intent so that the _package_ it opens automatically with HTTP-Shortcuts.

Thanks,
Jon

**Comment by Waboodoo** [comment]
Cool idea, I have so far only briefly considered this.

How would you imaging this? Do you think it would be enough to add an option to export a single shortcut (similar to the cURL export right now), or would you want to export multiple (but not all) shortcuts at once? Would those shortcuts be all in the same category? Would it be a viable solution to have the option to export a category (with all shortcuts in it)?

One tricky thing I see here is that if a shortcut is exported, the export would also need to contain all variables that are used by this shortcut. Would this work for your use-case?

**Comment by jmccrohan** [comment]
Hi,

I think exporting multiple shortcuts would be really useful. I hadn't considered the variable aspect originally, but agree that exporting all referenced variables would make sense.

Regards,
Jon

**Comment by Waboodoo** [comment]
As of version 1.35.0 it is possible to export individual shortcuts via the long press context menu. When exporting this way, the app will try to detect which variables also need to be exported.

There's no feature though to export multiple shortcuts though.

**Comment by jmccrohan** [comment]
> As of version 1.35.0 it is possible to export individual shortcuts via the long press context menu. When exporting this way, the app will try to detect which variables also need to be exported.

Thanks for this. This is really useful. Really appreciate you taking the time to implement.

**Comment by Waboodoo** [comment]
So, it's been a while, but I'm finally getting back around to this: In version 2.19.0, I'm extending the export feature so that it will be possible to select which shortcuts should be included in the export.

**Comment by Waboodoo** [comment]
As of version 2.19.0 (which is being released now) it is possible to select which shortcuts to export. In 2.20.0 I will further improve this by making sure that the export file only contains the variables, custom icons and client certificate files that are really needed.
