### ISSUE TITLE
Feature: Execute group of shortcuts

### ISSUE THREAD

**Issue by skrabadiloseidon** [Waboodoo/HTTP-Shortcuts#178]
Can you implement a feature to group multipe shortcuts AND to execute them together (maybe option to define with which parameters).

I use the app to control smart home devices over node red http calls, but currently i need to manually  tap multiple shortcuts to poweron tv, lights, etc.
If i could define one group e.g. "TV" that executes multiple shortcuts, were very useful.

**Comment by jeedomsteph37** [comment]
You can use function `triggerShortcut`... (see https://http-shortcuts.rmy.ch/scripting)

**Comment by Waboodoo** [comment]
I will think about it. So far I don't know what would be a good way of including such an option.

However, you could already achieve something like this with the current version of the app, by having one shortcut trigger one or more of the other shortcuts, using the `triggerShortcut` action, as @jeedomsteph37 already pointed out.

**Comment by skrabadiloseidon** [comment]
I solved my problem by passing an array with multiple actions to node red.
