### ISSUE TITLE
Publishing on F-Droid

### ISSUE THREAD

**Issue by DocSniper** [Waboodoo/HTTP-Shortcuts#180]
Thanks for the great app, I love to use it.

Please consider publishing your app on [F-Droid](https://f-droid.org/)

Submission link: https://gitlab.com/fdroid/rfp/

**Comment by Waboodoo** [comment]
I will try. I have not used F-Droid before today, and I must say the process of submitting an app isn't exactly straightforward.

From what I see the main change I have to make to the app is to exclude the crash logging framework. I will set up a special build type for this.

**Comment by DocSniper** [comment]
Thank you for all of your efforts.

Just for information, I am currently using your app to control a dozen ESP8266 with [Tasmota](https://tasmota.github.io/docs/) firmware and everything works great.

**Comment by Waboodoo** [comment]
I have opened a request for packaging on F-Droid: https://gitlab.com/fdroid/rfp/-/issues/1369

**Comment by DocSniper** [comment]
Great and thanks, then I close the issue.

**Comment by Waboodoo** [comment]
The app is now published on F-Droid: https://f-droid.org/en/packages/ch.rmy.android.http_shortcuts/

**Comment by IzzySoft** [comment]
@Waboodoo I forgot to make a note: shall I remove your app from my repo then? Makes not much sense to have the same version in both places, only differing by signature.

**Comment by Waboodoo** [comment]
@IzzySoft Feel free to remove it :+1:

**Comment by IzzySoft** [comment]
Thanks – done (effective with the next sync tomorrow). Should you need it back for some reason (like, test builds), just yell. Metadata are still there.
