### ISSUE TITLE
[BUG] response-object is null if before-request script is defined

### ISSUE THREAD

**Issue by klausj1** [Waboodoo/HTTP-Shortcuts#183]
**Steps To Reproduce**
1. Define a shortcut
2. In scripting, in "execute before request (JavaScript)" (german: "Vor Request ausführen (JavaScript)"), add a setVariable-statement 
3. In scripting, in "success", add a script accessing response.body
4. On execution, an error message is shown, because response is null
5. Remove the script in "execute before request (JavaScript)"
6. Now everything works fine

**Context**
 - Android OS Version: 10
 - App Version: 1.32.1
 - The problem occured in the last days/weeks, probably because of an upgrade. Unfortunately I do not know which version I had before

**Comment by Waboodoo** [comment]
Thanks for reporting this. I have identified the issue and will fix it for the next release :+1:

**Comment by Waboodoo** [comment]
This is now fixed (version 1.33.0) and released.
