### ISSUE TITLE
Feature request: more granular execution delay

### ISSUE THREAD

**Issue by 42wim** [Waboodoo/HTTP-Shortcuts#187]
At the moment the smallest execution possible delay is 500ms. (or 0ms)

It would be nice if this would be more granular, like 100ms.
Or even better if we could manually fill in the value in ms

Thanks for your work btw!

**Comment by Waboodoo** [comment]
I'm not sure how much sense it would make to go for execution delays below 500ms. On many devices, the overhead needed to trigger a shortcut is within that order of magnitude, so even if the delay were set to 100ms it might still take signficiantly longer than that for the HTTP request to fire. I'll do some experimentation and see if I can improve the performance around this somehow, but I can't make any promises as some limitations of the Android platform apply.

**Comment by Waboodoo** [comment]
Doing some cleanup here. I think my original reasoning here still stands, and the request has no come up again in 4 years, so I'm closing this issue now.
