### ISSUE TITLE
[FIX|IMPROVEMENT] Working arrowkeys...

### ISSUE THREAD

**Issue by HendrikPoppe** [Waboodoo/HTTP-Shortcuts#188]
**Is your feature request related to a problem? Please describe.**
The arrowkeys are working only for single line inputfields. But at the scripting section they change the focus of selected element.

**Describe the solution you'd like**
Use tabulator as focus selector/changer.
Arrowkeys for up down ...

**Describe alternatives you've considered**
there is none.
Its the normal behavior in almost each app/prog i can think of.
And would also improve the accessilitiby for disabled persons.

p.s: Nice app idea, usage and build.

**Comment by Waboodoo** [comment]
Thanks for reporting this. I have identified the issue and fixed it for the next release (1.34.0)

**Comment by Waboodoo** [comment]
This should be fixed now in version 1.34.0.
