### ISSUE TITLE
Request: Submit to F-Droid

### ISSUE THREAD

**Issue by acornsirup** [Waboodoo/HTTP-Shortcuts#189]
Awesome app!
It'll be even better if people don't have to rely on Google Play or the direct download here on GitHub to get it.

How about submitting the code to F-Droid?
https://f-droid.org/en/docs/Inclusion_How-To/

Thanks and all the best.

**Comment by Waboodoo** [comment]
I've already submitted it, but the request hasn't moved much since. See https://github.com/Waboodoo/HTTP-Shortcuts/issues/180

**Comment by acornsirup** [comment]
Ah, didn't catch that. Many thanks!

**Comment by Waboodoo** [comment]
The app is now published on F-Droid: https://f-droid.org/en/packages/ch.rmy.android.http_shortcuts/
