### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Potatof** [Waboodoo/HTTP-Shortcuts#190]
Hi, 
After last update (1.34?),
When i use an already created shortcut (any) the command is well sent but i got a message "...failed to connect...." in loop , i've to reboot my phone to recover a normal stat.

**Comment by Waboodoo** [comment]
Does this only happen when you trigger shortcuts from the home screen, or also when you trigger them from within the app?

You can try enabling the "Run Requests in Foreground" option which you'll find on the Settings page. Maybe that helps.

**Comment by Potatof** [comment]
Well Seen!
Only from home screen, in app it Work as usual... I have deleted all shortcuts and recreate and... Now everything is fine.
Thx very mutch!

**Comment by Waboodoo** [comment]
Glad to hear it works now :+1:
