### ISSUE TITLE
Feature: schedule a request

### ISSUE THREAD

**Issue by Dewey12** [Waboodoo/HTTP-Shortcuts#192]
Hello,

For strating, very good application, good job.

But why not include a planner for shortcut.
Example, I want send a "post request " everyday at 8AM.

**Comment by Waboodoo** [comment]
This request has come up multiple times so far. However, adding the capability to schedule requests would push my app even further into the domain of a automation apps. There are already quite a number of automation apps out there (e.g. Tasker, E-Robot, IFTTT, Macrodroid, to name a few), and I don't want to build another one. Instead, I recommend to make use of those existing apps and combine them with my app. Most if not all of those apps give you the option to trigger another app, so you should be able to have e.g. Tasker trigger an HTTP Shortcut.
As such, I'm currently not considering adding this feature to my app.
