### ISSUE TITLE
Add Fastlane dir

### ISSUE THREAD

**Issue by 6543** [Waboodoo/HTTP-Shortcuts#193]
**Is your feature request related to a problem? Please describe.**
It will bring screenshot preview to F-Droid (when F-Droid incluseion is done)

**Describe the solution you'd like**
just add structure as described here https://gitlab.com/snippets/1895688

**Comment by Waboodoo** [comment]
According to https://gitlab.com/snippets/1895688, F-Droid also supports the Triple-T structure, which is already present: https://github.com/Waboodoo/HTTP-Shortcuts/tree/develop/HTTPShortcuts/app/src/main/play

**Comment by Waboodoo** [comment]
Since F-Droid for some reason failed to pick up the Triple-T files I've switched over to the Fastlane file structure: https://github.com/Waboodoo/HTTP-Shortcuts/tree/develop/metadata

**Comment by IzzySoft** [comment]
For where F-Droid picks metadata from, see e.g. [my Fastlane cheat-sheet](https://gitlab.com/snippets/1895688) and the [corresponding F-Droid documentation](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots). Fastlane should be in `fastlane/metadata/android/<locale>`, for example :wink:
