### ISSUE TITLE
When set header request User-Agent still displaying the default one[BUG]

### ISSUE THREAD

**Issue by WuvorWenda** [Waboodoo/HTTP-Shortcuts#195]
**Steps To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Context (please complete the following information):**
 - Android OS Version: [e.g. 9.0]
 - App Version [e.g. 1.32.0]
 - Any other context about the problem that you think is relevant

OS Android 10
Set request header User-Agent to test
In web server still the default one: "HttpShortcuts/1.36.0 (Linux; U; Android 10; ...."

**Comment by Waboodoo** [comment]
Thanks for reporting this bug. This will be fixed in the next release (version 1.37.0).

**Comment by WuvorWenda** [comment]
Thanks! Great app btw

**Comment by Waboodoo** [comment]
Version 1.37.0 is now released

**Comment by WuvorWenda** [comment]
Its oke now, User-Agent works perfect.
Thanks.
