### ISSUE TITLE
[BUG] Sharing with attached file doesn't work

### ISSUE THREAD

**Issue by sebastiannielsen** [Waboodoo/HTTP-Shortcuts#198]
**Steps To Reproduce**
Share a item which contains BOTH an text and attached image.
This can be tested both with a variable input or file input.

**Expected behavior**
Both file input and text should be populated.

**Actual behavior**
file (attached picture) is ignored. If you have a file input, it will ask you to select a file on-device.

To check that a picture is actually shared try sharing to a email program. If the composed email has both text and a attached picture, now try sharing this into HTTP shortcuts. The picture will be ignored, despite having a file input.

**Context (please complete the following information):**
 - 10
 - 1.37.0

**Comment by Waboodoo** [comment]
Interesting. That's a use case I hadn't even considered. Currently the app is designed to support sharing only one thing at a time: either text or a file.

I will look into this and see if I can enable support for sharing text and files at the same time.

**Comment by Waboodoo** [comment]
@sebastiannielsen What app did you use to share the image and text from?

**Comment by sebastiannielsen** [comment]
This:
https://play.google.com/store/apps/details?id=nl.innovalor.nfciddocshowcase

make sure to check "share of personal details" in settings.

then scan a passport/idcard, select share.

try with email software, you will see text AND pic is shared.

**Comment by Waboodoo** [comment]
This should now be fixed with the 1.38.0 release. Please let me know if there's still a problem.
