### ISSUE TITLE
Feature Request:UDP Packet Shortcuts

### ISSUE THREAD

**Issue by emerysteele** [Waboodoo/HTTP-Shortcuts#199]
Would be awesome if you could add functionality to send UDP packets via a shortcut.

I wrote my own smart home controller in Python and it uses UDP packets to receive data from my desktop & laptop computers.

Having UDP packet sending built in to this app would save me from having to build a separate webserver that translates http requests to UDP. Others may find useful as well.

Currently there is an android app that I use called 'UDP sender'. But it doesn't have the ability to make shortcuts. I have to type the command I want to send manually every time.

**Comment by Waboodoo** [comment]
In version 2.19.0, I'm including a `sendUDPPacket` function which will enable this usecase through the Scripting feature.

**Comment by emerysteele** [comment]
🙌

Awesome!! Currently using a local web server and php to interpret get requests and send the udp packets. But this would make it so much easier :D

**Comment by Waboodoo** [comment]
Version 2.19.0 is now being released. The documentation for the newly added `sendUDPPacket` function can be found here: https://http-shortcuts.rmy.ch/scripting#send-udp-packet
