### ISSUE TITLE
Add possible to include sending package in the request

### ISSUE THREAD

**Issue by sebastiannielsen** [Waboodoo/HTTP-Shortcuts#200]
**Is your feature request related to a problem? Please describe.**
A possible to include the package name from sending app.
So for example, sharing from AppX to HTTP-Shortcuts, should give a way to include AppX's package name.

**Describe the solution you'd like**
Best would be a additional checkbox in the static variable dialog, like "Allow sharing..." but instead "Set this variable to sending package name"

So you could define static variable pkgname, then check box "Set this variable to sending package name". Then use it as formfield or url argument.

Usage:
It can be good to in backend application, be able to differentiate between sharing from different apps.

**Comment by Waboodoo** [comment]
This goes a bit against the idea of Android's Sharing framework. An intent to share data into an app can come from an arbitrary source (app), and the receiver should not need to know where the data that is being share comes from, which means that in many cases this information is not available or at least not reliably. There are some hacks to get the package name of the sharing name but there is no guarantee that they work or that the obtained information is correct. As such I don't think it's a good idea to introduce this kind of coupling.

**Comment by sebastiannielsen** [comment]
Aaah, I tought there was a "legal" way to access the caller of a share intent, so an receiver app could react differently if a piece of data where shared from for example the contact book or SMS messages - so for example, the receiving app could parse and format the data as a VCF file in the case of contact book.

**Comment by sebastiannielsen** [comment]
Ill file this on the android issue tracker instead so they could extend the share framework.

**Comment by sebastiannielsen** [comment]
Reopening this as I got back from the android engiinering team:

https://issuetracker.google.com/issues/178904644

**Comment by Waboodoo** [comment]
`Activity.getCallingPackage` will return the package name of the app that invoke it, but only if it expects a result back, i.e., only if it used `Activity.startActivityForResult`.

See https://developer.android.com/reference/android/app/Activity#getCallingPackage()

> Note: if the calling activity is not expecting a result (that is it did not use the startActivityForResult(Intent, int) form that includes a request code), then the calling package will be null.

I tested this by sharing a URL from Chrome into the app and verified that the result of `Activity.getCallingPackage` was indeed `null`.

Using the 'Share' feature on Android is a one-way operation, it does not expect back a result from the target application, and therefore it also doesn't present the target application with reliable information about the origin of the shared data, so as I understand, this still won't solve your original issue here.

**Comment by sebastiannielsen** [comment]
Strange.
I tought share was a two-way operation that it would return if the sharing was successful or not.

Ill rely back to the engiiner and see if he have a better solution.

**Comment by Waboodoo** [comment]
Closing this issue now as there is no complete and correct way to achieve this, as also indicated by the linked issue which was closed as "Won't Fix".
