### ISSUE TITLE
Inbuilt Icon Size

### ISSUE THREAD

**Issue by Badger101** [Waboodoo/HTTP-Shortcuts#201]
Hello,

I haven't needed to setup this app for a long time as it worked perfectly for me. However I have just tried to setup another shortcut today and the sizes of the inbuilt icons are a lot bigger on my home screen than the older ones.
Have the icons changed in size? Or have I missed a setting somewhere?
If they have changed in size, is there somewhere I can get hold of the older ones?

Thanks!

**Comment by Badger101** [comment]
Sorry, I've just figured it out :)

**Comment by Waboodoo** [comment]
Glad to hear you figured it out. Basically, there are 2 types of widgets offered by the app: the regular shortcut widget, which is the default one, and the customizable widget, which can be resized.
