### ISSUE TITLE
API Data on widget

### ISSUE THREAD

**Issue by bermaneyal** [Waboodoo/HTTP-Shortcuts#202]
Can I show the api data response on the widget himself? and that the widget will update himself on every minute?
now i need to press the widget for him to fetch the data and show it on the screen.

**Comment by Waboodoo** [comment]
You can use the app's Scripting capabilities to add custom logic to the execution of a shortcut. With this you could for example have the shortcut dynamically rename itself based on what the response was.

See https://http-shortcuts.rmy.ch/scripting#examples for documentation on how Scripting works and to see an example of how this can be set up.

There is currently no direct way to update a shortcut periodically or based on a schedule. The next best thing you could do is to set set a delay of 1 minute (find it in the shortcut's "Misc Settings") and then use Scripting again to have the shortcut trigger itself again after execution. This might not work well though, but you could give it a try.
