### ISSUE TITLE
Feature Request:Add Base64 encoding and decoding support

### ISSUE THREAD

**Issue by xiozf** [Waboodoo/HTTP-Shortcuts#205]
Thank you for developing such an easy-to-use app.I use it every day. Recently, I encountered a problem.

A JSON response is as follows:
{"type": "text","data": "message"}  or
{"type": "media","name": "pic2020.png","data": "Base64 encoded"} or
{"type": "file","name":"help.pdf","data": "Base64 encoded"}.

I want to get the "data" value from it and decode it.Can you add base64 encoding and decoding support?

You may also need to remove the size limit of the response body and add the file save function.

**Comment by Waboodoo** [comment]
Hello, and thanks for the feature request. Base64 encoding and decoding is something I'd like to add to the app at some point, but in order for it to be useful I'll need to first make quite a few bigger changes to how requests are handled. Removing the size limit is currently not possible, as the response is loaded into memory and would just make the app crash if it gets too large. I'll see what I can do, but it will take a while and I can't give any timeline for this at this point.

**Comment by wielandp** [comment]
I need base64 too.  Size is not my problem.

**Comment by Waboodoo** [comment]
@wielandp Can you perhaps elaborate on what you'd need base64 decoding for?
Base64 is typically used to encode binary data, so if you decode it you'd end up with a byte array, and I'm not sure what you'd do with that, as there is no way to store it into a file or anything.

**Comment by wielandp** [comment]
I'm from Germany and have a smart meter for electricity. To get the data I have a poweropti from https://www.powerfox.energy/
There is a jsonrpc api (not documented) which I can use on my PC and would like to use with my phone.
POSTing this: Content-Type: application/json
{"id":1,"jsonrpc":"2.0","method":"getConfig","params":{"key":"latest_data"}}
I get back:
{"jsonrpc":"2.0","id":1,"result":"W3siZmMiOjAsImMiOjEsInQiOjE2MTQwNzk0MzIsIm0iOiIxRUJaMDEwMHh4eHh4eCIsImRpdiI6MCwiZCI6W3sibyI6IjAxMDAwMTA4MDBmZiIsInYiOiI5OTgyMTYifSx7Im8iOiIwMTAwMDEwODAxZmYiLCJ2IjoiMCJ9LHsibyI6IjAxMDAwMTA4MDJmZiIsInYiOiIwIn0seyJvIjoiMDEwMDAyMDgwMGZmIiwidiI6IjExNTUifV19LHsiZmMiOjAsImMiOjIsInQiOjE2MTQwNzk0MzIsImQiOlt7Im8iOiIwMTAwMTAwNzAwZmYiLCJ2IjoiNTkxIn1dfV0="}

Base64 decoding the result gives again json:
[{"fc":0,"c":1,"t":1614079432,"m":"1EBZ0100xxxxxx","div":0,"d":[{"o":"0100010800ff","v":"998216"},{"o":"0100010801ff","v":"0"},{"o":"0100010802ff","v":"0"},{"o":"0100020800ff","v":"1155"}]},{"fc":0,"c":2,"t":1614079432,"d":[{"o":"0100100700ff","v":"591"}]}]

Now I want to see energy 998216 Wh, power 591 W and datetime 1614079432 as 23.02.2021 12:23:52

**Comment by wielandp** [comment]
I was able to write a lua-cgi-script in my openwrt router doing the POST, parsing JSON and base64decoding.
Now it should be possible with HTTP-shortcuts, Will try it later.

**Comment by Waboodoo** [comment]
I added the 2 functions `base64encode` and `base64decode` now. They will become available once version 2.2.0 is released.

**Comment by wielandp** [comment]
Thanks. I will try it

**Comment by Waboodoo** [comment]
Version 2.2.0 is now released and brings support for the functions `base64encode` and `base64decode`.
See https://http-shortcuts.rmy.ch/scripting#text-processing
