### ISSUE TITLE
[BUG] Share button is not working if response body is too large

### ISSUE THREAD

**Issue by 0xTyagi** [Waboodoo/HTTP-Shortcuts#208]
If response body is too large then share button is not working. ~(maybe due to intent data is too large for transaction)~

Solution: an option to save response to file #125

**Comment by 0xTyagi** [comment]
https://github.com/Waboodoo/HTTP-Shortcuts/blob/c08422e48a57542f80f6a7ecf92a46426d6efb08/HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/activities/response/DisplayResponseActivity.kt#L165

**Comment by Waboodoo** [comment]
With the 2.0.0 release it is now possible to share larger responses, and you also have the option to save the response into a file.

**Comment by 0xTyagi** [comment]
thank you
