### ISSUE TITLE
Open Link with App on startup

### ISSUE THREAD

**Issue by suabo** [Waboodoo/HTTP-Shortcuts#209]
I want to use the app to improve my smart home. 
I have set up some nfc tags with links to my iobroker rest api. 
This works nice, but opens up a browser every time i scan the tag on my phone.

If I scan the nfc tag with my phone I can't select your app to open the link. This would be a nice feature if it would show up here.
It is also possible to set a startup app in the tag it self, so you don't have to associate links to http-shortcuts app general.

It would be cool if the link that is passed to the app is first checked with known links and adept the settings if a match is found.
That way you would also enable all the features your app offers to users with nfc tags.

**Comment by Waboodoo** [comment]
As of version 2.0.0 (which is being released now), you have the option to trigger a shortcut via a deep-link. You can invoke a URL of the form **http-shortcuts://deep-link/<shortcut-id>**, where *<shortcut-id>* has to be replaced with the ID of the shortcut you want to trigger. Optionally, you can query parameters to the URL to pass in values for variables. E.g. if you have a variable named "my_var" you could trigger a shortcut which uses this variable and pass it a specific value, e.g. **http-shortcuts://deep-link/2dddb06f-9b46-49fd-8378-ab1a5ac195cf?my_var=42**

You should be able to use these URLs in your NFC tags which should allow you to trigger a particular shortcut directly from a tag.

**Comment by suabo** [comment]
Thanks a lot for implementing this! I tried to write such a link to a nfc tag and it works perfekt, but now there is another message: "New Tag..." and i have to click on it, which is sad. Maybe you have some advice on how to avoid the message coming from android?

![Screenshot_20210203-161746_Tags](https://user-images.githubusercontent.com/5021753/106768010-ca6a4d80-663b-11eb-8ee8-1570b5fac5b4.jpg)

**Comment by Waboodoo** [comment]
I'm not familiar with this feature, and I'm not sure where that message is coming from. I assume it is part of the Android OS itself, or of a custom part added by the vendor. In either case, it's probably not configurable.
