### ISSUE TITLE
Wrapping json response

### ISSUE THREAD

**Issue by sinancetinkaya** [Waboodoo/HTTP-Shortcuts#212]
My requests return long text fields in json responses.
Could you add wrapping json response in the response window? 
And also prettifying & wrapping json response in the response dialog window?

**Comment by Waboodoo** [comment]
Could you give an example or a more detailed explanation of how you imagine it to look? The app already tries to prettify JSON in the response window, so not sure what you'd like to see changed.

**Comment by sinancetinkaya** [comment]
In your app there are 3 display types, right?
1-Toast Popup
2-Dialogue: Wraps lines but doesn't prettify
3-Window: Prettifies but it doesn't wrap lines.

I assume you already know what wrapping a text line is?

**Comment by Waboodoo** [comment]
Yes, the 'Window' display type will prettify and syntax-highlight JSON, but not wrap it. The main reason for that is that I personally think that when lines are wrapped in JSON it becomes much less readable and it partially negates the purpose of prettifying. However, I see that there might be different preferences and that in some cases wrapping is better than having to scroll a lot. In order not to break the current behavior, I'm introducing a toggle: by default the JSON response is displayed without line wrapping, but by clicking it it can be toggled on.

I will include this change in the upcoming 2.0.0 release.

### Without line wrapping
![Screenshot from 2021-01-24 10-00-02](https://user-images.githubusercontent.com/2445563/105625732-72f20380-5e2b-11eb-9f89-1cb0022cdb09.png)

### With line wrapping
![Screenshot from 2021-01-24 10-03-35](https://user-images.githubusercontent.com/2445563/105625734-738a9a00-5e2b-11eb-9234-5c37335b5c70.png)

**Comment by sinancetinkaya** [comment]
Thank you 👍

**Comment by Waboodoo** [comment]
This change is now being released as part of version 2.0.0.
