### ISSUE TITLE
[BUG] Sharing randomly stop working after first try.

### ISSUE THREAD

**Issue by sebastiannielsen** [Waboodoo/HTTP-Shortcuts#214]
**Steps To Reproduce**
Use share to share data to HTTP shortcuts. It works wonderfully.
Now do it again. It doesn't work.
Spam the share button - then it will occasionally work.

Also tried the "Run requests in foreground" checkbox in settings - no difference.

If I press Edit on shortcut, and then change nothing, and then save, it guranteed to work next time.

**Expected behavior**
Executiion should work everytime.

**Actual behavior**
Execution randomly don't work after first request.

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version 2.0.0
 - Any other context about the problem that you think is relevant

**Comment by Waboodoo** [comment]
Thanks for the bug report. I am so far unable to properly reproduce this issue. I observe that sometimes the Share button seemingly does nothing, but I don't know what's causing it. What I noticed is that sometimes it just takes a long time (1 second or more) for the shortcut to trigger.

I have two followup questions:
- What response display type are you using for your shortcut (toast, dialog or window)?
- Did you observe this bug already in an older version or do you think it was introduced in 2.0.0?

**Comment by sebastiannielsen** [comment]
1: I tought also first, that the response type is at fault, so I have tried all 3.
2: As far as I know, it worked in version 1.38. Could also be something that is introduced by Android 11. But unsure as I didn't heavily test it as much.
3: Both
4: https://play.google.com/store/apps/details?id=nl.innovalor.nfciddocshowcase

Have also tried with different "timeout" settings but didn't work either.

**Comment by Waboodoo** [comment]
Thanks. I might have found the cause of the issue. I applied a fix which will I'm also including in the 2.0.0 release. Since I can't fully reproduce it I'm not sure if it's fixed now, so let's wait and see

**Comment by sebastiannielsen** [comment]
Ill test it once its released. Im enrolled in beta branch so if you want, you could push it already now.

**Comment by Waboodoo** [comment]
2.0.0 is now being released, so you should soon be able to try it out.

Regarding the timeout value: I'm actually not sure what this means in detail. The value is applied as a connect timeout, a read timeout and a write timeout, so basically it applies for the overall connection, starting from when the TCP socket is connected. Changing this value is only of interest when the server you're connecting to is expected to take a long time to respond. In most cases you don't have to change this value.

**Comment by sebastiannielsen** [comment]
Got the release now, and can say that it works flawlessly now. The share button responds everytime. So, bug successfully fixed!
