### ISSUE TITLE
[BUG] Choose Custom Image crashes app on Android 11

### ISSUE THREAD

**Issue by pizzabreath** [Waboodoo/HTTP-Shortcuts#216]
**Steps To Reproduce**
1. Go to 'Edit Shortcut'
2. Click on 'Icon'
3. Click on 'Choose Custom Icon'
4. App crashes

**Expected behavior**
No crash.

**Actual behavior**
Crash

**Context (please complete the following information):**
 - Android OS Version: 11.0 (Android One; Update 5. Jan 2021)
 - App Version 2.0.0

I've also tried to manually allow access to the filesystem before trying to chose a custom image, but the app crashes nonetheless.

**Comment by Waboodoo** [comment]
Thanks for reporting this. I will fix this for the next release.

**Comment by pizzabreath** [comment]
Thank you very much for all the hard work and the fantastic app!

**Comment by Waboodoo** [comment]
This should now be fixed.
