### ISSUE TITLE
The response window can display PNG or JPG images？

### ISSUE THREAD

**Issue by touchmii** [Waboodoo/HTTP-Shortcuts#217]
I want to get information that can only be described by a picture

now only window can show image

**Comment by Waboodoo** [comment]
I don't understand the question. Yes, the response window can display PNG or JPG images.

**Comment by touchmii** [comment]
> I don't understand the question. Yes, the response window can display PNG or JPG images.

![Uploading C35BFA03-212C-4E7A-9BD7-D96B558D4A1A.jpeg…]()

**Comment by Waboodoo** [comment]
The "Dialog Window" only supports displaying text (with some basic HTML formatting). If you want to display image responses you have to use the "Fullscreen Window" option.

**Comment by Waboodoo** [comment]
I will include support for displaying images in the "Dialog Window" as part of the upcoming 2.3.0 release.

**Comment by Waboodoo** [comment]
Version 2.3.0 is now released, which should fix this issue.
