### ISSUE TITLE
[BUG] Can't reproduce POST 

### ISSUE THREAD

**Issue by arcadenea** [Waboodoo/HTTP-Shortcuts#218]
**Steps To Reproduce**
I'm using RESTClient and CURL to send commands to a TV. It works fine on both but can't make it work on HTTP Shortcuts.

This is what i use on RESTClient:
Method: POST
URL: http://tvaddress:49152/avt_control
Custom Header: SOAPaction: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"
Custom Header: Content-Type:text/xml; charset="utf-8"
Body:
```
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
 <s:Body>
  <u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
    <CurrentURIMetaData>video</CurrentURIMetaData>
    <CurrentURI>http://videourl</CurrentURI>
    <InstanceID>0</InstanceID>
  </u:SetAVTransportURI>
 </s:Body>
</s:Envelope>
```

This is the CURL command:
```
echo '
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
 <s:Body>
  <u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
    <CurrentURIMetaData>video</CurrentURIMetaData>
    <CurrentURI>http://videourl</CurrentURI>
    <InstanceID>0</InstanceID>
  </u:SetAVTransportURI>
 </s:Body>
</s:Envelope>
' | curl -v -d @- \
 -H 'SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"' \
 -H 'content-type: text/xml; charset="utf-8"' \
 http://tvaddress:49152/avt_control
```

**Expected behavior**
The same with RESTClient or CURL.

**Actual behavior**
The TV answers with "Invalid Action".

**Screenshots**
The exported json script is attached
[shortcut.txt](https://github.com/Waboodoo/HTTP-Shortcuts/files/6173377/shortcut.txt)

**Context (please complete the following information):**
 - Android OS Version: 9.0
 - App Version 2.0.0

**Comment by Waboodoo** [comment]
Could it be because in your shortcut's request body you are missing the `<?xml version="1.0"?>` part at the beginning?

**Comment by arcadenea** [comment]
I think it's related to double quotes in: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI". It doesn't work without that and if i send an empty body the error is "XML Error" (tested on RESTClient).

**Comment by Waboodoo** [comment]
Sending double quotes in a header should not be a problem. I tested it just now.

You can try using the Chrome debugger tools as described [here](https://http-shortcuts.rmy.ch/faq#debugging) to check what exactly the app is sending and receiving.

**Comment by arcadenea** [comment]
Thanks for the tip but i don't even use Chrome. I've fixed this using just netcat, diff'd both outputs and the problem was that some line breaks in the XML were different. Just edited them on HTTP Shortcuts and it worked!

This simple command was everything that i needed:
```
xxxxx@xxxxx:~/xxxxx$ sudo nc -lv xx.xx.xx.xx 80
Listening on [xx.xx.xx.xx] (family 2, port 80)
Connection from xx.xx.xx.xx 33650 received!
POST / HTTP/1.1
Connection: close
SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"
User-Agent: HttpShortcuts/2.0.0 (Linux; U; Android 9; 5101A Build/PPR1.180610.011)
Content-Type: text/xml; charset="utf-8"
Content-Length: 439
Host: xx.xx.xx.xx
Accept-Encoding: gzip

<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
<CurrentURIMetaData>video</CurrentURIMetaData>
<CurrentURI>http://videourl</CurrentURI>
<InstanceID>0</InstanceID>
</u:SetAVTransportURI>
</s:Body>
</s:Envelope> 
```
