### ISSUE TITLE
Feature Request: GPS position variable

### ISSUE THREAD

**Issue by hadmut** [Waboodoo/HTTP-Shortcuts#221]
Hi, 
would be nice to have a variable type GPS/Geolocation, which, by default, is set to the current position of the Android device. 

Somewhat more complicated: Optionally allow manual input by opening an google maps map and touch a position on the map. 

Addional feature: compass reading (heading)

regards

**Comment by Waboodoo** [comment]
This is already being tracked by https://github.com/Waboodoo/HTTP-Shortcuts/issues/95
