### ISSUE TITLE
SSL client auth without android keystore

### ISSUE THREAD

**Issue by Jontron123** [Waboodoo/HTTP-Shortcuts#222]
Is it possible to use SSL client authentication without loading the credentials from the android keystore? Say maybe loading them directly from a certificate and key file, or a .p12 file?

My reason for wanting to do this is I have a tablet that sits on my coffee table and I use like a remote. Currently to be able to use SSL client authentication, you have to add the credentials to the android keystore, which requires you to set a pin or password. 
As this tablet just sits on my coffee table, setting a pin or password is just irritating, and makes it harder for family and friends to use the tablet. Loading the credentials directly without using that android keystore would allow me to not have to set a pin or password.

**Comment by Waboodoo** [comment]
That sounds reasonable as a use-case, I'm integrating support for using a .p12 file directly. Although keep in mind that this will be less secure than using the Android keystore, as the .p12 file itself will not be protected in a secure way.

I'm including this in the next release (2.4.0), which has no known release date yet.

**Comment by Waboodoo** [comment]
This is now available as part of the 2.4.0 release.

**Comment by Jontron123** [comment]
Just tried version 2.4.0 and it works great! Thank you very much!
