### ISSUE TITLE
Support TLS 1.3

### ISSUE THREAD

**Issue by boocov** [Waboodoo/HTTP-Shortcuts#224]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I want to use HTTP-Shortcuts with my server, which is configured to use TLS 1.3 only, but the app fails with an protocol error.

![http_shortcut_tls_1_3](https://user-images.githubusercontent.com/83019633/115747374-7e56bb80-a395-11eb-92a9-45380023481a.png)
You can also test TLSv1.3 only via https://tls13.browserleaks.com

**Describe the solution you'd like**
Please add support for TLS 1.3.

**Describe alternatives you've considered**

**Additional context**

**Comment by Waboodoo** [comment]
Thanks for the link, that was helpful for testing. I will include TLSv1.3 support in the next release.

**Comment by Waboodoo** [comment]
This is now available as part of the 2.4.0 release.

**Comment by boocov** [comment]
Thank you very much. Works perfectly 😄 
I sent you a little donation.
