### ISSUE TITLE
 [BUG] CLEARTEXT communication not enabled for client

### ISSUE THREAD

**Issue by roelleke** [Waboodoo/HTTP-Shortcuts#226]
I just updated to version 2.4.0 and got the Error message: CLEARTEXT communication not enabled for client
on every shortcut and on two devices.

**Comment by Waboodoo** [comment]
oh no, looks like in my eagerness to implement and test TLS 1.3 support, I broke cleartext support.
I have pushed out a fix to the Play Store, it should be available for updating shortly.
Apologies for any inconvenience caused.

**Comment by jmpavlec** [comment]
Also has this problem this morning. The update in the play store has fixed it now. Thanks!

**Comment by Waboodoo** [comment]
@roelleke Thanks for reporting
@jmpavlec Thanks for confirming that it works again

Closing this now as resolved
