### ISSUE TITLE
Allow set empty name if set icon

### ISSUE THREAD

**Issue by MasterYura** [Waboodoo/HTTP-Shortcuts#227]
![Screenshot_20210508_140717_com huawei android launcher](https://user-images.githubusercontent.com/1090712/117536956-bb15ea00-b006-11eb-9e5a-a5bb3b84164a.jpg)
![Screenshot_20210508_140713_ch rmy android http_shortcuts](https://user-images.githubusercontent.com/1090712/117536959-bc471700-b006-11eb-9389-0efcfd70eea6.jpg)

**Comment by Waboodoo** [comment]
Unfortunately, having a shortcut without a label is not technically possible on Android. The operating system does not allow it.
However, if you want to have a shortcut without a label, you can just use the "Customizable Widget" option instead. You will find it when adding widgets to your home screen, and there you have the option to hide the shortcut label.

![Screenshot_1620643331](https://user-images.githubusercontent.com/2445563/117647385-31dcef80-b18d-11eb-9dba-a719ee6f4c6d.png)
