### ISSUE TITLE
Feature Request: Adding multiline text to form input

### ISSUE THREAD

**Issue by beRoller** [Waboodoo/HTTP-Shortcuts#229]
**Is your feature request related to a problem? Please describe.**
i have problem making my input see if i have a long text input.

**Describe the solution you'd like**
adding this option multiline text input is much better when making i request like sending request to an api like discord and other chatbots or apps to read multi line inputs.

Thanks..

**Comment by Waboodoo** [comment]
Just to clarify, by "form input", do you perhaps mean "Text Input" variables?

**Comment by Waboodoo** [comment]
With the 2.5.0 release there is no the option to have multiline text for "Text Input" variables.
