### ISSUE TITLE
Feature Request: Support Zeroconf/Bonjour/mDNS

### ISSUE THREAD

**Issue by 13rac1** [Waboodoo/HTTP-Shortcuts#230]
**Is your feature request related to a problem? Please describe.**
Cannot create HTTP shortcuts to Zeroconf/Bonjour/mDNS `.local` domains.

**Describe the solution you'd like**
HTTP requests to `http://my-iot-device.local` should work in addition to `http://x.x.x.x` IP addresses.

**Describe alternatives you've considered**
I currently use the device IP address, but it is tedious and error prone.

**Additional context**

An Android OS issue, which *should* be handled at the OS level as it is in Linux, Windows, MacOS, and iOS. The workaround is handling it in-app.

* Example implementation https://www.dodgycoder.net/2015/02/setting-up-bonjourzeroconfmdnsnsd.html
* Android docs for using NSD https://developer.android.com/training/connect-devices-wirelessly/nsd.html#discover
* Android OS feature requests:
    * [Zeroconf/Bonjour support, so I can do things like http://mycomputer.local](https://issuetracker.google.com/issues/36932514?pli=1)
    * [Add .local mDNS resolving to Android](https://issuetracker.google.com/issues/140786115)

**Comment by Waboodoo** [comment]
Thanks for the useful links. This seems doable to implement, and it is not the first time it has been requested, so I think I will look into this when I have time.

**Comment by Waboodoo** [comment]
@13rac1 I have published version 2.6.0 for [beta testing](https://play.google.com/apps/testing/ch.rmy.android.http_shortcuts) in the Play Store, which includes an implementation of Zeroconf/mDNS. If possible you could give it a try to see if it works the way you imagined.

**Comment by 13rac1** [comment]
Cool! I've joined the Beta.
> Beta signup in progress. It takes a few minutes.

Been about a hour now... I'll test when the App store allows me.

**Comment by Waboodoo** [comment]
@13rac1 Any progress? Hope the installation has worked by now.

**Comment by 13rac1** [comment]
Hi! Busy week...

The beta has installed correctly. My laptop can `curl` my NAS, Raspberry Pi, and a ESP8266 using `.local` DNS. HTTP Shortcuts can connect to the NAS by mDNS name, but not the Pi or the ESP8266. It returns:
```
test failed: Unable to resolve host
"pi.local": No address associated by hostname
```
Curiously [.Local Finder](https://play.google.com/store/apps/details?id=com.dokoden.dotlocalfinder&hl=en_US&gl=US) [[source](https://github.com/Network-Revolution/DotLocalFinder)] works to find IPs for all three devices.

**Comment by Waboodoo** [comment]
That is unfortunate. I spent a few more hours tinkering with this and found that mDNS on Android is simply cursed. For me the Local Finder app that you mentioned doesn't seem to work on either of the 2 devices that I tried it, so there seem to be some hardware or vendor software issues involved as well.

When researching this topic I found that everyone only talks about service resolution, hardly ever about host resolution, i.e., all the interfaces and libraries for mDNS on Android only deal with discovering services, but resolving a ".local" hostname to an IP address seems to be a much trickier problem.

The way the HTTP Shortcuts app works for now is that it scans for any service of type "_http._tcp" where the name of the service matches the host name. This is not the proper way to do it of course, so naturally it doesn't work properly in most of the cases. It seems to work for your NAS, so I assume that the NAS advertises such a service using the same name, while your other 2 devices do not. So maybe as a workaround you could try to configure your Pi to advertise a "_http._tcp" service in the local network. Not great, but I'm out of ideas for now on how to make this work out of the box, so I'll leave this as it is now and hopefully find some pointers eventually.

**Comment by 13rac1** [comment]
Ugh. I'm sorry you hit this deadend. Thanks for looking at it! 

NAS is a QNAP with all network support enabled, so it makes sense it's the easiest to locate on the network.

This _should_ be just supported by Android as it is in every other OS. The original now-closed [feature request is from TEN YEARS ago](https://issuetracker.google.com/issues/36932514?pli=1) and even the ["new" open feature request is two years old](https://issuetracker.google.com/issues/140786115). May be best to delete it from your codebase to avoid the support headaches? How frustrating 🤦🏼 

**Hey! Anyone else find this issue? Star this feature request: [Add .local mDNS resolving to Android
](https://issuetracker.google.com/issues/140786115)**
