### ISSUE TITLE
can support websocket?

### ISSUE THREAD

**Issue by touchmii** [Waboodoo/HTTP-Shortcuts#231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Waboodoo** [comment]
@touchmii Can you please provide some details of what your usecase is, how you imagine this could work or what you would like to use it for?

**Comment by Waboodoo** [comment]
Closing this as not enough information provided.
