### ISSUE TITLE
Script Get a File Input

### ISSUE THREAD

**Issue by X7md** [Waboodoo/HTTP-Shortcuts#232]
I think If there is a way to get a File Input form user as a JavaScript BLOB or something like this, will be a great idea to handle files.

**Comment by Waboodoo** [comment]
The app already has ways for handling file input from the user, though not directly through Scripting.
Could you maybe share a usecase or some idea of what you would like to do here?

**Comment by Waboodoo** [comment]
Closing this as not enough information provided.
