### ISSUE TITLE
request documents on share button

### ISSUE THREAD

**Issue by songsammy** [Waboodoo/HTTP-Shortcuts#235]
**Is your feature request related to a problem? Please describe.**
I want to share a file to my pc. The file is from a proprietary software , and the only (easy) way was to share it to get it out for further processing.
**Describe the solution you'd like**
I saw the button "share via httpshortcut", I clicked it , it told me to set a variable, i dug through the document and didn't know how.
I have implemented a file recieving script with PHP on my desktop,which recieves form data.
I want an example of how to share a file to a url via share button.

**Describe alternatives you've considered**
Share via other services. I don't feel like using them as my file would travel through the internet, it is neither safe or fast.
Open a http server via termux. Acceptable,but too much work needed.

**Additional context**

**Comment by Waboodoo** [comment]
You can set up a shortcut to allow sharing a file as form-data by doing the following:

1. Open the editor for your shortcut (via long press -> Edit)
2. Open the "Request Body / Parameters" section
3. Set the "Request Body Type" to "Parameters (form-data)"
4. Click the + button
5. Select "Single File" as the Parameter Type in the dialog
5. In the dialog window that pops up, enter the parameter name for your file
6. Optionally also give it a file name. If you leave this empty, the app will try to use the file's original name or generate one
7. Save your changes

![Screenshot_20210814-141642](https://user-images.githubusercontent.com/2445563/129446122-638165bf-73c0-46a0-b21d-faab3a8a10ab.png)

If you now trigger this shortcut, it will prompt you to select a file, and will then make an HTTP request with your file sent as form-data. Alternatively, you can trigger the shortcut by sharing a file into the HTTP Shortcuts app.

Hope this helps. Let me know if something doesn't work.
I'll try to create a proper tutorial / help page for this at some point.
