### ISSUE TITLE
[BUG] Issue with response.headers in scripting

### ISSUE THREAD

**Issue by chirag755** [Waboodoo/HTTP-Shortcuts#245]
hello there,
``
it seems there is issue with `response.headers`

i tried testing it via https://google.com and tried to parse its headers via `response.headers['Content-Type']`

and when it hasnt worked then i parsed all repsone using `repsone` and saved to it a file and i found out that only body,statuscode and cookie was in my saved file, there was no headers value in it.

you can also reproduce this by parsing any header via scripting

**Comment by Waboodoo** [comment]
Version 2.10.0 is now released, so this issue should be resolved.
