### ISSUE TITLE
Unable to install on Sony A80J via sideload

### ISSUE THREAD

**Issue by Ajmartin001** [Waboodoo/HTTP-Shortcuts#248]
Attempting to sideload app on Sony A80J running latest build of Google TV results in ‘unknown error’ / failure to install. 

This works on other android TV devices I tried via the same method.

**Comment by Waboodoo** [comment]
Which APK did you use for installing the app? Make sure it is the right one for your TV's hardware. If you're unsure you can also use the [universal APK](https://github.com/Waboodoo/HTTP-Shortcuts/releases/download/v2.11.0/app-universal-release.apk).

**Comment by Ajmartin001** [comment]
Hey thanks for the reply - I used the universal APK from F-droid.

**Comment by Ajmartin001** [comment]
No joy. Same issue

**Comment by Waboodoo** [comment]
Closing this issue now, because I don't think there's anything I can do to fix this. Can't even really debug it :/.
