### ISSUE TITLE
Add Share Targets

### ISSUE THREAD

**Issue by dshanske** [Waboodoo/HTTP-Shortcuts#259]
**Is your feature request related to a problem? Please describe.**
Looking to register a shortcut as a share target so I can forward what I share from other apps via httppl

**Describe the solution you'd like**
A registered share target that would trigger http shortcuts.

**Comment by Waboodoo** [comment]
This is already possible, to some extent at least. Below I've summarized how you can make use of it. Let me know if this is not sufficient for your usecase.

### Sharing Text
If you want to share text via a HTTP shortcut, you can do so like this:

1. Open the app
2. Open the dropdown menu at the top right and select "Variables"
3. Click the + button and select "Static Variable (Constant)" as the variable type
4. Enter a name for the variable
5. **Tick the "Allow 'Share...'" checkbox
6. Click the checkmark button at the top right to save your variable
7. Go back to the app's main screen
8. Click the + button to start creating a new shortcut or long press an existing shortcut and select "Edit" to open the shortcut editor
9. Find the input field for the place where you want to share the text as, e.g. the URL, the request body or a header. Click the "{}" button next to that field
10. Select the variable that you created earlier
11. Save the changes to your shortcut
12. You should now be able to share text from other apps (e.g. a URL from a browser) into the HTTP Shortcuts app and there select your shortcut as the share target. It will execute the shortcut and insert the shared text into where you put the variable placeholder.

### Sharing Files
If you want to share a file, you can so by opening the "Request Body / Parameters" section in the shortcut editor and there either set the "Request Body Type" to "File (Picker)" or set it to "Parameters (form-data)" and then add a parameter of type "Single File" or "Multiple Files". After that save your changes. You should now be able to share files into the HTTP Shortcuts app and it will allow you to pick the shortcut as a target. This will execute the shortcut and it will use the content of the shared file as the request body or as a form parameter.

**Comment by dshanske** [comment]
I'll try it . couldn't find it in the manual

**Comment by dshanske** [comment]
How do you share a link as opposed to text?

**Comment by dshanske** [comment]
To be specific, some applications send title and URL,

**Comment by Waboodoo** [comment]
Currently it is only possible to share text this way, which in case of sharing a link usually means only the URL, not the title. Even if the title (or called *subject* sometimes) is provided by the source app, it is currently ignored by the HTTP Shortcuts app.

**Comment by Waboodoo** [comment]
I will include an option to allow sharing both title and text into a variable. This will be part of the next release (2.14.0)

**Comment by dshanske** [comment]
Thanks.... my solution was in the interim to break the string into parts by spaces, and check if the last space was a url... but it means title won't pass through

**Comment by Waboodoo** [comment]
The new feature is now released as part of 2.14.0

When editing a variable, in addition to enabling it for receiving a value from sharing, it is now possible to declare whether the shared text, title, or both should be used as the variable's value.
