### ISSUE TITLE
Changelog disappears after rotating screen

### ISSUE THREAD

**Issue by mmc20520** [Waboodoo/HTTP-Shortcuts#261]
**Steps To Reproduce**
1. Open Changelog
2. Rotate screen
3. Log disappears

**Expected behavior**
Log should be there with a correct scroll position

**Actual behavior**
Log disappears

**Screenshots**
Before rotation:
![pic13](https://user-images.githubusercontent.com/100833575/156762832-30923ec4-8c30-4ca0-acda-60b79ea957a3.png)

After rotation:
![pic14](https://user-images.githubusercontent.com/100833575/156762852-c677699a-db89-4d20-80fe-e10e0d3ac008.png)

**Context (please complete the following information):**
 - Android OS Version: Android 10
 - App Version v2.12.0
 - Any other context about the problem that you think is relevant

**Comment by Waboodoo** [comment]
Thanks for the bug report. This is due to a technical limitation, and it applies to basically every dialog in the app, not just the changelog.

**Comment by mmc20520** [comment]
Thanks for your reply, I also found a similar that is scroll position of acknowledgements is also lost after device rotation. Would you be able to take a look at #264? Thanks for your effort!

**Comment by Waboodoo** [comment]
This is now fixed as part of the 2.14.0 release.
