### ISSUE TITLE
[BUG] several dialogs disappear on screen rotation

### ISSUE THREAD

**Issue by davirec** [Waboodoo/HTTP-Shortcuts#262]
When I perform these sequences of events, the dialog disappears on-screen rotation:
**Steps To Reproduce**
1. Go to the Main activity
2. Tap in add (plus in the right bottom)
3. A fragment similar to this will appear:

<img src="https://user-images.githubusercontent.com/3637419/156907758-3767c839-cd8c-46a7-b0a9-468f5c79f3ba.png" width=30% height=30%>

4. Force the pause from the activity and then return to the activity (double rotation). Note that the fragment disappears. Note: the pause from activity can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

**Expected behavior**
The expected behavior is the return to the previous state with the fragments of the previous image.

**Actual behavior**
However, the fragment disappears.

<img src="https://user-images.githubusercontent.com/3637419/156907761-ab3caabc-1157-4015-81e7-8e63c579f9a1.png" width=30% height=30%>

This bug occurs in activities:
- AboutActivity
- BasicRequestSettingsActivity
- CategoriesActivity
- ExecutionSettingsActivity
- ImportExportActivity
- MainActivity
- ResponseActivity
- ScriptingActivity
- SettingsActivity
- ShortcutEditorActivity
- VariablesActivity

Device:
- Device: Moto G30 with OS: Android 11
- Version: 2.12.0
- Device language: English

**Comment by Waboodoo** [comment]
Thanks for the bug report. This is basically the same bug as https://github.com/Waboodoo/HTTP-Shortcuts/issues/261. It applies to any dialog window in the app. There is currently a technical limitation around this, and I'll need to do some more refactoring to preserve the state of these dialogs. So, for now, this is "expected" behavior.

**Comment by davirec** [comment]
Thanks

**Comment by Waboodoo** [comment]
Most if not all of these should now be addressed. There are still a handful of dialogs that might get lost on a configuration change, so I'll keep this issue open until I'm sure I got them all.

**Comment by Waboodoo** [comment]
I believe that at this point (as of version 2.18.0), the only dialogs that disappear or lose state when the activity is recreated at the ones created when clicking one of the many "{}" variable insertion buttons in the app. I will try to fix those soon.

**Comment by davirec** [comment]
Thanks

**Comment by Waboodoo** [comment]
In version 3.0.0 I overhauled the entire app's UI. I hope that as part of this, I managed to fix this issue for all the dialogs.
