### ISSUE TITLE
[BUG] Data loss while using the app.

### ISSUE THREAD

**Issue by davirec** [Waboodoo/HTTP-Shortcuts#263]
When I perform these sequences of events, the elements of the activity disappear on-screen rotation:
**Steps To Reproduce**
1. Go to the Main activity
2. Tap in add (plus in the right bottom)
3. Tap in Regular HTTP Shortcut
4. Tap in Response Handling
5. A activity similar to this will appear:

Before rotation:
<img src="https://user-images.githubusercontent.com/3637419/156908626-84871216-13fa-4201-aeb5-aebc3da065d0.png" width=30% height=30%>

6. Force the pause from the activity and then return to the activity (double rotation). Note that the elements of the activity disappear. Note: the pause from activity can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

**Expected behavior**
The expected behavior is the return to the previous state with the elements of the activity of the previous image.

**Actual behavior**
However, the elements of the activity disappear.

After rotation:

<img src="https://user-images.githubusercontent.com/3637419/156908627-93e99caa-00db-4b3e-98ab-6580fe7a547a.png" width=30% height=30%>

Device:
- Device: Moto G30 with OS: Android 11
- Version: 2.12.0
- Device language: English

**Comment by Waboodoo** [comment]
Thanks for the bug report. This activity was completely rebuilt in app version 2.13.0, and I can not reproduce this particular issue there. Could you try out whether this bug still exists for you if you update the app to 2.13.0?

**Comment by davirec** [comment]
Hello, the issue has been resolved in version 2.13.0. 

I made a video with the problem in the previous version (2.12.0) to be registered.
https://user-images.githubusercontent.com/3637419/157357045-6d21ecf9-04b9-4f2b-ac73-ff84b5c3939f.mp4

**Comment by Waboodoo** [comment]
Glad to hear it's resolved. I'll then close this issue.
