### ISSUE TITLE
Similar to #261, scroll position of acknowledgements is lost after device rotation

### ISSUE THREAD

**Issue by mmc20520** [Waboodoo/HTTP-Shortcuts#264]
Similar to #261 

Scroll position of acknowledgements was also lost after device rotation

Before rotation:

<img width="290" alt="Screen Shot 2022-03-06 at 3 41 24 PM" src="https://user-images.githubusercontent.com/100833575/156913912-6271fca1-5440-48ab-87db-a43d317c5c7c.png">

After rotation:

<img width="615" alt="Screen Shot 2022-03-06 at 3 41 31 PM" src="https://user-images.githubusercontent.com/100833575/156913915-1728e330-e8e4-4a9e-89e4-04895e5d660e.png">

**Comment by Waboodoo** [comment]
This is basically the same issue as https://github.com/Waboodoo/HTTP-Shortcuts/issues/261. It applies to all dialog windows, as well as all webview-based activities in the app. As the "Acknowledgements" screen is not a primary part of the app's functionality and screen rotations don't happen very frequently, I will treat this bug with low priority.

**Comment by Waboodoo** [comment]
This is now fixed and released with version 2.13.1.
