### ISSUE TITLE
[BUG] Input fields are empty when editing existing shortcut

### ISSUE THREAD

**Issue by arminus** [Waboodoo/HTTP-Shortcuts#266]
**Steps To Reproduce**
In the following clip, both the shortcut name and the JS code fields are empty. When I upload the shortcut for browser editing, the JS code is properly shown - so this is just a display issue (there is no device rotation involved):

![EmptyFields](https://user-images.githubusercontent.com/683680/158028520-40b19bbc-77b7-4bdb-b05d-1d3f20d2db97.gif)

**Expected behavior**
All fields should display their content in shortcut edit

**Actual behavior**
Some edit fields are empty

**Screenshots**
See above

**Context (please complete the following information):**
 - Android OS Version: 8.0.0 / Samsung Galaxy A5
 - App Version 2.13.1/PlayStore

**Comment by Waboodoo** [comment]
Thanks for the bug report. It will be fixed in the next release.

**Comment by Waboodoo** [comment]
This should now be resolved, as part of the 2.14.0 release. Please let me know if the problem (or a similar one) still exists.
