### ISSUE TITLE
[BUG] Import Not working

### ISSUE THREAD

**Issue by roelleke** [Waboodoo/HTTP-Shortcuts#277]
**Steps To Reproduce**
1. Go to 'Import / Export'
2. Click on 'Import from File'
3. Scroll down to 'Choose exported shortcuts.zip'

**Expected behavior**
Import all shortcuts and Variables.

**Actual behavior**
Error Message “Import fehlgeschlagen Duplikate Variable Keys“

**Screenshots**

**Context (please complete the following information):**
 - Android OS Version: 11.0
 - App Version: 2.17

**Comment by Waboodoo** [comment]
The error message "Duplicate variable keys" means that your imported file contains one or more variables which have the same keys (i.e., names) as variables you already have in the app. You'll need to delete or rename those variables for the import to work.

**Comment by roelleke** [comment]
Yes, tryed to do that, but I don't have any duplicate Variables.

**Comment by Waboodoo** [comment]
There are 2 variables with key "Markise" in this import file.

**Comment by roelleke** [comment]
Thanks for your help. 
I found some more duplicates after the Variables are sorted alphabetically. But I couldn't unterstand how it is possible to produce them. 
It were nice when the sorting were possible automatically.

**Comment by Waboodoo** [comment]
Could it be that you had exported some variables from one device and then imported them onto another? Or exported variables, then added additional ones, and then imported the exported ones?
Upon importing, there is currently no check to make sure that combining the existing variables and the newly imported ones does not lead to duplicate variable names.

**Comment by Waboodoo** [comment]
I will include an option to alphabetically sort all variables in the 2.18.0 release
