### ISSUE TITLE
Reorder the Popup Menu when long pressing on the app icon

### ISSUE THREAD

**Issue by haitham506** [Waboodoo/HTTP-Shortcuts#278]
Hi,

Can we have the option to Reorder the Shortcuts in the Popup Menu when long pressing on the app icon.

**Comment by Waboodoo** [comment]
The shortcuts in the launcher popup appear in the same order in which they appear inside the app. If you want to change their order you can just move the shortcuts within their category (or across categories).

You might have to restart the app or make a change (any) to one of the shortcuts for the re-ordering to be applied.

**Comment by haitham506** [comment]
It worked. 
Thank you :)
