### ISSUE TITLE
F-Droid can't build due to GMS

### ISSUE THREAD

**Issue by linsui** [Waboodoo/HTTP-Shortcuts#279]
In https://github.com/Waboodoo/HTTP-Shortcuts/commit/53a438780dae5aeb60c07b496870e02d315b3323 GMS is added as a dep which is not FOSS. Could you please add a flavor without it for F-Droid? Thanks!

**Comment by Waboodoo** [comment]
I will move the feature (and its dependency) out of the "release" flavor as part of the next version (2.19.0)

**Comment by linsui** [comment]
Thanks!

**Comment by Waboodoo** [comment]
The release tag for version 2.19.0 is now created, which should fix this issue.

**Comment by linsui** [comment]
Thanks!

**Comment by Waboodoo** [comment]
@linsui I see that the `AutoUpdateMode` is still set to `None`, and that F-Droid has not picked up the `2.19.0` release. Is there still something wrong?

**Comment by Waboodoo** [comment]
Oh, that looks like Bugsnag got into the build task for the 'release' build again. I'll look into it and create a new tag once it's fixed.

**Comment by Waboodoo** [comment]
I *think* the issue is resolved now, and the latest tag should be buildable.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11365 It works, thanks!
