### ISSUE TITLE
[BUG] Error message is being displayed even when configured not to

### ISSUE THREAD

**Issue by zipiju** [Waboodoo/HTTP-Shortcuts#280]
**Steps To Reproduce**
Create POST shortcut that is sending JSON payload.
Configure shortcut response handling as Show nothing (run silently) for both On Success and On Failure.
Configure Scripting -> Run on Failure as const.message = JSON.parse(response.body).message; showDialog(message, 'Window title');
Receive JSON payload with "message": "value" in it with HTTP code 500.

**Expected behavior**
Expecting to see Dialog with title "Window title" and displaying the message received in JSON payload. After this dialog is shown and confirmed with OK do nothing more.

**Actual behavior**
Dialog is being displayed with correct title and having the received message, after confirming with OK however another message is displayed fullscreen as if the shortcut had Response Handling set to Show a detailed error message (Shortcut failed with status code 500...). After removing the Scripting -> Run on failure code nothing is being displayed as expected.

**Context (please complete the following information):**
 - Android OS Version 10
 - App Version 2.18.0

**Comment by Waboodoo** [comment]
Version 2.19.0 is now being released, which includes the fix for this bug.

**Comment by zipiju** [comment]
Thank you, I can confirm it is now working as expected.
