### ISSUE TITLE
Add support to display Base64 encoded images

### ISSUE THREAD

**Issue by Owlbertz** [Waboodoo/HTTP-Shortcuts#281]
**Is your feature request related to a problem? Please describe.**
I am using an API that returns an image as its Base64 representation inside a JSON structure. I want to display this. I tried`showPrompt` with `<img src="' + data.image + '">` but that only shows a teal square.

**Describe the solution you'd like**
I would love `showPrompt` to be able to handle the Base64 and display it as an image.

**Describe alternatives you've considered**
I feel like this needs a new implementation as I was not able to make it work with the existing tools.

Thank you for considering this.

**Comment by X7md** [comment]
+1
It will be nice if we handle dialog window through script

**Comment by Waboodoo** [comment]
Thanks for the detailed description. I agree that this sounds useful, and I can confirm that this is currently not possible in the app. I'll look into this, can't give a timeline for it yet though.

**Comment by Waboodoo** [comment]
This is now implemented and released as part of version 2.21.0
