### ISSUE TITLE
[BUG] Separator for multiple choice variables does not get saved

### ISSUE THREAD

**Issue by laberlaib** [Waboodoo/HTTP-Shortcuts#283]
Hi HTTP-Shortcut-Team,

to send commands to my vaccum cleaner I wanted to use the multiple select feature to make him clean a few rooms in a row.
A comma-seperated list is need, but I cannot define a seperator:

**Steps To Reproduce**
1. Go to 'variables'
2. Create a Mulitple-Choice Variable wih some options
3. Mark "Multiple oOptions selectable " (German: "Mehrere Optionen auswählbar")
4. Choose a separator
5. Save
6. Edit the variable and see that the field with the separator is empty

**Expected behavior**
The separator is filled between the values when selected multiple options.

**Actual behavior**
As the separator is not saved, the variables are send all attached togehter

**Screenshots**

**Context (please complete the following information):**
 - Android OS Version: Lineage 17 (Android 10)
 - App Version [e.g. 2.17]
![Screenshot_20220715-180800_HTTP_Shortcuts](https://user-images.githubusercontent.com/81492190/179263366-5f39d8fa-1682-46e7-b5d8-a10274e0c5fc.png)

Thanks for the great app, I am alread looking forward to the "clipboad as variable content" in 2.20 :)

Keep up the good work.
laberlaib

**Comment by Waboodoo** [comment]
This bug was already fixed in version [2.19.0](https://github.com/Waboodoo/HTTP-Shortcuts/blob/develop/CHANGELOG.md#version-2190). You'll need to update your app. In case you're using F-Droid, you might have to wait a few days for the update to become available, as there was an issue that prevented the app from being published there for a while.

**Comment by laberlaib** [comment]
Thx for the immediate reply and even more for the positive content.
Yes, I use F-Droid and now I tried to donwload 2.21 from the releases section but when I try to install it, it does not work and it does not provide any information why.

I try it again and otherwise I hope the F-Droid-Bugfix works well.

**Comment by Waboodoo** [comment]
Cool. Bear in mind though that if you switch from F-Droid to manually installed APKs, you won't receive updates from F-Droid anymore, so you'll either have to manually install the new APKs from the release page or switch back to F-Droid eventually if you want to update to newer versions of the app.

**Comment by Waboodoo** [comment]
Version 2.21.0 is now released on F-Droid, so I'm closing this issue.
