### ISSUE TITLE
[BUG] "Fetch favicon from page" does not work when variable is used

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#284]
**Steps To Reproduce**
1. Create static variable, e.g. lets call it "domain" and enter "google.com" as value
2. Create a shortcut with any name and use this url: https://www.{domain}
3. Click the icon and choose to fetch the favicon

**Expected behavior**
The sites favicon should be downloaded and be used as icon.

**Actual behavior**
An error is shown that the download failed because the site probably does not have a suitable favicon. 

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version 2.21.1

PS: Really awesome app!

**Comment by Waboodoo** [comment]
Thanks for the bug report. This will be fixed in 2.22.0. I also discovered a similar bug when exporting a shortcut to cURL, which will also be fixed as part of this.

**Comment by Waboodoo** [comment]
Closing this as version 2.22.0, which contains the fix for this, has been released.
