### ISSUE TITLE
[BUG] When only the option to confirm shortcut exection is change then saving is not possible

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#285]
**Steps To Reproduce**
1. Create a shortcut, enter any name and url which can be saved (but don't save, but you might be able to reproduce it when you save)
3. Scroll down to 'Trigger & Execution Setting' and **activate** the second last setting (that you have to confirm the execution)
4. Save the shortcut
5. Edit the shortcut. Scroll down to 'Trigger & Execution Setting' and **deactivate** the second last setting (that you have to confirm the execution)
6. (try to) save the shortcut

**Expected behavior**
it should be possible to save the change

**Actual behavior**
It is not possible to save the change. The icon to save is not visible.

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version 2.21.1

**Comment by Waboodoo** [comment]
Thanks for the bug report. The issue will be fixed in the next release (version 2.22.0)

**Comment by Waboodoo** [comment]
Closing this as version 2.22.0, which contains the fix for this, has been released.
