### ISSUE TITLE
[BUG] cannot remove variable from scripting dialog

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#286]
**Steps To Reproduce**
1. Create and save a variable
2. Create a normal shortcut.
3. Go to scripting. Which of the text fields are used does not matter 
4. Via Code insertion (so don't enter it manually) insert a variable read
5. Try to delete the newly inserted code 

**Expected behavior**
You can clear character by character

**Actual behavior**
You cannot delete the variable name enclosed in quotation marks 

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version: 2.21.1

**Comment by googol42** [comment]
Also happens with global scripting.

**Comment by Waboodoo** [comment]
Once more, thanks for the bug report. I was able to reproduce and fix this issue. The fix will be part of version 2.22.0.

**Comment by Waboodoo** [comment]
Closing this as version 2.22.0, which contains the fix for this, has been released.
