### ISSUE TITLE
[Feature] Preserve order of selected options for mutli select variables

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#288]
**Is your feature request related to a problem? Please describe.**
When using a multi select the order the options are selected are not reflected when outputting the variable. E.g. you use a multi select variable in the request body, the first selected option will be the first value in the request body and the second selected option will be the second value. 

**Describe the solution you'd like**
What I want: When I select the second option first and then the first option, then the second value should be first and the first value should be second. 

Solutions: Either add an option to the variable settings to preserve the order when outputting or just change the default behaviour. The order the options are selected should be reflected in the output. 

**Describe alternatives you've considered**
I haven't found any.

**Additional context**
I am using HTTP-Shortcuts to remote control a vacuum cleaner using Valetudo. There is a REST endpoint to clean multiple rooms/segments. The request body looks like this: `{"action":"start_segment_action","segment_ids":[{roomIDs}],"iterations":1,"customOrder":true}` When I select room/segment "A" first, I would like it be cleaned first. Etc.

Would that be possible to implement?

**Comment by Waboodoo** [comment]
I decided to go with the "just change the default behaviour" approach, as I think it will be a subtle enough change that likely special configuration will not be necessary. Starting with 2.23.0, the selection variable will return its value in the order in which the items were selected.

**Comment by googol42** [comment]
I tested it, but for me the order stayed always the same

**Comment by googol42** [comment]
Here some screenshots from my test setup:

![Screenshot_20220829-123342](https://user-images.githubusercontent.com/9155562/187182653-df41c570-72df-4a88-ac91-8bd5b35f9442.png)
![Screenshot_20220829-123350](https://user-images.githubusercontent.com/9155562/187182659-9510fdcd-f443-4837-8030-d52bac561770.png)
![Screenshot_20220829-123400](https://user-images.githubusercontent.com/9155562/187182691-072f5ffa-3b31-4178-b209-12ca94e88b1d.png)

It does not matter if I select first Option 1 and then 2 or the other way around, the dialog always shows "1,2"

**Comment by Waboodoo** [comment]
Did you test this with version 2.23.0? It's currently only available for beta testing. If you want to test this, you'd have to opt-in to the [beta program](https://play.google.com/apps/testing/ch.rmy.android.http_shortcuts) and then install the update from the Play Store.

**Comment by googol42** [comment]
I am already on the beta program and according to the "about" view I have 2.23.0 installed.

**Comment by googol42** [comment]
That's interesting. The app showed 2.23.0. I then clicked "View in Play Store" and there was an update available, which I installed. The app version is still 2.23.0 but now everything works. Maybe a bug in Android?

**Comment by Waboodoo** [comment]
Ah, that makes sense if you were already on the beta program. There are usually multiple releases on the beta channel, all under the same version number (basically, there is a 2.23.0.0 and a 2.23.0.1 in this case). So even if the app shows 2.23.0, it might still be that there is a newer 2.23.0 available for updating.
In any case, mystery solved, glad to hear it works for you now 👍🏻

**Comment by googol42** [comment]
Ah, good to know. Are new commits automatically pushed to the Play Store?

**Comment by Waboodoo** [comment]
No, creating a new release or beta version is a separately kicked-off process. I create new versions whenever there's a sufficiently large and/or stable set of changes.

**Comment by Waboodoo** [comment]
Closing this now as 2.23.0 has been released.
