### ISSUE TITLE
[BUG] List of "App Shorcuts" is not updated when duplicating or deleting a shortcut

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#289]
**Steps To Reproduce**
1. Create any shortcut which can be saved. Before saving activate the "Show as app shortcut on launcher" setting.
2. Go to the home screen and long press the app icon => the shortcut is shown in the list.
3. Duplicate the shortcut
4. Go to the home screen and long press the app icon
5. Check *Expected behavior*
6. Restart your phone or edit the duplicated shortcut.
7. Go to the home screen and long press the app icon => now both shortcuts are shown in the list.
8. Delete the duplicated shortcut
9. Check *Expected behavior*

I think the impact of this bug is very low, as you normally edit a duplicated shortcut anyway and if not, it is fixed after a restart of the phone. But I suppose that you just have to call an update hook when duplicating/deleting a shortcut to update the list of "quick launch actions"

**Expected behavior**
The duplicated shortcut should also be shown in the list.

**Actual behavior**
The duplicated shortcut is not shown in the list.

**Context (please complete the following information):**
 - Android OS Version: Android 11
 - App Version: 2.22.0

**Comment by Waboodoo** [comment]
Thanks for the bug report. As you pointed out, this was an easy fix. Launcher shortcuts are now also updated when shortcuts are duplicated or deleted. This will be part of the 2.23.0 release.

**Comment by googol42** [comment]
Wow. You're quick fixing bugs :+1:

**Comment by Waboodoo** [comment]
Closing this now as 2.23.0 has been released.
