### ISSUE TITLE
[Feature] Allow to update only the icon or only the icon colour and don't require to change both at the same time

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#290]
**Is your feature request related to a problem? Please describe.**
When choosing an icon for an action you first select the icon and then the colour. When you then check the "result" and decide to change the colour again (e.g. make the colour paler/sturdier) you have to search the _same_ icon again and then pick the _new_ colour. It is a tedious process to find the right colour.

Subproblem: I want multiple shortcuts/icons to have the same colour. Only workaround for this is to find the correct colour (which is tedious, see above) and then export the shortcuts and edit the hex codes in the json, zip the files again, and import it (which is also tedious).

**Describe the solution you'd like**
Instead of selecting the icon over and over again it would be nice to decide to only change the icon or to only change the colour. Would be better when it is not required to change both. A solution for the "subproblem" would be to be able to edit/copy/paste the hex code. So have a text field where the currently selected colour's hex code is shown which can be copied and changed.

One further addition: Allow to use a variable for the hex code. So one can update the colour of multiple shortcuts at once but this is just a bonus, which only makes sense I think, when you would implement a new colour variable type, because you wouldn't have a colour picker otherwise. So this "addition" is probably overkill and maybe less user friendly.

**Describe alternatives you've considered**
I haven't found any better solution. I could use my computer to search a colour but what the right colour is depends on the phone theme I use and depends on things you cannot see on your computer. So it is not viable to use the computer to select the right colour. Once I found a good colour I could export the shortcuts and edit the json to ament the colours for the other shortcuts (workaround for the subproblem).

**Comment by Waboodoo** [comment]
I agree that the current UX is suboptimal. It's a very recent addition that icons can be colored at all, so this has so far basically been an experiment to see if it is useful at all. My plan is to eventually combine the selection of the icon and its color into one UI, so that you can directly see what the icon looks like in a specific color and change it quickly.
I like your idea of showing the color's hexcode and allowing to copy/input one, I might add that. I was also thinking to make the color picker remember the previously used color, so that it's easier to apply the same color to many different shortcuts in succession. I'll think about this a bit, I'm not yet commiting to a particular solution.

**Comment by googol42** [comment]
>  I was also thinking to make the color picker remember the previously used color, so that it's easier to apply the same color to many different shortcuts in succession.

That sounds very reasonable!

Thanks a lot for all your effort

**Comment by googol42** [comment]
> It's a very recent addition that icons can be colored at all, so this has so far basically been an experiment to see if it is useful at all.

I found it useful. Less scrolling to find the icon you are searching and at the same time adding more possibilities.

**Comment by Waboodoo** [comment]
As of 2.23.0 (which has been released) this issue has been partially addressed:
- The color picker dialog now allows to pick a color via its RGB hex code, which can also be copied and pasted
- The color picker remembers the previously used color and uses it as the initially selected color

**Comment by Waboodoo** [comment]
As of version 3.4.0, the icon picker will now show the previously selected icon at the top, which should make it easier to re-select the same icon to quickly change its color. With that, I'd say this feature request is sufficiently covered and I will therefore close this ticket.
