### ISSUE TITLE
Application cannot read data from clipboard

### ISSUE THREAD

**Issue by LinYF0** [Waboodoo/HTTP-Shortcuts#294]
Application cannot read data from clipboard, application version 2.24.0, system is Android 10, Oneplus 8 phone. If you have time, I hope you can help fix it. I am Chinese, please forgive me for my poor language.

**Comment by LinYF0** [comment]
执行失败，状态码 422 (Unprocessable Entity)

{"detail":[{"loc":["body"],"msg":"field required","type":"value_error.missing"}]}

**Comment by LinYF0** [comment]
The POST data is the contents of my clipboard

**Comment by LinYF0** [comment]
It has been solved by using the Riru Clipboard Whitelist module of magisk. Thank you for your application

**Comment by Waboodoo** [comment]
Glad to hear it's resolved. I saw the stacktrace and it looked very fishy. I don't think there's much I could about this from the application side.
