### ISSUE TITLE
Can't remove quick settings tile

### ISSUE THREAD

**Issue by mattlaverick** [Waboodoo/HTTP-Shortcuts#295]
I added a quick settings tile shortcut via "3 dots > settings > quick settings tile" but can't seem to remove it. If I press the same setting I receive a toast notification saying that a tile has been added.

Version 2.24.0 on Pixel 6 Pro, Android 13

**Comment by Waboodoo** [comment]
Unfortunately, Android currently doesn't offer a way for an app to remove its own quick settings tile, so instead you have to do it manually via the Android system.

Pull the quick settings bar all the way down and look for the little pen icon (likely at the bottom right).

![image](https://user-images.githubusercontent.com/2445563/193268630-8d74bb23-a461-40fd-9258-2abb226a85e1.png)

With that you can edit all the quick settings tiles that you have active by dragging them around. To remove on, drag it all the way to the bottom.
