### ISSUE TITLE
enable script send http request and read response.

### ISSUE THREAD

**Issue by Arvintian** [Waboodoo/HTTP-Shortcuts#297]
**Is your feature request related to a problem? Please describe.**
I want use http-shortcuts to controller my devops paltform, many shortcuts run shoud init some data, to fill button options like multiple-choice or check some state. I want write script to do this work, but i can't make a http request and wait the response.

**Describe the solution you'd like**
In my case, i think http-shortcuts like a fire-button or flexible ui (User Interaction function is useful), in the script i can prepare many props or do abort the action. Use HTTP-Shortcuts, i don't have to write a web ui to do the same thing. 

**Describe alternatives you've considered**
For example:

***Variable:***
Token: "xxx" // static text
PodIP: "yyy" // update by js
***Run:***
token = getVariable("Token")
let rsp = sendHTTP("get","url",headers={"token":token},timeout=5) // http-shortcuts's function sendHTTP
...//parse rsp
let podList = [....]
let selectedPod = showSelection(podList);
setVariable("PodIP",selectedPod)
...

**Comment by Waboodoo** [comment]
Thanks for your suggestion.
I am currently working on a feature that would cover this usecase, by allowing to execute another shortcut via Scripting and retrieving its result. This will be part of version 2.25.0

**Comment by Waboodoo** [comment]
This feature is now available as part of version 2.25.0, which is being released now. See https://http-shortcuts.rmy.ch/scripting#execute-shortcut for information on how to nest HTTP requests.
