### ISSUE TITLE
How to Translate‽

### ISSUE THREAD

**Issue by Vanillma** [Waboodoo/HTTP-Shortcuts#301]
Finally, after a few days of searching on GitHub and testing different http projects... I came to your project... Your Android application is unique... light and beautiful... I am very happy that you have a live and active project.

I installed your unique app and I suggest it to all my friends... I also gave you a golden github star 🌟 so that you can advance the development path with more power... the app's ui and ux are very good. It's nice and fast and light...I hope you can convert it to SPA later...Thanks for this project, it made my job infinitely easier today.

Looking forward to new updates :)

(also i can translate to persian, How should I start?)

**Comment by Waboodoo** [comment]
Thanks for the very positive feedback.
If you want to help with translations you can join the translation project by signing up here: https://poeditor.com/join/project/8tHhwOTzVZ

> I hope you can convert it to SPA later

What do you mean by SPA here?

**Comment by Vanillma** [comment]
> Thanks for the very positive feedback. If you want to help with translations you can join the translation project by signing up here: https://poeditor.com/join/project/8tHhwOTzVZ
> 
> > I hope you can convert it to SPA later
> 
> What do you mean by SPA here?

Single Page Application...🎉

**Comment by Vanillma** [comment]
> Thanks for the very positive feedback. If you want to help with translations you can join the translation project by signing up here: https://poeditor.com/join/project/8tHhwOTzVZ
> 
> > I hope you can convert it to SPA later
> 
> What do you mean by SPA here?

I noticed that I can't send requests to localhost(127.0.0.1:port)...why??...is this a fix??

**Comment by Waboodoo** [comment]
You should be able to make requests to localhost (assuming there's actually a service running there). If that doesn't work you'll need to give me more information so that I can investigate the issue.
