### ISSUE TITLE
[BUG] Remote editing doesn't pull everything

### ISSUE THREAD

**Issue by mpiffault** [Waboodoo/HTTP-Shortcuts#303]
**Steps To Reproduce**
1. Push current configuration to server
2. Connect to remote interface with provided id
3. In remote edition interface, add a new shortcut with some scripting
4. Add a custom Authorization header based on an existing global variable
5. Add a function in global scripting field
6. Save the modifications
7. Pull modifications from the app

**Expected behavior**
Everything in the app is updated according to what has been done in remote editing.

**Actual behavior**
The custom header and the global scripting modification are not pulled. Other modifications (new shortcut with custom scripting) are. 

**Context :**
 - Android OS Version: 11
 - App Version 2.24.0
 - Remote editing used in Firefox 105.0.2 (didn't try chrome)

**Comment by mpiffault** [comment]
I tried to reproduce the header issue, but no chance. This is probably a mistake on my part.

Also, in the diff of the global scripting fix, I suggested that it could be replaced by the new content even if it's empty as it could be a choice from the user. What do you think about it ?

**Comment by Waboodoo** [comment]
You are right, that's a case I had not considered. I will adjust it.

**Comment by mpiffault** [comment]
Thanks ! And by the way, thank you very much for this piece of software, it's super powerful and very promising.

**Comment by Waboodoo** [comment]
This bug should now be fixed as part of version 2.25.0, which is being released now.
