### ISSUE TITLE
[BUG] F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Waboodoo/HTTP-Shortcuts#305]
https://monitor.f-droid.org/builds/log/ch.rmy.android.http_shortcuts/1102250003#site-footer

Could you please take a look?

By the way, F-Droid support autoupdate for multiple abi now. So we can split the abi if it can reduce the apk size.

Thanks!

**Comment by Waboodoo** [comment]
Oh, my bad. I forgot to test for this one. It's now fixed and will be included in version 2.25.1, which I'm planning to release in the next 2 days.

**Comment by linsui** [comment]
Thanks!

**Comment by Waboodoo** [comment]
This should now be resolved with the latest release

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/ch.rmy.android.http_shortcuts/1102250100#site-footer It's fixed. Thanks!
