### ISSUE TITLE
[BUG] Desktop Widgets not work (partly)

### ISSUE THREAD

**Issue by mikepiko** [Waboodoo/HTTP-Shortcuts#306]
I use the current version of http shortcut with Android 13 on a Samsung S22.
I added 3 Widgets to my startscreen
1 for my Garage Door to open
1 to close my Front Door
1 to open my Front Door

The Icons i set within http Shortcut are correctly assigned.

The Problem is that only the First item in my http shortcut App is triggered, regardless of which icon i use.
Within the App everything works as expected, but the Widgets are only triggering the first URL.

As it´s only since a few Days i won´t say it´s an Android 13 issue, i think it´s the last Update.

**Context (please complete the following information):**
 - Android OS Version: 13
 - App Version 2.25.0
 
![shortcut1](https://user-images.githubusercontent.com/38277702/201692970-a8d7d8c7-e1e1-48c2-a1fd-f373ac14210b.jpeg)
![shortcut2](https://user-images.githubusercontent.com/38277702/201692972-a7251882-82e6-4381-bc8b-6355210c2f08.jpeg)

https://user-images.githubusercontent.com/38277702/201692997-ba36b469-03b0-4d8b-9674-a62d14c399bc.mp4

**Comment by mikepiko** [comment]
Already deleted the Widgets and created new ones ... doesn´t help

**Comment by mikepiko** [comment]
didn´t wanted to close it ...

**Comment by Waboodoo** [comment]
Thanks for the detailed bug report. I was able to identify and fix the issue, it was indeed a newly introduced bug in version 2.25.0. I will release the fix as part of version 2.25.1 in the next 2 days.

**Comment by Waboodoo** [comment]
Version 2.25.1 is now released and can be installed from the Play Store
