### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by xmha97** [Waboodoo/HTTP-Shortcuts#311]
Please use material you FAB (Floating Action Button)

**Comment by Waboodoo** [comment]
Is there any particular reason why you think specifically the FAB should be updated to Material You, rather than the whole app?

**Comment by xmha97** [comment]
> Is there any particular reason why you think specifically the FAB should be updated to Material You, rather than the whole app?

Because I thought this change might be time consuming.

If you are able to redesign the whole app with Material You that would be awesome. 🤗

**Comment by Waboodoo** [comment]
I'd like to avoid having a mixture of different Material versions. I'll probably try to migrate the whole app at some point, combined with a migration to Compose. But as that is mostly just cosmetics and requires quite some effort, I'll treat this as low priority for now.

**Comment by xmha97** [comment]
Ok, thanks.

**Comment by Waboodoo** [comment]
The app now uses Material 3, as part of version 3.0.0

**Comment by xmha97** [comment]
Thanks 🙏
