### ISSUE TITLE
In-app SOCKS5 proxy

### ISSUE THREAD

**Issue by xmha97** [Waboodoo/HTTP-Shortcuts#312]
Hi, I want to use Telegram bot API but Telegram blocked in my country.

Please add in-app proxy like Telegram app:

![Screenshot_2022-11-20-19-04-05-042_org.telegram.messenger.web.jpg](https://user-images.githubusercontent.com/23485114/202911014-8fa56f24-3dc5-49ae-acb2-9a535af339a3.jpg)

**Comment by Waboodoo** [comment]
Would you happen to have a proxy server that I can use for testing this? I would have to first figure out how to set one up, as I'm not familiar with SOCKS5 at all.

**Comment by Waboodoo** [comment]
Version 2.26.0 is now available for beta testing, which includes the support for SOCKS proxies. You can join the beta program here: https://play.google.com/apps/testing/ch.rmy.android.http_shortcuts

**Comment by xmha97** [comment]
Thanks 🙏

![Screenshot_2022-12-01-12-39-32-721_ch.rmy.android.http_shortcuts.jpg](https://user-images.githubusercontent.com/23485114/205012308-901e7d37-6fec-4269-8657-07e19735ac0d.jpg)

**Comment by Waboodoo** [comment]
This feature is now released in version 2.26.0
