### ISSUE TITLE
Importing omits HTTP Request Headers via legacy JSON format

### ISSUE THREAD

**Issue by tdussmann** [Waboodoo/HTTP-Shortcuts#313]
Hi and thanks for creating this absolutely awesome tool first of all! 

I've been using it for this and that over the years but recently wanted to prototype calling about 100 slightly different actions. 

While doing this I encountered what could be a bug with the importing of HTTP Request Headers, as they didn't get set correctly
* by using the Remote Editor in the Browser and trying to apply the changes (new shortcuts) everything gets created but the request headers were missing. Note: I created one shortcut by hand and then duplicated it each time, only changing the POST payload
* due to the number of individual shortcuts I've then resorted to exporting to legacy-JSON format, generating the individual slightly varying shortcuts and then importing the legacy-JSON format again. Again, the HTTP Request Header is missing in each of the shortcuts. I've made sure to change the UUID for each shortcut as well as its headers entry. 

Could you tell me if I'm missing something or doing something wrong? Since the JSON format is probably not really meant to be user-generated for batch-editing of shortcuts, its not really documented as far as I could see, so it could very well also be PEBCAK.

Example Shortcut JSON in legacy format:

`{
          "bodyContent": "{\"sound\": \"sound\", \"volume\": 30}",
          "contentType": "application/json",
          "headers": [
            {
              "id": "824c7762-7e67-4216-8736-1b409e583010",
              "key": "Ocp-Apim-Subscription-Key",
              "value": "omitted"
            }
          ],
          "iconName": "flat_color_lightbulb",
          "id": "10e243a9-e36b-43eb-a093-76187a33d35b",
          "method": "POST",
          "name": "Name",
          "responseHandling": {
            "successOutput": "none",
            "uiType": "toast"
          },
          "url": "https://foo/bar"
        }`

Thanks

**Comment by Waboodoo** [comment]
Hello and thanks for the positive feedback.

Your JSON looks valid. I tried to import this shortcut and for me it worked, including the headers, so I'm not sure what's going on. Could you perhaps send me the whole file?

Regarding the JSON format:
- It's not per se meant for being user-generated but I intentionally made it "hackable", meaning I chose a human-readable format where it's possible to guess how it works. So what you're doing is intended, just not documented because it's only few people who go this route.
- In case you want to avoid using the legacy format and use the regular format: It's basically just the JSON file packaged into a zip archive, with optional files such as custom icons or certificates packaged in.

**Comment by tdussmann** [comment]
Thank you for the quick feedback! It was indeed what I needed, the confirmation that what I am attempting should indeed work and I just must have missed some mistake. Indeed the reason existed between chair and keyboard. 

The confusion happened since the first attempt did include duplicate UUIDs for the nested `headers` entry, as I forgot about the difference between copy vs. deepcopy in my python script that generated the 100+ shortcuts. Therefore in the first import all the header entries were omitted. The second import indeed added all shortcuts correctly, however I had always assumed that an import action would actually *replace* all existing shortcuts. 

Previously I was only ever doing full exports/full imports e.g. to transfer a few shortcuts from one android device to another, so I was not aware that they can be additive. Due to my script setting random UUIDs for each new run I had multiple sets of the same shortcuts in the app and was looking at the old ones, still without the request headers in place due to my previous error. 

So thank you for your help! It works flawlessly now. The format may be pretty self-explanatory indeed, I just made two errors in succession and incorrectly assumed there was an issue with the importing of headers. I can not explain why the adding via browser editor with the duplication had shown a similar issue at first, but there it worked without issue on my second attempt, so I think that can also not be reproduced. 

I would therefore close this. Thank you for your help!

**Comment by Waboodoo** [comment]
Glad to hear you figured it out. I have added a bit more validation logic to the app now, to make sure that there will be a meaningful error message when an import contains duplicate IDs anywhere.

**Comment by tdussmann** [comment]
That's awesome! Thanks again for your help and the amazing effort behind HTTP Shortcuts. Very glad I found your app way back then!
