### ISSUE TITLE
Requesting the HMAC Action String "message" variable to change to a ByteArray.

### ISSUE THREAD

**Issue by ngbk1993** [Waboodoo/HTTP-Shortcuts#314]
**Is your feature request related to a problem? Please describe.**
Yes. I was trying to do a HMAC SHA 1 hashing  using the javascript but unfortunately the output is different from what I compared with python, it is possibly due to when I was passing in as ByteArray, and it is being converted to String in the HMAC Action function.

**Describe the solution you'd like**
Referring to the https://github.com/Waboodoo/HTTP-Shortcuts/blob/develop/HTTPShortcuts/app/src/main/kotlin/ch/rmy/android/http_shortcuts/scripting/actions/types/HmacAction.kt

Change the
private val message: String,
to
private val message: ByteArray,

afterall the message is being converted to a ByteArray
message.toByteArray()) at line 20

**Describe alternatives you've considered**
N/A

**Additional context**
Below are the 3 experiments I tried at both the HTTP Request App and python

1) At Python
key = b'THiIsATesting'
msg = b'\x00\x00\x00\x00\x03Q\x04+'

binascii.hexlify(msg)
>>> b'000000000351042b'

binascii.hexlify(hmac.new(key, msg, hashlib.sha1).digest())
>>>b'45be3f509164744c61568f3216a3cb0278c8d794'

2) At HTTP Request Shortcuts App
const key = 'THiIsATesting';
const msg = '000000000351042b';
const myHMAC = hmac('SHA-1', key, msg);
const myHMACasHex = toHexString(myHMAC);
showDialog(myHMACasHex);

And the Result I get was (Which is incorrect)
4c067244427121c5ab11ee4d5b9fde9342d58298

3) If i Changed the python msg
key = b'THiIsATesting'
msg = b'000000000351042b'

binascii.hexlify(msg)
>>>b'30303030303030303033353130343262'

binascii.hexlify(hmac.new(key, msg, hashlib.sha1).digest())
>>>b'4c067244427121c5ab11ee4d5b9fde9342d58298'

**Comment by ngbk1993** [comment]
Hi @Waboodoo Thanks for prompt action to address the feature request. This will definitely help me for implementing the TOTP for the IoT devices.

**Comment by Waboodoo** [comment]
This change is now released as part of version 2.26.0.
Let me know here in case something still doesn't work.

**Comment by ngbk1993** [comment]
Thanks @Waboodoo 
I have implemented the TOTP code here and tested working with google authenticator.
https://github.com/ngbk1993/safer_mqtt_protocol/blob/master/JavaScript/TOTP.js
