### ISSUE TITLE
Creating Shortcut Apps on Head Unit

### ISSUE THREAD

**Issue by ukiews** [Waboodoo/HTTP-Shortcuts#318]
I have Teyes head unit. Similar to Joying. As with most car head units, the launcher app takes over the Home Screen and does not allow creating shortcuts. Is it possible to have the app create an app shortcut directly in the apps menu?

maybe HTTP-shortcuts could create simple apk files to run like a normal app.

**Comment by Waboodoo** [comment]
I see your problem. Currently this is not possible in the app.
I suppose, as you suggest, the simplest solution would be to just create a separate APK which then just invokes a shortcut when opened. This comes with a bit of overhead though (bootstrapping a new app, figuring out how to publish it, selecting which shortcut should be used, etc.), so I can't make any promises that I'll get around to building this. Would be a great opportunity for contributions, maybe I can find someone willing to look into this before I do it myself eventually.
Anyway, I'll keep this issue open for now, until I have some solution for it.

**Comment by ukiews** [comment]
Great! Hope this could happen. Thank you in advance.

**Comment by Waboodoo** [comment]
Actually, I might have found a better solution, though I don't know if it will work for your use case.
For the upcoming release (version 2.27.0), I'm including a new feature which allows to enable a secondary app. This app will trigger a shortcut when opened.
You'll be able to configure this by going to the "Trigger & Execution Settings" screen when editing a shortcut.

**Comment by ukiews** [comment]
If there will an actual secondary app in the app list, this should work.
However, will not this secondary app only be limited to triggering one
shortcut?

**Comment by Waboodoo** [comment]
Yes, there will be an actual second app in the app list.
If you enable this option for more than one of your shortcuts then you clicking the secondary app will show a selection dialog with all the shortcuts for which this is enabled, similar to how it works for the Quick Settings Tile or the "Share Into" feature.

**Comment by ukiews** [comment]
Would it be possible to designate an icon for the secondary app?
In my situation, all I am trying to create is a toggle switch to open/close the garage. 


see here:
https://photos.app.goo.gl/iaPhDPbyu4ZugFyf9

**Comment by Waboodoo** [comment]
Version 2.27.0 is now released. Can you give it a try and see if it solves the issue for you?
You'll find instructions for enabling the secondary launcher app on this page: https://http-shortcuts.rmy.ch/advanced

> Would it be possible to designate an icon for the secondary app?

Unfortunately there is a technical limitation here. The icon and name of the secondary app needs to be statically defined by the app and cannot be changed dynamically.

**Comment by ukiews** [comment]
Thank you. It’s not ideal, but it does work better than the default app, in that there is only a popup, and the secondary triggering app does not take over the whole screen to trigger a select shortcut.

**Comment by Waboodoo** [comment]
Glad to hear it works 👍🏻 . I'll close this then.
