### ISSUE TITLE
[BUG] Fullscreen Window doesn't show JSON properly

### ISSUE THREAD

**Issue by vasanthtt** [Waboodoo/HTTP-Shortcuts#325]
**Steps To Reproduce**
1. Call a API returns JSON body
2. Goto Response Handling and set Display Type to **Fullscreen Window**
3. Run the shortcut and JSON contains "=" symbol encoded as \u003d
4. But When the Display Type is **Dialogue Windows** its shows without encoding. works properlyy.

**Expected behavior**
Value inside should not automatically encode the string inside string array

**Actual behavior**
Encodes

**Screenshots**
![image](https://user-images.githubusercontent.com/724399/214001544-a7f02bd3-27fa-4008-92da-23f3acdfbcc6.png)

**Context (please complete the following information):**
 - Android OS Version: 12
 - App Version 2.29.0

**Comment by Waboodoo** [comment]
Thanks for the bug report. Looks like GSON (the library I'm using to pretty print the JSON) escapes these characters by default. I have now disabled this option, so this bug will be fixed with the next release (2.30.0)

**Comment by Waboodoo** [comment]
This fix is now released as part of version 2.30.0.
