### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by edwyn-amador** [Waboodoo/HTTP-Shortcuts#326]
The base64Encode function is appending a "/n" character, so basically if I do this:

![image](https://user-images.githubusercontent.com/36249854/214829704-668d7b2a-1768-4ff5-81cd-80bee6cd7a44.png)

It will transform it to this:

aGVsbG8=/n

**Comment by Waboodoo** [comment]
Thanks. This will be fixed for the next release (2.30.0)

**Comment by edwyn-amador** [comment]
> This fix is now released as part of version 2.30.0.

Great, Thanks! :)
