### ISSUE TITLE
instaj

### ISSUE THREAD

**Issue by kevinyuvietnam** [Waboodoo/HTTP-Shortcuts#329]
{
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, v-data, x-access-token, X-Forwarded-*",
  "access-control-allow-methods": "GET, POST, OPTIONS, PUT, PATCH, DELETE",
  "access-control-allow-origin": "*",
  "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
  "cf-cache-status": "DYNAMIC",
  "cf-ray": "797617ed5f970223-SIN",
  "content-type": "application/json; charset=utf-8",
  "date": "Fri, 10 Feb 2023 16:06:44 GMT",
  "etag": "W/\"83d-Jv2H20bujbu+DDE8+UMlKO7a4gM\"",
  "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
  "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=%2Fl0UkVwiWdd6v6UJr6Xhsh3AN5GfxX9NVA4kIriV%2FE1%2FOjshgH8E95c6xrMw1NpffiDCnBQSa3QzbbNZlZ660e4fvKttLl6uBj3YuGWq34cWgIG3Y%2FAAfpA0RECovVcXjvY%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
  "server": "RapidAPI-1.2.8",
  "vary": "Accept-Encoding",
  "x-powered-by": "Express",
  "x-rapidapi-region": "AWS - ap-southeast-1",
  "x-rapidapi-version": "1.2.8",
  "x-ratelimit-request-limit": "150",
  "x-ratelimit-request-remaining": "139",
  "x-ratelimit-request-reset": "1930731"
}

**Comment by Waboodoo** [comment]
@kevinyuvietnam What is this about?
