### ISSUE TITLE
[BUG] 中文翻译存在错误

### ISSUE THREAD

**Issue by CafeBabe202** [Waboodoo/HTTP-Shortcuts#331]
**描述**
在界面语言设置成中文的情况下，在添加快捷方式时，将 **request/request parms** 翻译成了 **响应体/响应参数**，实际应该为 **请求体/请求参数**

**版本**
2.29.0

**截图**

![Screenshot_20230215-103522_HTTP_快捷方式](https://user-images.githubusercontent.com/53887690/218913637-7fc27273-8bed-48bf-91e7-2a2959df9176.png)

![Screenshot_20230215-103532_HTTP_快捷方式](https://user-images.githubusercontent.com/53887690/218913646-14ad7e76-b9bb-48ea-be4e-99a216e91c72.png)

**Comment by Waboodoo** [comment]
Thanks for reporting this. It will be fixed for the next release.
If you find other issues with the translations, feel free to join the translation project and correct them here: https://poeditor.com/join/project/8tHhwOTzVZ
