### ISSUE TITLE
var from clipboard and write repsonse to clipboard

### ISSUE THREAD

**Issue by m2acgi** [Waboodoo/HTTP-Shortcuts#338]
I'm using the HTTP-Shortcuts with the Piping server (https://github.com/nwtgck/piping-server), to send text to each other like clipbaord sync APP. Please add the two options as follows:

![20230315123433](https://user-images.githubusercontent.com/34497122/225212196-18301ec1-4c51-48bb-ba0b-6e62772aab01.jpg)
![20230315123437](https://user-images.githubusercontent.com/34497122/225212209-4ac5a097-0187-419c-880c-4daa2f31b0b1.jpg)

**Comment by m2acgi** [comment]
solved by Scriping.

**Comment by Waboodoo** [comment]
Glad to hear you found a solution. There actually already is a variable type that reads from the clipboard. You just need to scroll further down in the list when creating the variable.
