### ISSUE TITLE
[BUG] response unreadable code

### ISSUE THREAD

**Issue by stonereese** [Waboodoo/HTTP-Shortcuts#341]
**Steps To Reproduce**
1. excute shortcut
2. get response

**Expected behavior**
When the response body uses Charset as GB2312, the response contains Chinese, whether it is using a display response, or using the script showDialog, the result is garbled, unreadable code.

**Actual behavior**
When the response body uses Charset as GB2312, the response contains Chinese, whether it is using a display response, or using the script showDialog, the result is garbled, unreadable code.

**Screenshots**
![Screenshot_2023-04-21-10-11-41-439_ch rmy android http_shortcuts-edit](https://user-images.githubusercontent.com/31586810/233524515-349064bf-0b0d-43cc-8f55-a451fe4dae4c.jpg)
blem.

**Context (please complete the following information):**
 - Android OS Version: 13.0
 - App Version: 2.31.0

**Comment by Waboodoo** [comment]
Thanks for the bug report. Would you happen to have a URL with which I can test this? Also, did you verify that the Content-Type header of the response declares the charset correctly?

**Comment by stonereese** [comment]
I'm sorry, but I am unable to provide the original URL at this time. Following your suggestion, I have attached a corresponding screenshot of the HTTP response after sending an HTTP request via the shortcut, which displays charset=gb2312 and is consistent with the actual situation. If I come across any publicly testable URLs with similar issues in the future, I will be sure to submit them to you for further analysis. Thank you for your development work, as it has been of great convenience to me.
![1683188215258](https://user-images.githubusercontent.com/31586810/236151630-afd9bda5-dcb6-4a44-98b4-690c54ff7e8f.jpg)

**Comment by stonereese** [comment]
> Thanks for the bug report. Would you happen to have a URL with which I can test this? Also, did you verify that the Content-Type header of the response declares the charset correctly?

I'm sorry, but I am unable to provide the original URL at this time. Following your suggestion, I have attached a corresponding screenshot of the HTTP response after sending an HTTP request via the shortcut, which displays charset=gb2312 and is consistent with the actual situation. If I come across any publicly testable URLs with similar issues in the future, I will be sure to submit them to you for further analysis. Thank you for your development work, as it has been of great convenience to me.
![1683188215258](https://user-images.githubusercontent.com/31586810/236151782-81ba3587-a7cf-4019-a6e4-47700ffd6683.jpg)

**Comment by Waboodoo** [comment]
Alright, thanks. I was able to fix the issue (I think) in the meantime. The fix will be part of the next release. Since I'm working on some other big internal changes, it might take a while before that is released though.

**Comment by stonereese** [comment]
> Alright, thanks. I was able to fix the issue (I think) in the meantime. The fix will be part of the next release. Since I'm working on some other big internal changes, it might take a while before that is released though.

I found a charset=gbk page for you to test, [Test URL](http://bbs.runbible.cn/forum.php)

**Comment by Waboodoo** [comment]
This bug should now be fixed, as part of the 3.0.0 release.
