### ISSUE TITLE
Download directly into the destination directory

### ISSUE THREAD

**Issue by opk12** [Waboodoo/HTTP-Shortcuts#344]
**Is your feature request related to a problem? Please describe.**
I download large files on the SD card, with the new feature introduced in version 2.31.0. As mentioned in from 323 ([comment](https://github.com/Waboodoo/HTTP-Shortcuts/issues/323#issuecomment-1528814639)), the HTTP response body is stored in a temporary location in the internal memory, then it is copied to the destination directory. Saving directly to the designated directory would avoid a copy and be a bit faster. It would also help when the internal memory has little free space.

**Comment by Waboodoo** [comment]
This is now implemented and available as part of the 3.0.0 release.
