### ISSUE TITLE
Add shortcut icon in share picker 

### ISSUE THREAD

**Issue by ChrisCinelli** [Waboodoo/HTTP-Shortcuts#345]
**Is your feature request related to a problem? Please describe.**
If I have more than one shortcut that ai want to put in the share picker there is an extra step. It is also annoying that I need to share with "HTTP shortcut".

It also took me a little bit to figure out how to be able to get the shared text in the JS.

**Describe the solution you'd like**
Each shortcut should have an option "show in the share picker"  that if it is checked, the app should add the shortcut with its own icon in the share picker.

**Describe alternatives you've considered**
None

**Additional context**
I REALLY love this app! Thank you for creating it!

**Comment by Waboodoo** [comment]
Thanks for the positive feedback.
I agree with the usefulness of your feature suggestion. I'm not yet sure though if it is technically possible. There's some technical limitations on how Android allows apps to interact with the sahre sheet. I'll look into it when I find the time.

**Comment by steff75** [comment]
Hi, i think the feature direct-share is meant:
[https://developer.android.com/training/sharing/direct-share-targets](https://developer.android.com/training/sharing/direct-share-targets)
[https://developer.android.com/codelabs/android-direct-share#0](https://developer.android.com/codelabs/android-direct-share#0)

In AutoShare Tasker plugin this is also used for such purposes.
Thanks for the great app!

**Comment by ChrisCinelli** [comment]
Did you leave ok into this? One of the advantages of this app is to quickly share with the app with one tap. Currently I can only have one script.

**Comment by Waboodoo** [comment]
@ChrisCinelli I don't think I understand your last comment. Could you elaborate?

**Comment by ChrisCinelli** [comment]
I mean that having a direct share target for each script let you share quicker when you have more than ine script. See @steff75 comment.

**Comment by Waboodoo** [comment]
I'm looking into this now. I plan to have a working implementation in the next version, which I'm hoping to release within a few weeks.

**Comment by Waboodoo** [comment]
Version 3.5.0 is now being released. It includes a feature which lets you turn shortcuts into Direct Share targets. You'll find the checkbox for this in the shortcut's "Trigger & Execution Settings" screen when editing it.
