### ISSUE TITLE
Improve response handling

### ISSUE THREAD

**Issue by Waboodoo** [Waboodoo/HTTP-Shortcuts#35]
Add additional options for how to process the request responses:
- Save to file
- Syntax highlighting
- Open in appropriate app (e.g. gallery for images)

**Comment by eadmaster** [comment]
another improvement i'd like to suggest is parsing plaintext responses via JS code (like the [Http Widget app](https://play.google.com/store/apps/details?id=com.axgs.httpwidget))

**Comment by flddr** [comment]
I hope the additional options will come :)

Please add an loader while waiting for request. I curled a pdf and thought it would not do that, seems to stop work, but than it pops up - btw: while showing response in dialog

**Comment by Waboodoo** [comment]
@eadmaster This functionality is now available with today's 1.24 release
