### ISSUE TITLE
[BUG] I cannot enter more than 3 variables.

### ISSUE THREAD

**Issue by ORICO-SUN** [Waboodoo/HTTP-Shortcuts#352]
Thank you for updating to version 3.
I have a problem with a variable and would like to report it.

**Steps To Reproduce**
1. Launch GET request with 3 or more variables in the URL (It was the same for any type of variable.)
2. Set the second variable and try to transition to the third variable screen.
3. The loading screen is displayed endlessly and does not transition to the third variable setting screen.

**Expected behavior**
I want it to move to the third variable setting screen.

**Screenshots**
Please see the video on youtube.
https://youtu.be/NZdwWTWUV-g

**Context (please complete the following information):**
 - Galaxy Note10+
 - Android OS Version: 12
 - App Version : 3.0.0

**Comment by Waboodoo** [comment]
This should now be fixed as part of the 3.0.1 release.
