### ISSUE TITLE
Application weight reduction

### ISSUE THREAD

**Issue by HFPasfho** [Waboodoo/HTTP-Shortcuts#361]
**Is your feature request related to a problem? Please describe.**
A fresh install of this app uses around 100-111 MB of storage. That's a lot even by the standards of an Android app. I assume it's due to all these shortcut icons available in app.

**Describe the solution you'd like**
The solution could be not to build them into the application. Since this app already requires internet connection the screen where the user selects an icon could display a web page with available icons (with lazy loading) and only the chosen icon would be downloaded and stored on a device. Of course it should be deleted when it is no longer associated with any shortcut. This way the app's footprint could by reduced significantly. Additionally you could add a search option on this web page to filter icons by names/tags (e.g. light bulb can represent a light bulb or an idea or ...).

**Describe alternatives you've considered**
A simpler but less elegant solution would be to release 2 app versions. One with icons and one without.

**Comment by Waboodoo** [comment]
I agree with your concern that the app is quite bulky. I'm keeping a close eye on its size and I'm trying to make it smaller where I can. However, your assumption that the built-in icons are the main contributor to its size is incorrect. A very rough, high-level breakdown of the app's main size contributors are as follows:
- ~35% comes from the JavaScript engine, which is required for the Scripting feature
- ~25% comes from the app's code itself (already reduced in size as much as possible)
- ~20% comes from the database library (Realm)
- ~5% comes from the TLS support library (Conscrypt)
- ~7% comes from the bundled-in assets, which includes the icons but also many other things like the translations, app icons, animations, ...

I've already considered the idea of removing the icons from the app and loading them lazily, but I've decided against it for the following reasons:
- It would barely have an impact on the size
- It would increase the complexity of how the icons are handled in the app
- It would introduce an external dependency (I have to host and maintain these icons somewhere)
- The icon picker would not work when there is no internet connection (there are users who use the app in situations where that is the case)
- It would make the app less standalone
- It would introduce a potential privacy concern, as the app would need to fetch stuff from the internet that would open the door for me to track users. I don't want to do that and I don't want users to think I might do that.

Coming back to your original concern though: 100-111 MB sounds like a lot, you should be able to go lower than that. With every version I publish, I publish different variants, one for each processor architecture, plus one universal APK. The architecture-specific ones are much smaller, as they only contain the library code that is really needed, while the universal APK contains everything and is therefore quite large. If you install the app from the Play Store, you will automatically get the right one for your device. If you install it from an APK, please make sure to pick the right one for your device. If you get it from F-Droid, then I'm not sure how it's done, but I know they also have a feature for this now. That should give you a significant size reduction.

Beyond that, I'm afraid I currently don't see much potential for reducing the app's size without compromising on existing features. If it becomes more of a concern for users I will re-evaluate, but currently I don't deem the situation dire enough to invest effort into it.

**Comment by HFPasfho** [comment]
Thank you for clarification. I got this app from F-Droid so if they have such feature it doesn't work (at least not for this app).

**Comment by Waboodoo** [comment]
F-Droid has only recently added support for this, so it might be that it's not fully implememted yet, or you might have to re-install the app. On the F-Droid website you can choose which variant you want:

![Screenshot_20230619_115143_Chrome](https://github.com/Waboodoo/HTTP-Shortcuts/assets/2445563/55946b76-e6f8-4b62-be77-9ea9d7d3062c)
