### ISSUE TITLE
[BUG] Message about data saver and/or battery saver keeps showing up even if user checks don't show it again checkbox

### ISSUE THREAD

**Issue by HFPasfho** [Waboodoo/HTTP-Shortcuts#363]
**Steps To Reproduce**
1. Enable data/battery saver mode
2. Open the app
3. The message is displayed
4. Click OK (don't show it again checkbox is already selected)
5. Close the app
6. Open the app again

**Expected behavior**
The message shouldn't be displayed again

**Actual behavior**
The message is displayed again and again. It stops when we **uncheck the "don't show it again" checkbox**

**Context (please complete the following information):**
not relevant

**Comment by Waboodoo** [comment]
Thanks for the bug report. This will be fixed in the 3.0.2 release.
