### ISSUE TITLE
Automatically Pick file for HTTP Request

### ISSUE THREAD

**Issue by milouk** [Waboodoo/HTTP-Shortcuts#366]
**Is your feature request related to a problem? Please describe.**
My objective it to automatically push another application's export file to a self hosted server using HTTP Shortcuts. However, I would like this to be done automatically on a specific interval instead of having a picker pop up every time

**Describe the solution you'd like**
Ideally we could specify the location and name of the file to POST and HTTP Shortcuts would automatically fetch it instead of popping up the Picker

**Comment by milouk** [comment]
That would be similar to 

`curl -X POST -F "file=@/sdcard/exported_data.csv" https://your-server-url.com/upload-endpoint`. Basically cut out the picker part and specify a fixed path for a file @Waboodoo

**Comment by Waboodoo** [comment]
Yeah, that's the idea. Unfortunately, it's more tricky than that on Android, as an app can't just access files by path from the file system, unless it holds the permission for that, and I really really don't want to give that permission to the app. There are other ways, they're just more involved, but I will look into it when I find the time. It's high up on my priorities list for new features.

**Comment by Waboodoo** [comment]
As of version 3.4.0 (which is being released now), it is possible to select a specific file to be used for file uploads, without opening the file picker every time.
