### ISSUE TITLE
[BUG] Some shortcuts fails after 3.0.2 update

### ISSUE THREAD

**Issue by yml78** [Waboodoo/HTTP-Shortcuts#367]
**Steps To Reproduce**
Unconsistent behavior! Maybe something with multiple choice variables...

**Expected behavior**
Execute OK, as was still the case before 3.0 (even in 3.0.1, but not 100% sure).

**Actual behavior**
Several shortcuts use the same scripts, some still OK, others report "something went wrong" (in french for me).

**Screenshots**
None.

**Context (please complete the following information):**
 - Android OS Version: 10?
 - App Version 3.0.2
 - Any other context about the problem that you think is relevant

Tried to add some bubble prints in pre-exec and error handling scripts but nothing obvious+all shortcuts use copy/paste of same scripts.

Only significant difference between OK/KO shortcuts I could track (all using same pre exec scripts) is the use of a multiple choice variable in those that fails at execution (GET requests).

IMO there is an issue there as just trying to edit such variable now just hangs/restart the app!

Regards.

**Comment by Waboodoo** [comment]
Thanka for the bug report. This issue is already fixed in 3.1.0. Please try updating the app. If you're using F-Droid you might have to wait a few more days until the new version becomes available there.

**Comment by yml78** [comment]
Thanks to you, can confirm that's OK again this morning after F-Froid update was availlable!
