### ISSUE TITLE
[BUG] Selfsigned certificates do not work any longer 

### ISSUE THREAD

**Issue by laberlaib** [Waboodoo/HTTP-Shortcuts#371]
Hi,
my wife already uses 3.2 Googleplay and this version does not accept our selfsigned certificate any longer which used to work (and still does with F-Droid 3.1 on my phone).
In the changelog I saw, that something was changed in relation to handling selfsigned certificates.

The shortcut is configured not to validate the certificates but to trust in everything (Spanish: "Sin verification (confia en todos, oinseguro") and it also used to work with 3.1

**Expected behavior**
That the connection works and the command gets executed.

**Actual behavior**
nothing, error message, see screenshot from the logfile (in spanish, I can translate but it seems selfexplanatory).

**Screenshots**

<img src="https://user-images.githubusercontent.com/81492190/254498272-489bb6b4-dd4c-43c5-82e8-826560b886ad.jpg" width="200">

**Context (please complete the following information):**
 - Android OS Version: 12
 - App Version [3.2] Google Play

laberlaib

**Comment by Waboodoo** [comment]
Can you check whether there is another update available on Google Play? I pushed a new version yesterday (also 3.2.0), which fixes an issue with host verification. Yours is likely the same issue.

**Comment by laberlaib** [comment]
I hope you understand a little spanish:
<img src="https://github.com/Waboodoo/HTTP-Shortcuts/assets/81492190/31609101-58d1-4edf-af95-7a4c8bffb51e" width="200">

top!

**Comment by Waboodoo** [comment]
I understand just enough Spanish to read that, thanks for sharing 😄 👍🏻
