### ISSUE TITLE
[BUG] SSL Certificate error

### ISSUE THREAD

**Issue by sidey79** [Waboodoo/HTTP-Shortcuts#373]
**Steps To Reproduce**
1. Go to: Run a HTTPS request top a Site which uses mTLS.

**Expected behavior**

SSL Handshake can bei completed
Certificate ist trusted Like in chrome

**Actual behavior**
A clear and concise description of what actually happens.

```
Read error: ssl=0xb4000071c9a237d8: Failure in SSL library, usually a protocol error
error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE (/usr/local/google/home/
```

**Context (please complete the following information):**
 - Android OS Version: 13
 - App Version : 3.2.0
 - Any other context about the problem that you think is relevant

The Client cert ist a self signed cert and Server logs error, that no client cert is providef

The shortcuts worked a few days ago

**Comment by Waboodoo** [comment]
Thanks for the bug report, and sorry for the inconvenience. Looks like I broke client-certificate support completely in the latest update. I'll fix this for the next release.

**Comment by Waboodoo** [comment]
This should now work again in version 3.3.0

**Comment by sidey79** [comment]
Thanks for that quick response. I can confirm, that mTLS is working again.
