### ISSUE TITLE
Feature request: location variable without Google Play Services

### ISSUE THREAD

**Issue by tiptoptom** [Waboodoo/HTTP-Shortcuts#376]
I would find it nice when there would be an comparable function to #95 in the F-Droid version.

**Comment by Waboodoo** [comment]
I will adjust the [getLocation](https://http-shortcuts.rmy.ch/scripting#get-location) function to use some fallback options in case Play Services are not available. The result might be less accurate, less reliable or slower in some cases, but it should do the trick for most usecases. This will be part of the version 3.4.0.

**Comment by Waboodoo** [comment]
Version 3.4.0 is now being released and should become available on F-Droid within a few days. It contains support for the `getLocation` function without depending on Play Services.
