### ISSUE TITLE
Why v 3.6.0 is not tagged and released?

### ISSUE THREAD

**Issue by ChrisCinelli** [Waboodoo/HTTP-Shortcuts#388]
![1000029491](https://github.com/Waboodoo/HTTP-Shortcuts/assets/153101/e6b779f7-8454-4f70-9b19-7590bdc05b88)

**Comment by Waboodoo** [comment]
I didn't get around to it yet. The release and tagging process is mostly manual, and it was getting late yesterday and the build kept failing, so I decided to call it a day and create the tag later. I'll add it when I get around to it.

**Comment by Waboodoo** [comment]
Version 3.6.0 is now tagged
