### ISSUE TITLE
TCP sockets remain in CLOSE_WAIT

### ISSUE THREAD

**Issue by mguentner** [Waboodoo/HTTP-Shortcuts#4]
Hi,

it seems that the TCP sockets used for the HTTP connections are not properly closed.
After each request, the (new) socket remains in the "CLOSE_WAIT" state (check `netstat` in a terminal emulator).

If you have a small embedded device a few requests and therefore a few open TCP connections might result in a DOS for that device since it can not accept any more TCP connections (think 8 bit AVR).

The current solution is to force quit/kill the application in order to allow the garbage collector to close all the open connections.
For my device, the concurrent TCP connection limit is 3, which means after 3 requests using HTTP-Shortcuts I have to force quit the application to make more requests.

Steps to reproduce:

1. Make some requests
2. Check `netstat | grep CLOSE_WAIT`

**Comment by Waboodoo** [comment]
Thank you for reporting this issue. I will try to reproduce and fix this as soon as I can.

**Comment by mguentner** [comment]
Looks good (e787f7c8606282c71b47a13dbd904a4ce39cb6ac)! Thanks, @Waboodoo :muscle:
