### ISSUE TITLE
is there a way to import multiple choice selection option?

### ISSUE THREAD

**Issue by braboobssiere** [Waboodoo/HTTP-Shortcuts#403]
preferably from a json file (there's 100+ options so i can't do it manually)

**Comment by Waboodoo** [comment]
You could try the following:
1. Create a dummy multiple choice with a few values
2. Export the shortcut that uses the multiple choice, via the context menu -> "Export"
3. The file you get this way is a zip file, unzip it and find the JSON file inside.
4. In this JSON file, look for your dummy multiple choice to set how its structure works.
5. Copy in your own options, adjusting them to match the structure of the dummy values. If you have many options I recommend doing this with some script or other automation. You'll probably need to set an ID for each option, for this you can just generate a UUID.
6. Save the JSON file and place it into a zip file
7. In the app, import this file by going to "Import / Export" in the main menu

**Comment by braboobssiere** [comment]
I'll try it, thank you
