### ISSUE TITLE
Feature Request : Trigger Commands using a Physical or Bluetooth Keyboard

### ISSUE THREAD

**Issue by nk-gears** [Waboodoo/HTTP-Shortcuts#404]
### Is your feature request related to a problem? Please describe.
I use this app for custom actions from Chrome and Youtube. I would like to trigger the commands through my mini keyboard/bluetooth.

### Describe the solution you'd like
The app should listen for any keyboard events and trigger the respective scripts

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by Waboodoo** [comment]
Thanks for the feature request. I did a bit of research on this topic and it looks like this would be fairly complicated if not outright impossible to do without some questionable workarounds like abusing accessibility services. This sounds like it should be the job of a general purpose automation app, which HTTP Shortcuts is not meant to be. As such, unfortunately I will not be implementing this at the current time.

**Comment by nk-gears** [comment]
@Waboodoo Thanks for the explanation. Closing this.
