### ISSUE TITLE
[BUG] No curl import/export of digest authentication

### ISSUE THREAD

**Issue by MichaelEFlip** [Waboodoo/HTTP-Shortcuts#407]
### Steps To Reproduce
1. Create a shortcut with http digest authentication
2. Export curl command

### Expected behavior
Curl command should contain the "--digest" option:
curl --digest --u user:password ...

### Actual behavior
Plain HTTP basic authentication is exported:
curl --u user:password ...

### Additional information
The other way round is also not working: If trying to import a curl command with "--digest" a message box is shown, that the "--digest" option is not supported.

### Context
- Android OS Version: [13.0]
- App Version [3.8.0]

**Comment by Waboodoo** [comment]
Thanks for the issue. This will be fixed in the next release.

**Comment by Waboodoo** [comment]
This is now fixed in version 3.10.0
