### ISSUE TITLE
Writing to a file using a script. 

### ISSUE THREAD

**Issue by UlinoyaPed** [Waboodoo/HTTP-Shortcuts#410]
### Is your feature request related to a problem? Please describe.

I have an API that I need to make multiple requests to, and I want to save the results in a file. The problem I'm facing is that I also need to **perform additional processing** on the returned results. Although I can handle the data using a script, **the application's built-in file-saving functionality doesn't meet my requirements**. Therefore, I would like to **add a file I/O interface** or include the 'require' module import, just like `const fs = require('fs')`

**Comment by Waboodoo** [comment]
In the upcoming version, I'm adding basic functionality to read a file as a string and to write data into a file. Would this suffice for your use case? If not, please let me know what kinds of file operations you'd also need. I won't be able to implement the full scope of what `fs` can do.

**Comment by Waboodoo** [comment]
Version 3.16.0 is now released, which includes an option to write to a file using Scripting. More info about this here: https://http-shortcuts.rmy.ch/scripting#files
