### ISSUE TITLE
[BUG] Desktop shortcuts disappear on app upgrade

### ISSUE THREAD

**Issue by mimre25** [Waboodoo/HTTP-Shortcuts#414]
### Steps To Reproduce
1. Create a shortcut on any home screen
2. Upgrade the app to a new version
3. Shortcuts are gone

### Expected behavior
I would like the shortcuts on any of my home screens to stay there when I upgrade the app, as otherwise I have to re-add them every time.

### Actual behavior
The shortcuts disappear when I upgrade the app.

### Context
- Android OS Version: 11 (OxygenOS 11.1.2.2 on OnePlus 6)
- App Version ~ I've had the app for about a month or two - every upgrade triggers the behavior
- Other context: I've had this happen for other apps' shortcuts, so it might be an android default Behavior, but I'm not sure.

I'm happy to provide any additional info if necessary. 
I'd also be open to contribute but haven't done Android development in about 10 years, and haven't used Kotlin at all :sweat_smile:

**Comment by Waboodoo** [comment]
I'm afraid this is likely a problem I can't fix. Once the shortcuts are placed on the home screen, they should stay there until removed. If they disappear then this is likely an issue with the launcher or some other part of Android or the manufacturer's software. I was never able to reproduce this issue, but I've had people report it before, though only rarely, so I assume it's an issue with only certain devices. So far I have no lead on what might cause this or how it could be fixed.

**Comment by mimre25** [comment]
Thanks for the prompt response! 

I've googled around a bit and it seems to be quite common with the one plus launcher, however, it's not happening for every app. 
The latter part hints that there is something that the app can also influence, and so do some search results.

Anyhow, since I assume debugging this is probably some form of a Heisenbug and given that this app doesn't have weekly updates, I don't think it's worth further investigating. 

I'll revisit this thread after the next upgrade and report back whether it happened again or not ~ maybe that will shed some insights.

--

Let me also take this chance to thank you for providing this app, I really appreciated it! :slightly_smiling_face:

**Comment by Waboodoo** [comment]
> The latter part hints that there is something that the app can also influence, and so do some search results.

I wasn't able to find out what this "something" is.
My suggestion here would be to just disable automatic updates. I release new versions quite irregularly, but most of the time it's no game changers, so you should be perfectly fine with not installing all updates or only updating occasionally.

**Comment by mimre25** [comment]
I've updated the app today and this time the home screen shortcuts stayed.

I'll close this, and if I ever encounter the problem again and find a solution, I'll come back and let you know :slightly_smiling_face:
