### ISSUE TITLE
Something went wrong... [BUG]

### ISSUE THREAD

**Issue by itszux** [Waboodoo/HTTP-Shortcuts#415]
### Steps To Reproduce
1. On executing this curl
curl 'https://api-my.te.eg/api/user/generatetoken?channelId=WEB_APP' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.6' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://my.te.eg' \
  -H 'Referer: https://my.te.eg/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-GPC: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'
2. It return "something went wrong" without knowing what went wrong

### Expected behavior
It should return a response then run this on success
setVariable("jwt", JSON.parse(response.body).body.jwt);
And it was working just fine a week ago

### Actual behavior
It shows a toast "Something went wrong"
I think it doesn't even send the request

### Screenshots
![Screenshot_20240406_170558_HTTP Shortcuts](https://github.com/Waboodoo/HTTP-Shortcuts/assets/99715555/45c19f03-bbd7-4731-8a71-46988a77a9b9)

### Context
Please complete the following information:
- Android OS Version: 13
- App Version 3.10.0

**Comment by Waboodoo** [comment]
Thanks for the bug report. The "Something went wrong..." pops up when there's an internal unexpected error. Did you install the app from the Play Store, from an APK or from F-Droid, and if one of the former two, do you have crash logging enabled in the app (it's on by default)? And if so, could you use the in-app "Contact Developer" option and send me a quick message, such that I get your user ID, which will help me find the corresponding crash in the crash logs. Alternatively, let me know which device model you are using or at which specific time you encountered the error, so I can narrow it down.

I have one lead so far, and I'm already working on a fix for that, but I want to make sure this isn't something else.

**Comment by itszux** [comment]
I installed the app from the Play Store
crash logging is enabled
I just send you a message from "contact developer"
and its the last request I send from the app

**Comment by Waboodoo** [comment]
Sorry it took a while, but I believe I've found the cause. I'm preparing a new release not that includes a fix. Until then, you might be able to work around the issue by editing your shortcut and in the "Advanced Technical Settings" disable the "Store cookies" checkbox.

**Comment by itszux** [comment]
Thanks, by disabling "Store cookies" its working.
