### ISSUE TITLE
开启实验性功能后，获取不到剪贴板内容[BUG]

### ISSUE THREAD

**Issue by dongbao66** [Waboodoo/HTTP-Shortcuts#416]
与syncclipboard 剪贴板同步结合使用，在不开启实验性功能的情况下，使用磁贴快捷方式可以 正常获取剪贴板 。
开启实验性功能后，使用磁贴，内容获取为空白

**Comment by dongbao66** [comment]
[ENGLISH]
When utilizing the SyncClipboard in conjunction with the Tile feature sans the experimental option enabled, the clipboard retrieval via shortcuts operates seamlessly. However, upon activating the experimental functionality, employing the Tile feature results in blank content retrieval.

**Comment by Waboodoo** [comment]
This should now be fixed as of version 3.12.0
