### ISSUE TITLE
[BUG] toast notification Not working

### ISSUE THREAD

**Issue by egs2003** [Waboodoo/HTTP-Shortcuts#418]
### Actual behavior
A clear and concise description of what actually happens.

### Context
Please complete the following information:
- Android OS Version: [e.g. 9.0]
- App Version [e.g. 1.32.0]
- Any other context about the problem that you think is relevant
- Device ID if possible: (Unless you installed from F-Droid or have crash reporting disabled, you can find this in Settings > Privacy)

**Comment by Waboodoo** [comment]
@egs2003 Please take the time to fill in the details on the issue, otherwise I have no idea what this is about.

**Comment by Waboodoo** [comment]
Closing this as no information was provided
