### ISSUE TITLE
Feature Request: Share Intent

### ISSUE THREAD

**Issue by ncarlier** [Waboodoo/HTTP-Shortcuts#42]
Hello,
first of all thanks for this app. It's a great companion for personal iot stuff. Something very cool would be to add sharing support. For instance, you are on an application like Twitter and you want to share a tweet. You choose "HTTP Request Shortcuts" as share intent, Then the widget propose all the shortcuts able to send data (mainly POST requests). And when you choose the shortcut, the content of the share intent is sent to the HTTP endpoint. Then your personal backend (NodeRED or whatever) would be able to decode the http body and do some clever stuff. You could imagine several use cases: post a photo, archive text, trigger some action depending the data sent.
What do you think ?

**Comment by Waboodoo** [comment]
That sounds like a great idea. I guess I could combine this with the concept of variables, e.g. that there would be a special variable {{sharedText}} that can be inserted into shortcuts. This way when sharing into "HTTP Shortcuts" the app would suggest all shortcuts that contain this variable placeholder.

I'll definitely do some investigation on this one.

**Comment by ncarlier** [comment]
Using a variable is a great idea! And the cherry on the cake would be also to use the intent content type as http request content type. And don't limit to text content. You can imagine to upload the file if the type of the intent is a stream. Doing that you will also be able to share/upload an image, an audio record... or whatever.
Nevermind, the cake without the cherry would be already so cool ;)

Thanks!

**Comment by pouicr** [comment]
+1

**Comment by ncarlier** [comment]
Hello, any update on this feature request ?

**Comment by Waboodoo** [comment]
I have started working on this and built a prototype where you can share text to be used in a variable. There's still some work to be done, though, and I can not say when I'll have time to continue. But a basic implementation of ti will definitely be in the next release.

**Comment by ncarlier** [comment]
Great! I am looking forward the next release. Thx a lot.

**Comment by Waboodoo** [comment]
A basic version of this is now available in v1.13, where it is possible to mark a variable as 'Allow share'. This makes it possible to share text snippets (not files) into to app where they are used as the value for these variables.

The feature to allow sharing arbitrary files/data into a shortcut to use as request body (+ set request type accordingly) is still planned for a future version.

**Comment by ncarlier** [comment]
:+1:  Just tested and everything is working as expected! It's exactly what I needed. Thanks alot for this super tool.

**Comment by pouicr** [comment]
Great

**Comment by eadmaster** [comment]
thank you it is working fine for me,
but please a little explanation on the frontpage how to use this.

**Comment by Waboodoo** [comment]
@eadmaster There is a detailed description in the help text that you can find on the "Variables" screen. But I agree, there needs to be more/better documentation. I will see that I can add something, maybe a tutorial or FAQ.

**Comment by Waboodoo** [comment]
Part of this is now possible as of version 1.29.0, where I've added file parameter support. I.e., it is possible to send files in a request, using form-data. You can share one or multiple files into the app and have them sent as form parameters. It is not yet possible to share a file and use it as the full request body, that's something I plan to work on in the future.

**Comment by Waboodoo** [comment]
Closing this now as it is now also possible to share a file and use it as the request body for a shortcut. To use this feature, set the shortcut's request body type to "File (Picker)". If the shortcut is executed normally, it will prompt you to pick a file, but you can also trigger the shortcut by sharing a file into the app.
