### ISSUE TITLE
Any shortcut for real-debrid.com?

### ISSUE THREAD

**Issue by morocoeltopo** [Waboodoo/HTTP-Shortcuts#420]
I Alternatively use realdebrid and alldebrid services, for the second there are a zip file on his web page so you can import it to the app, edit it with your api key and share the links to the http-shortcuts obtaining the direct download url. My question is if there are a similar already created shortcut for real-debrid service or where can I find the info to create a proper one. Thanks in advance for the help.

Sorry for my bad English, I'm a Spanish speaker 😅.

**Comment by Waboodoo** [comment]
Hello,
I don't think I can really help you here. Until moments ago, I didn't even know what realdebrid and alldebrid are. From a quick googling, I didn't find any documentation on how you could integrate with realdebrid, but I saw that there's an unofficial subreddit for it. I recommend you try asking there, as there your question will be seen by people who know and use the service, whereas here it will at most be seen by people using the HTTP Shortcuts app, which is used for all kinds of things.

**Comment by Waboodoo** [comment]
Forgot to post the link: https://www.reddit.com/r/RealDebrid/
