### ISSUE TITLE
[BUG] App crashes when deleting characters from the Scripting input fields

### ISSUE THREAD

**Issue by LunarKittyy** [Waboodoo/HTTP-Shortcuts#421]
### Steps To Reproduce
1. Go to any Scripting input field (Scripting in a shortcut or Global Scripting).
2. Type anything and then try to delete it.
3. The app crashes immediately.

### Expected behavior
It's possible to delete anything from the code and I can edit it without the app closing instantly.

### Actual behavior
The app crashes and I get returned to home screen instantly after pressing the backspace key. Because of that I'm unable to delete any of the code I typed in there and the only way to remove it is to fully clear the app data if it got saved.

### Screen recording
https://github.com/Waboodoo/HTTP-Shortcuts/assets/76916308/e95b8b76-e5ae-40d2-a743-4f5903786729

### Context
- Android OS Version: 13
- App Version: 3.13.0
- Device model: SM-G781B/DS
- OneUI Version: 5.1
- Device ID: 35074E6D26AF42AAA74B

**Comment by Waboodoo** [comment]
Hi, thanks for the detailed bug report. I see the crash in the crash logs, but I can't reproduce it. My suspicion is that it has to do with your keyboard, specifically the autosuggest/autocomplete feature, or perhaps some accessibility feature (e.g. TalkBalk). Could you check if disabling those fixes the issue?

As a workaround for now, you could use the "Remote Edit" feature found on the "Import & Export" screen, which lets you edit your shortcuts from a computer.

**Comment by Sternagfonkel** [comment]
Having the same problem here on old Android 9 with app version 3.13.0. Sometimes it is possible to delete more than one character but then it will fail/crash at the second or third.
I'm using the "Unexpected Keyboard" from f-droid without any auto-completion or suggestions. TalkBack is also disabled.

**Comment by Waboodoo** [comment]
I made a change, which might fix this issue. It's part of version 3.14.0, which is available for beta testing. You could try joining the [beta program](https://play.google.com/apps/testing/ch.rmy.android.http_shortcuts), installing the update and testing whether the crashes still occur.

**Comment by LunarKittyy** [comment]
I checked disabling autocorrect/autocompletion on 3.13.0 and using another keyboard without these features. I also don't have any accessibility features active, I believe. It still crashed. But I downloaded the new 3.14.0 version and it seems to solve the issue. Thank you! (amazing app btw, thanks for making it)

**Comment by Waboodoo** [comment]
That's good news, thanks for testing the new version. I will be releasing it as a regular update soon.

**Comment by Waboodoo** [comment]
Version 3.14.0 is now fully released, which should fix this issue. It will likely take a few days for the update to also become available on F-Droid.

**Comment by Sternagfonkel** [comment]
Yes, problem seems to be solved for me too. Many thanks! :)
