### ISSUE TITLE
Align the widgets

### ISSUE THREAD

**Issue by Djyp** [Waboodoo/HTTP-Shortcuts#428]
### Is your feature request related to a problem? Please describe.
Since the latest version and a fix on the shortcuts' names, my widgets aren't aligned anymore.

### Describe the solution you'd like
It's not much but I guess if I had the option to align widgets at the top line, all widgets would be aligned and the length of the text would not affect the result.

### Describe alternatives you've considered
This could be the default behavior without an option

### Additional context
This illustrates some of my widgets. Yes they're all linked to Obsidian. Number 1, 3 and 5 have two lines of text. 2 and 3 and shorter and the titles need only one line.
![some of my shortcuts](https://github.com/user-attachments/assets/8f933621-2e92-415c-8643-b35c7906b49f)

**Comment by Waboodoo** [comment]
Thanks for the detailed description. I'll see that I can improve this for the next version.

**Comment by Waboodoo** [comment]
Version 3.16.0 is now released, which should fix this alignment issue.

**Comment by Djyp** [comment]
Thanks! It is perfect!
