### ISSUE TITLE
exclude a shortcut from the "Send To" menu

### ISSUE THREAD

**Issue by AdachiQ** [Waboodoo/HTTP-Shortcuts#429]
I created Shortcut1 to send multiple files to the server, but this server can only receive one file at a time. Therefore, I created Shortcut2. After Shortcut1 receives multiple files, it executes Shortcut2 multiple times to send files to the server. This results in both Shortcut1 and Shortcut2 being able to accept files, and each time I click "Send To," I need to select both Shortcut1 and Shortcut2 from the list. How can I exclude Shortcut2 from the list so that I don't have to make a selection?

**Comment by Waboodoo** [comment]
Hi,
Currently, there's no way to achieve this. I'm adding such an option for the next release, which I'll hopefully be able to release in the next 2-3 weeks.

**Comment by AdachiQ** [comment]
> Hi, Currently, there's no way to achieve this. I'm adding such an option for the next release, which I'll hopefully be able to release in the next 2-3 weeks.

Nice!
HTTP Shortcuts is a fantastic app!

**Comment by Waboodoo** [comment]
Version 3.16.0 is now released, which includes this option. You'll find it on the "Trigger & Execution Settings" screen when editing a shortcut.
