### ISSUE TITLE
dynamic icon change.

### ISSUE THREAD

**Issue by roccomuso** [Waboodoo/HTTP-Shortcuts#43]
Do you think would be hard to have the icon changing based on a specific response? This to avoid having multiple shortcuts for a single switch-toggle operation.

I did a similar app in the past, using Android widgets and changing widget background-img based on the http response. I think it could be a useful feature.

PS. I'm recommending this app to all the users using my https://github.com/roccomuso/iot-433mhz home automation system. :)

**Comment by Waboodoo** [comment]
Changing the icon dynamically is not possible with shortcuts, as they are managed by the launcher and the app itself has very limited control. With a widget it would be super easy to do, but currently the app has no widget and I'm not planning on adding one in the short run. However, at a later stage, especially in combination with other features, this sounds like a useful idea to include. I will keep it on the radar.

Thanks for the recommendations, very much appreciated :+1:

**Comment by penlok** [comment]
I understand that its not straight forward to dynamically update the icon on the start screen. But what about doing it in the list view? This is basically the only missing piece to turn this app into an automation front end.

Iäm currently using a homewritten frontend in javascript to my automation. But that requires a browser to be opened which takes time and is not so nice as if I could use your app instead.

Preferably, a longlived http request would update the icon in the list view once it is opened.

**Comment by Waboodoo** [comment]
I agree on the usefulness of the feature. However, it is also a larger change to how the app currently works and what it was designed for, and I currently don't know how a user would configure this. I will keep this idea on the backlog, but for now I can only treat this as low priority.

**Comment by Flavien06** [comment]
It may be possible to change the icon depending on the state of a variable (example ON = color icon; OFF = grey icon)

**Comment by gemminiss** [comment]
Amazing work Waboodoo!.
Do you have any progress on this feature?

**Comment by jeedomsteph37** [comment]
Hi,

what the news for change icon dynamically ?

Thank,

**Comment by Waboodoo** [comment]
In the current version it is possible to dynamically change the icon of a shortcut via the `changeIcon()` function.
When creating/editing a shortcut, go to "Scripting" section and find the option "Add Code Snippet" > "Actions" > "Change Shortcut Icon".
The function takes 2 arguments: The first one is the name or ID of the shortcut you want to change (you can pass an empty string to target the current shortcut) and the second one is the name of the icon (you can only use the built-in icons so far).

You'll find more information on the [documentation page](https://http-shortcuts.rmy.ch/scripting).

**Comment by jeedomsteph37** [comment]
Thank you ! :)
