### ISSUE TITLE
Add an option to the variable to determine whether the value should be removed upon export

### ISSUE THREAD

**Issue by AdachiQ** [Waboodoo/HTTP-Shortcuts#430]
Some variables in my shortcut require manual input from the user the first time it is run, and each user has different values. It is quite cumbersome for me to manually remove the values of these variables when exporting the shortcut. I hope to add an option to the variables to determine whether their values need to be removed upon export.

**Comment by Waboodoo** [comment]
Sounds good. I'll add such an option in the next release.

**Comment by Waboodoo** [comment]
Version 3.16.0 is now released, which includes the option to mark variables, such that their values are excluded from exports. You can find this option in the "Advanced Settings" section when editing a variable.
