### ISSUE TITLE
add property "visible" to shortcuts and categories to be able to hide "Xmas"-Items

### ISSUE THREAD

**Issue by Gru0810** [Waboodoo/HTTP-Shortcuts#431]
### Is your feature request related to a problem? Please describe.
I have a lot of shortcuts only for Xmas. Today (Summer) I see all these "useless" shortcuts and categories. I can move them to a new category " Xmas" but i want to keep together all "Light ON"

### Describe the solution you'd like
It would be great when a Shortcut or Category has a property "visible" like "Description". As Property-value the user can enter a Value,  a Variable or a JavaScript ( with return-value true or false / 0 or 1.
all permanent ShortCuts will have Value "true".
all XMas-Shortcuts will have Variable "VarVisibleOnXmas"
default Null -> visible = true

### Describe alternatives you've considered
none

### Additional context
nothing

**Comment by Waboodoo** [comment]
Hi, thanks for the feature request.
I'm taking the liberty to adjust this a bit so it better aligns with other items in my backlog:
For the upcoming release, I'm making it possible to hide shortcuts, similar to how it is already possible to hide entire categories. I'm also adding a `setShortcutHidden` Scripting function. This should enable you to create a custom Scripting shortcut which can show or hide all of your X-Mas shortcuts in one go.

**Comment by Waboodoo** [comment]
Version 3.17.0 is now released, which includes the `setShortcutHidden` function (see https://http-shortcuts.rmy.ch/scripting#set-shortcut-hidden). I hope this addresses your issue.

**Comment by Gru0810** [comment]
Hallo Roland
Hat alles super geklappt mit der neuen Funktion!

Frage 1: Für das aus- und einblenden von Kategorien gibt es (noch) keine
Funktion?
Frage 2: man kann nur über den WebEditor "hidden" Shortcuts wieder finden
und wieder anzeigen lassen?
Frage 3: gibt es eine Möglichkeit per Javascript alle existierende
Shortcuts durch  zu-"loopen"
Beste Grüsse
Udo aus Eglisau

Roland Meyer ***@***.***> schrieb am Mi., 28. Aug. 2024,
18:32:

**Comment by Waboodoo** [comment]
> Frage 1: Für das aus- und einblenden von Kategorien gibt es (noch) keine
Funktion?

Noch nicht. Hab ich aber vor, noch einzubauen.

> Frage 2: man kann nur über den WebEditor "hidden" Shortcuts wieder finden
und wieder anzeigen lassen?

In den Einstellungen findest du eine Option die es dir ermöglicht, versteckte Shortcuts sichtbar zu machen.

> Frage 3: gibt es eine Möglichkeit per Javascript alle existierende
Shortcuts durch  zu-"loopen"

Die gibt es nicht, und das möchte ich aus Sicherheitsgründen vorerst auch so belassen. Primär möchte ich verhindern, dass en User externe Shortcuts importieren kann, welche dann mit bestehenden Shortcuts interagieren oder diese verändern. Da muss ich mir mal eine Strategie überlegen um das zu verbessern, aber bisher war das noch nicht so ein Problem. Du müsstest also deine Shortcuts explizit mit Namen oder ID ansprechen um sie ein- oder auszublenden.
