### ISSUE TITLE
add "cancel" to Slidebar ( and other elements with user-interaction)

### ISSUE THREAD

**Issue by Gru0810** [Waboodoo/HTTP-Shortcuts#432]
### Is your feature request related to a problem? Please describe.
I use a Slidebar to define a duration. It would be helpful to be able to cancel the input
![image](https://github.com/user-attachments/assets/a353b288-e925-4084-ba9f-7c826862caf3)

### Describe the solution you'd like
add a Cancel"-button like "ok"

**Comment by Waboodoo** [comment]
You can already cancel the input by pressing the back button or by tapping outside of the dialog window. Is that not sufficient?

**Comment by Gru0810** [comment]
I did not know this! Just tested and it's fine for me.
Schöne Grüsse aus Eglisau, Wir hatten  vor langer Zeit mal Email-Verkehr betreff "HTTP Shortcut"

**Comment by Waboodoo** [comment]
Super, freut mich dass dann das Problem gelöst ist 👍🏻
