### ISSUE TITLE
[BUG] Crashed when placing variables into the textbox

### ISSUE THREAD

**Issue by 4riw** [Waboodoo/HTTP-Shortcuts#433]
### Steps To Reproduce
1. Add or edit Request body/parameter
2. In value textbox, place a variable place holder, any kind.

### Expected behavior
A variable place holder should be there and continue with editing.

### Actual behavior
The app crashed and had to restart the app and recover the unsaved shortcut. But, if the textbox is multi line the place holder was there after recovery. The same behavior wasn't reproduce if the textbox is single line.

### Recordings

https://github.com/user-attachments/assets/05d380ab-d695-4b74-a719-0fd01725d1b9

https://github.com/user-attachments/assets/6bc2a8cd-0e81-478c-bf52-5150a7cc464a

### Context
- Android OS Version: 11
- App Version: 3.15.0
- Device: SM-A315G
- Device ID: 6B95D2C4DDD448E8BD52

**Comment by Waboodoo** [comment]
Thanks for the detailed bug report. I can't reproduce the issue myself, but I see it in the crashlogs. I suspect it's device-specific or depends on a component outside of the app. I will try a fix for the next release.

**Comment by Waboodoo** [comment]
Version 3.16.0 is now released, which might fix this issue. Please let me know if it doesn't.

**Comment by 4riw** [comment]
The bug persists in version 3.16.0. Even after being granted the 'appear on top' permission, I'm still uncertain if it is the issue.

**Comment by Waboodoo** [comment]
Ok, I'll look into it some more when I have the time. I don't think it is related to the "Appear on top" permission. More likely it is a problem with the software keyboard or with an accessibility setting. You could try a different keyboard, or play around with autocomplete settings.

**Comment by Waboodoo** [comment]
@4riw Does this crash only happen for the request body and parameter fields, or can you also reproduce it with other fields, such as the URL field or the authentication username or password fields?

**Comment by 4riw** [comment]
The same crash happens in other fields with single line textbox, but at Scripting, it operates as expected. I can add variables there without causing the crash.

**Comment by Waboodoo** [comment]
@4riw I tried another thing in version 3.17.0. Can you install it and check if you still get the crash?

**Comment by 4riw** [comment]
Yess.. it's working like a charm now. Currently I'm at 3.18 and the bug has gone.
Thank you very much

**Comment by Waboodoo** [comment]
Glad to hear 👍🏻
