### ISSUE TITLE
[BUG] prompt function will not display long text correctly

### ISSUE THREAD

**Issue by 77-77SP** [Waboodoo/HTTP-Shortcuts#434]
### Steps To Reproduce
1. Add **prompt** function to a shortcut and give it a long text as a parameter.
2. Run the shortcut.

### Expected behavior
The long text should be scrollable and visible and the input box should accept keyboard input.

### Actual behavior
Long text "underflows" and input box is unresponsive.

### Context
- Android OS Version: 13
- App Version: 3.15.0
- Any other context about the problem that you think is relevant: Android global font size is set to slightly larger.

**Comment by Waboodoo** [comment]
This bug should now be fixed in version 3.17.0
