### ISSUE TITLE
[BUG] writeFile is not a function

### ISSUE THREAD

**Issue by 2061360308** [Waboodoo/HTTP-Shortcuts#439]
### Steps To Reproduce
const dir = getDirectory('photo');
dir.writeFile('someFile.txt', 'New file content');
I have mounted the directory and the corresponding access time will be updated after executing the script, but it still prompts' writable file is not a function '

### Expected behavior
The file someFile.txt should be created and contain the content New file content.

### Screenshots
![54f833bc07c2317e2be7bc4d63867e4](https://github.com/user-attachments/assets/4045a1ec-36e7-4d13-90b9-eecbfa3b88be)
![861a2de738b083c5291c869ae4e5357](https://github.com/user-attachments/assets/1246541e-abb4-46c0-99aa-14880db21b31)

### Context
Please complete the following information:
- Android OS Version: 14
- App Version 3.17.0

**Comment by Waboodoo** [comment]
Thanks for reporting this. The bug is now fixed in version 3.18.0.

**Comment by 2061360308** [comment]
First of all, thank you for your work. But I encountered a new problem. WriteFile is a file written as text, how can I directly write bytes

**Comment by Waboodoo** [comment]
So far, `readFile` and `writeFile` can only deal with strings. Bytes are not supported (yet). The next best thing you could do is to base64 encode your data before writing and then base64 decode when reading. Adding support for binary data is something I want to add in the future, but I have no concrete plans yet on when and how.

**Comment by 2061360308** [comment]
> So far, `readFile` and `writeFile` can only deal with strings. Bytes are not supported (yet). The next best thing you could do is to base64 encode your data before writing and then base64 decode when reading. Adding support for binary data is something I want to add in the future, but I have no concrete plans yet on when and how.

Okay, I look forward to your adding this feature. The situation I'm facing is that I need to write the base64 image data returned by the interface as an image and save it. In this case, I cannot save it as text as you suggested. Specifically, what I need is to synchronize the Windows clipboard and automatically save the image data to the clipboard after taking a screenshot in Windows. I found a Windows program that provides a network interface to access the Windows clipboard, and now I want to implement a feature where a screenshot taken in Windows can be quickly saved on an Android device.😂

**Comment by 2061360308** [comment]
This feature is fairly simple, and I will design it myself. In this case, a better approach would be for Windows to push data to Android devices rather than for Android devices to manually trigger downloads. The Android app involves only a small amount of content, and I think I should be able to complete it.

**Comment by Waboodoo** [comment]
As of version 3.19.0, the `writeFile` function can now also write bytes directly instead of strings.

**Comment by 2061360308** [comment]
Thanks

> 从 3.19.0 版本开始，该`writeFile`函数现在还可以直接写入字节而不是字符串。
