### ISSUE TITLE
Option to force network requests go through WiFi instead of mobile network

### ISSUE THREAD

**Issue by vosmani** [Waboodoo/HTTP-Shortcuts#46]
When I'm connected to a WiFi hotspot (that requires web based login), it seems that Android (5.0.2) will forward requests over other networks (3G/4G for example) instead the hotspot, since the hot spot has no internet connection.

Would it be possible to add an option to force HTTPS requests through WiFi?

The solution seems simple, but I am not capable of implementing it:

[http://stackoverflow.com/questions/39311853/android-force-network-requests-go-through-wifi-instead-of-mobile-network](http://stackoverflow.com/questions/39311853/android-force-network-requests-go-through-wifi-instead-of-mobile-network)

**Comment by Waboodoo** [comment]
Sounds like a good idea. I will investigate.

**Comment by vosmani** [comment]
Hi Roland,

Any plans for this feature to be addressed?

**Comment by Waboodoo** [comment]
I had a quick look at it a few weeks ago and it turned out to be more complicated than anticipated. I will try to address it together with some other issues, so it is on the higher end of my priorities list. However, as always, my time to work on this project is limited, so I can't make any promises about the timing.

**Comment by Waboodoo** [comment]
I'm doing a bit of cleanup on the open issues. I realize I've completely dropped the ball on this one, sorry for that. If this is still relevant to anyone, please drop a comment, otherwise I'll close this soon as no mention of such feature request has come up in a long time.
