### ISSUE TITLE
feature request: save cookie and multiple requests

### ISSUE THREAD

**Issue by vanous** [Waboodoo/HTTP-Shortcuts#47]
Hi,

what a great app! I have to interact with a web that requires auth via form and then keeps cookie for following requests. Any chance i can make shortcut recipe with multiple requests, where i would define variables (for the auth) for the first request (this i can do already) save the cookie and re-use the cookie for following requests (with variables)?
Perhaps it's already possible and i just missed it?
thank you!

**Comment by Waboodoo** [comment]
Hi,
Unfortunately, that is not yet possible. Store the response or parts of it in a variable is definitely a feature a want to have in the app at some point, but for now I can't give an estimate on when I'll be able to work on it.

**Comment by vanous** [comment]
OK, thank you. I am not a dev so i cannot help unfortunately...

**Comment by Waboodoo** [comment]
Soo, it's been a few years, but I can finally say that the app supports this. As of version 1.36.0, the app can store cookies across requests. To do so, enable the "Store cookies" checkbox found in "Advanced Technical Settings" when creating or editing a shortcut.
