### ISSUE TITLE
Feature Idea: Provide multiple HTTP Action per Widget

### ISSUE THREAD

**Issue by Kusig** [Waboodoo/HTTP-Shortcuts#49]
This app works great and I could control all my house automation system perfectly right from my Android home screen :-)

It would be very handy if it would be possible to define different actions for click patterns:
- single touch
- double touch
- long touch

Or somehow a list of possible actions on one widget one does a long touch action ...

**Comment by Waboodoo** [comment]
Unfortunately, on Android it is only possible to define single touch actions for homescreen shortcuts. However, it would be possible to define these actions for use _inside_ the app. It would require some restructuring though, so I can not give this a high prio it the moment. But thanks for suggesting, I can see this being useful.

**Comment by Waboodoo** [comment]
Closing this now as I have decided to not make the shortcuts behave differently inside the app than outside. With the use of variables and scripting it is already possible to have one shortcut have different behavior based on additional user input, so I don't see the need for this now.
