### ISSUE TITLE
Support Android 7.1 app shortcut

### ISSUE THREAD

**Issue by kice** [Waboodoo/HTTP-Shortcuts#66]
https://developer.android.com/guide/topics/ui/shortcuts.html

I think it's the best way to keep the home screen clean without losing convince.

**Comment by Waboodoo** [comment]
I've been meaning to look into this. I'll definitely experiment with these some time, though currently I don't yet know in what way I'll use them, or when. Thanks for the suggestion.

**Comment by Waboodoo** [comment]
Support for app shortcuts is now added in version 1.16.0.
