### ISSUE TITLE
problem connecting to https with certifcate signed by custom ca

### ISSUE THREAD

**Issue by jarnett** [Waboodoo/HTTP-Shortcuts#67]
I have a shortcut that posts to a HTTPS URL.  The server has a certificate that is signed by a custom certificate authority.  I've added this CA cert to Settings > Security > Trusted Credentials on my android device.  This allows chrome to connect to the server and verify the certificate chain.  HTTP-Shortcuts fails with the following:

```
power cycle failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

This configuration worked in a previous version of the software, but I am unsure what version that was.

**Comment by Waboodoo** [comment]
As far as I recall, there have not been any changes to how the HTTP stack works in the app.

I tried to figure out how I can get my app to use the user provided certificates from the system trust store, but apparently that is not a typical use-case, as I was unable to find anything useful on the matter (apart from "Just trust all certificates", which should really only be a last resort, if at all).

**Comment by domanchi** [comment]
From [this blog post](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html), it seems that user-added CAs are blocked by default, unless [explicitly added](https://developer.android.com/training/articles/security-config.html#manifest) like the following:

```
<network-security-config>  
      <base-config>  
            <trust-anchors>  
                <!-- Trust preinstalled CAs -->  
                <certificates src="system" />  
                <!-- Additionally trust user added CAs -->  
                <certificates src="user" />  
           </trust-anchors>  
      </base-config>  
 </network-security-config>
```

I wonder whether we can build this in: it's better than the "trusting all certificates" option, it's more developer friendly (handy, considering this is a very nice cURL wrapper), and we'd be deferring the security of certificate management to the Android OS itself.

I mean, if the browser trusts it, shouldn't this?

**Comment by Waboodoo** [comment]
@domanchi Good find, thanks for the input. I was not aware of this. I have now added included this configuration. It will be part of the next release.

**Comment by Waboodoo** [comment]
Closing this now as it has most likely been fixed one version ago. Please re-open if the problem still exists.
