### ISSUE TITLE
HTTP message body input not visible

### ISSUE THREAD

**Issue by elvador1** [Waboodoo/HTTP-Shortcuts#7]
It seems like the HTTP message body input field is not visible on edit if the shortcut got created without one.

**Comment by Waboodoo** [comment]
I can't seem to reproduce this issue. Can you attach a screenshot or give detailed step on how to reproduce it?

**Comment by elvador1** [comment]
Looks like the custom parameters can hide it:
http://i.imgur.com/SAG46Dl.png
http://i.imgur.com/N1DMrfk.png

**Comment by Waboodoo** [comment]
This is the intended behavior. POST parameters (or any parameters other than GET parameters which are encoded into the URL) are sent as part of the request body. Therefore if you chose to send a custom request body you have to encode your parameters into the request body yourself. That is why using the parameter list disables thes use of a custom request body.

**Comment by elvador1** [comment]
Makes sense - feel free to close this
