### ISSUE TITLE
Relax URL validation

### ISSUE THREAD

**Issue by dvv** [Waboodoo/HTTP-Shortcuts#70]
I defined variable `{{do}}` to be `http://gate/do` and made a shortcut using `{{do}}?a=b`.
Upon run/save it says I entered invalid URL.
Please consider expanding URL before validation.
TIA

**Comment by Waboodoo** [comment]
Good point, though it is not as trivial as that as variable values change at execution time and may thus no longer be valid URLs. I'll see what I can do though.

**Comment by dvv** [comment]
Oh, I see.
- Limit pre-expansion with only constant variables?
- Do not check URL validity at all? (let android report authoritative error; who knows what URL scheme is supported by device)

**Comment by Waboodoo** [comment]
As of version 1.17, the URLs are no longer validated.

**Comment by sebastianha** [comment]
I just tried the same with version 1.25.0 and I think this bug is still there. Can you please check again?

**Comment by Waboodoo** [comment]
It seems there is a regression here, this used to work. I'll see that I can fix it again for the next version.
