### ISSUE TITLE
Array parameter

### ISSUE THREAD

**Issue by afk-mcz** [Waboodoo/HTTP-Shortcuts#77]
Could you add support for array string parameter?

**Comment by Waboodoo** [comment]
Could you elaborate on that? I'm not entirely sure what you mean, or what your use-case is.

**Comment by Arlefreak** [comment]
I have an end point which the body looks like this

```
{
    "tags": ["foo", "bar"],
    "name": "name"
}
```

It would be nice if you can have an array field for the tags parameter.

**Comment by Waboodoo** [comment]
This looks like a JSON body. To send a JSON body you need to specify a custom header "Content-Type" with the value "application/json" and then place your JSON body into the request body text field.

**Comment by Waboodoo** [comment]
I'm closing this with the assumption that the issue is resolved or no longer relevant. Feel free to re-open if I'm wrong.
