### ISSUE TITLE
Post form support

### ISSUE THREAD

**Issue by tdaliviu** [Waboodoo/HTTP-Shortcuts#78]
Correct me if I'm wrong, but I haven't been able to post form data (curl -F or --form option).

**Comment by Waboodoo** [comment]
That is correct. The app currently only supports 2 types of request body: x-www-form-urlencoded parameters and raw text body. I'm planning on adding form-data support in the next version.

**Comment by Waboodoo** [comment]
Support for this was added in version 1.21 (though the cURL parser does not yet recognize the option).
