### ISSUE TITLE
More icons

### ISSUE THREAD

**Issue by Waboodoo** [Waboodoo/HTTP-Shortcuts#8]
Add more built-in icons to choose from

Suggestions include:

- http://recepkutuk.com/bitsies/
- http://emojione.com/

**Comment by marksev1** [comment]
That would be cool, maybe some "flat" icons also. Here are some: https://www.elegantthemes.com/blog/freebie-of-the-week/beautiful-flat-icons-for-free
Perhaps here: https://icons8.com/color-icons/

**Comment by Waboodoo** [comment]
Added in 1.10.0
