### ISSUE TITLE
Use varaible key in another variable

### ISSUE THREAD

**Issue by Flavien06** [Waboodoo/HTTP-Shortcuts#81]
Is it possible to use variable key in another variable?

Exemple
I have http://my.url/hyperion.php?color={{hyperion}}

{{hyperion}} is toogle with "clear" or "{{color}}"
{{color}} is color input

Do you think that be possible?

I would also suggest an option to choose colors with actual method or with a [wheel](https://docs.unrealengine.com/latest/images/Engine/UI/ColorPicker/ColorWheel.jpg).

**Comment by Waboodoo** [comment]
It will need a bit of restructoring and introduces new edge cases like circular dependencies, but I'll see if I can do it. I have some use cases of my own where something like this would be handy.

**Comment by Waboodoo** [comment]
This is now implemented in version 1.20. Variables can be used recursively, up to a recursion depth of 3.

It will be part of the next release, coming sometime next week or the week after.

**Comment by Waboodoo** [comment]
Closing this now as this feature is now available in v1.20
