### ISSUE TITLE
Feature Request: Pass data to and from the Tasker plugin

### ISSUE THREAD

**Issue by pacobyte** [Waboodoo/HTTP-Shortcuts#82]
The main reason I will be using this app is for its Tasker plugin, and more specifically, focusing mostly on POST requests. It would be a tremendous help if I can pass data via Tasker variables into HTTP Shortcuts so that it could make the appropriate request. My usage consists of a number of similar endpoints that vary only slightly, and also, of course, expect different data in the bodies.

On the same note, having the response available for use in Tasker would also make sense to verify that all went well.

**Comment by Waboodoo** [comment]
This sounds like a great idea. I will investigate what can be done.

**Comment by jghaanstra** [comment]
Just got here wanting to request the same thing. Hope this makes it into the app!

**Comment by Waboodoo** [comment]
Passing variables from Tasker into the app is now being built and will be part of the next release (1.20). Passing data back to Tasker will probably have to wait a bit longer.

**Comment by Waboodoo** [comment]
With v1.20 now being released, one part of this is done. You can pass variables from Tasker to HTTP Shortcuts simply by giving them the same name in both apps.

**Comment by jemmail** [comment]
Hi Waboodoo, many thanks for you app ! 
I've tried with no luck to pass variable from Tasker to HTTP Shortcuts.
How do you declare it in HTTP Shortcuts ? as Constant ? with a default value ?
I know in Tasker UpperCase and Lower Case variable is used for context/visibility...

Do you have any tips ?
Regards from Switzerland

**Comment by Waboodoo** [comment]
If you want to pass a variable from Tasker to HTTP Shortcuts you need to create a variable in HTTP Shortcuts with the exact same name, i.e., it's case-sensitive. The type doesn't matter, so you can simply make it a variable and leave the default value empty.

For example, in the screenshot below I have a variable called "lightToggle", which will be passed over to the shortcut if a variable with the same name exists there.
![screenshot_2018-05-07-14-35-55](https://user-images.githubusercontent.com/2445563/39703367-275f7358-5208-11e8-8ad9-1ba979c11c53.png)

Regards from Switzerland as well

**Comment by matrpedreira** [comment]
I'm trying that on version 1.21.0 and this just doesn't work. I'm able to use my variables inside tasker but Http shortcuts doesn't seem to recognize it.

**Comment by genem2** [comment]
> Is there a way to pass response codes back to Tasker?

I'm trying to have Tasker request data from [Home Assistant](https://www.home-assistant.io), which completes fine. I just assumed I could set a Tasker variable with _Extract from Body_. Guess not, so here I am at this post.

This would really be valuable since so much is being maintained in Home Assistant.  Would appreciate the consideration.

**Comment by jowadmax** [comment]
The Tasker plug-in is very powerful, but I wish it has the ability to send variables from the app to Tasker.

I currently use the app alongside Tasker to control my smart lights, but I need to read the lights' state to create a toggle feature.
The Tasker plug-in doesn't currently pass variables back from the app to Tasker.

Having that feature would make this app much more powerful! Looking forward to hearing updates about that feature!

**Comment by Akalsharan** [comment]
Hello.

Sorry to reply to such an old thread (and extra apologies if this has been dealt with in a more recent post), but just wondering if there has been any update in passing data/variable/responses back to Tasker through the plug-in? For me, this would be useful as I'd like to get Tasker to perform specific actions if there has been an error within HTTP-Shortcut.

Keep up the great work.

**Comment by Waboodoo** [comment]
I am adding a `triggerTaskerTask` function to version 1.34.0, which allows to trigger an existing task in Tasker by name, and supports passing along one or more local variables. I'm also planning to add a function to send arbitrary intents at some point, which could be used to achieve the same, but I don't know yet when I'll get around to do that or how it will work.

**Comment by Waboodoo** [comment]
Version 1.34.0 is now released. It adds support for a `triggerTaskerTask` function (see [documentation](https://http-shortcuts.rmy.ch/scripting#trigger-tasker-task)) and `sendIntent` function (see [documentation](https://http-shortcuts.rmy.ch/scripting#send-intent). With these it is possible to trigger a task in Tasker (or any other automation app) and send some data along.
