### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by dshanske** [Waboodoo/HTTP-Shortcuts#85]
I just found your app and it fits a very useful need for me. I am manually adding an authorization token header into the app in order for it to send post requests to an API. Wondering if there might be a way to integrate this and make it easier. Wanted to ask/discuss.

**Comment by Waboodoo** [comment]
How does that API work, i.e., where does the API token come from, and how would you want to add it instead?

**Comment by dshanske** [comment]
I have pluggable authentication options on the system. Oauth2 is one. Right now, I set up an application password style interface that I pasted into the header.

**Comment by dshanske** [comment]
But as far as I understand, doesn't Android support authentication callbacks?

**Comment by Waboodoo** [comment]
Closing this now, as the topic has not come up again, so I'm assuming the current auth options are sufficient for most users.
