### ISSUE TITLE
Feature: Slider Variable

### ISSUE THREAD

**Issue by Casmithy** [Waboodoo/HTTP-Shortcuts#86]
It would be nice to have a numeric slider type variable with definable min, max and step values.

**Comment by Waboodoo** [comment]
Thanks for the input. This is already on my backlog as it has been requested before. I'm planning to add it in the next version, though I currently don't have that much time to work on this project, so it might be a while. Stay tuned.

**Comment by Waboodoo** [comment]
This is now implemented and will be released in version 1.19.
