### ISSUE TITLE
One Shortcut to open multiple urls

### ISSUE THREAD

**Issue by randomandy1314** [Waboodoo/HTTP-Shortcuts#90]
First off, thank you for such a handy app.

I have urls that activate devices around my home so having easy to create and access shortcuts is extremely handy.

I currently have to press 3 shortcuts when I get up in the morning (tv,hifi,lamp) so is it possible to combine these urls into one shortcut? Being able to have to create scenarios like 'waking up' (turns everything on) and 'bed time' (turns everything off) would be very handy.

"I recommend Elixir 2 - Widgets, which I personally use to combine multiple shortcuts into a nice looking widget."

I had a look at this but cant get my head around it... Does Elixir integrate with your HTTP Shortcuts or do you mean it will combine multiple shortcuts independently of HTTP Shortcuts?

This help request is maybe outside you're remit but I got tired of searching for something that I thought should be easy.

Any help appreciated.

Thanks.

**Comment by ritiek** [comment]
Executing multiple shortcuts on single tap sounds like something possible with Tasker.

You should be able to create a task (Action > Plugin > HTTP Shortcuts) that executes all the shortcuts you want to and then group them in a Tasker widget.

**Comment by Waboodoo** [comment]
I agree with @ritiek. If you want to trigger multiple shortcuts in sequence, you can use an automation app like Tasker or E-Robot and combine them there.

The "Elixir 2 - Widgets" app is only used to create nice home screen widgets. You can combine it with Tasker or E-Robot. I personally use it to create widgets which trigger E-Robot tasks, which internally contain HTTP Shortcuts. I know it sounds complicated, using 3 different apps, but you can get some nice workflows.

**Comment by randomandy1314** [comment]
Thanks guys, yous were absolutely correct.

--------

Quick Guide for other Tasker Novices like me...

1. Open Tasker and go to 'Tasks' tab
2. Press the 'Add' sign and give your Task a name
3. Press the 'Add' sign and select 'Plugin'
4. Choose the 'HTTP Shortcuts' plugin
5. On the 'Execute HTTP Shortcut' screen press the 'Edit' (pencil icon) next to 'Configuration' and select the HTTP Shortcut you would like to launch
6. Press the 'Back' arrow
7. Repeat steps 3 to 6 for all the shortcuts you want to launch from the one shortcut (note: I had to add a one second 'WAIT' in between shortcuts, on the screen where you select plugin just use the filter for 'wait')
8. Once all the shortcuts have been added press the 'Back' arrow
9. Now the the task has been configured press 'Back' to go to your Homescreen and long press an empty part of screen
10. Select 'Widgets' and scrolled down to 'Tasker - Task 1 x 1' and long press and move the widget to Homescreen
11. Select the task name you create
12. Choose an icon but pressing the icon selection icon at the bottom
13. Press the 'Back' arrow to save the shortcut task
14. Done. Your shortcut will now launch the HTTP Shortcuts you selected earlier on

Notes: 
My Tasker created shortcut wasn't working until (unsurprisingly) Tasker was enabled from inside the app...Enable Tasker option seems hidden away to me but can be found on the Tasker main screen behind the 3 vertical dots icon in the top right.

Tasker saves selections by using the 'Back' arrow so always hit that to save, why they couldn't have used a 'Tick' like everyone else I do not know.

--------

Hopefully useful to someone, thanks again for the guidance guys.

**Comment by Waboodoo** [comment]
As of version 1.32.0 it is possible to create "Multi-Shortcuts" inside the app, which make it easy to have one shortcut trigger multiple other shortcuts. No need to use a third-party app like Tasker anymore. As such, I'm closing this issue now.
