### ISSUE TITLE
Feature Request: Response in browser

### ISSUE THREAD

**Issue by 36bian** [Waboodoo/HTTP-Shortcuts#93]
Hi, I use HTTP-Shortcuts to simulate some requests, but the form of the response is not easy to see

I want to be able to view it in a browser, like chrome, and I did not find this feature in the software, but I am sure this feature is still very useful.

Seemingly indirectly through the tasker, but this is very tedious, so I hope  can provide native support

Thanks

**Comment by Waboodoo** [comment]
I will consider this, though from a technical point of view, this might not behave as expected.

All I can do is have Chrome (or whatever browser is installed) open a temporary file which contains the response, but not the response itself. This could cause strange behavior, e.g., relative links in the response would not work, which might brake styling and scripts.

**Comment by 36bian** [comment]
Even though the style is somewhat problematic, it is better to see than in the window or Toast, I think🙂
So, try your best

**Comment by Waboodoo** [comment]
Closing this now because this is now kinda possible. If the "Content-Type" header of the response indicates that it is an HTML page, the app will render the response inside a webview, which should cover most of this usecase.
