### ISSUE TITLE
POST http requests fail

### ISSUE THREAD

**Issue by Nemmya** [Waboodoo/HTTP-Shortcuts#94]
I have a POST request that used to work for a few months and ever since the last app update it says: " super.getBody() must not be null"
Thanks

**Comment by Waboodoo** [comment]
Thanks for reporting this. I'll look into it.
To help me debug this, it would be great if you could answer the following questions:
- Does your shortcut use POST parameters and/or a custom request body?
- Did you ever export & import this shortcut, and if so, did you make changes to the JSON file?

**Comment by Nemmya** [comment]
It uses custom request body in addition to some regular request headers.
No to import/export.
Many thanks!

**Comment by Waboodoo** [comment]
This should be fixed in version 1.21. Please re-open if the problem still exists.
