### ISSUE TITLE
Feature: Make date/time variables to pick current date/time

### ISSUE THREAD

**Issue by thejeshgn** [Waboodoo/HTTP-Shortcuts#97]
As of now user has to pick the date and time. Can we have an option where instead of user selecting, the app can pickup current date/time.

**Comment by Waboodoo** [comment]
I'm already planning on adding something like this in an upcoming version, though I can't yet say when it will be available.

**Comment by twcdk1** [comment]
Hi
Are you still planning to release this function?
I really hope so, I would be a very nice feature.

**Comment by Waboodoo** [comment]
Yes, it's still planned. I'm currently working on a few other changes first, so it may take a while for this to make it into the app, though.

**Comment by Waboodoo** [comment]
Closing this now as it is now possible to achieve this with scripting. For an example see https://http-shortcuts.rmy.ch/scripting

**Comment by thejeshgn** [comment]
Works. Thank you.

Would be great if I can pull out the current location too.

**Comment by Waboodoo** [comment]
Getting the location would mean that the app needs to request additional permissions for something that it doesn't really need. This could put the app into a bad light, which is something I would like to avoid. As such, implementing this is not trivial, so I'll put it on the backlog for now. I do see that there is good value in it, but it is a bit of an edge-case for this app, so maybe instead I'll try to improve the interaction with other automation apps such as Tasker, which can more easily get the location information and pass it into the HTTP Shortcuts app.
